<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

// phpcs:disable Magento2.Files.LineLength.MaxExceeded

use Magento\Checkout\Block\Cart\Item\Renderer;
use Magento\Framework\Escaper;

/** @var Renderer $block */
/** @var Escaper $escaper */

$item = $block->getItem();
$product = $item->getProduct();
$productSku = $product->getSku();
$isVisibleProduct = $product->isVisibleInSiteVisibility();

// Whizzy Helper
$whizzyHelper = $this->helper('ShopWhizzy\DigitalTheme\Helper\Data');
$product_image_background = (($whizzyHelper->getConfigValue('general/product_image_background')) ? 'bg-whizzy-artic' : '');
$product_image_background_custom = (($product_image_background_custom_value = $whizzyHelper->getConfigValue('general/product_image_background_custom')) ? "style=\"background-color:{$product_image_background_custom_value}\";" : '');
$product_image_background_mixblend = ($whizzyHelper->getConfigValue('general/product_image_background_mixblend') ? 'mix-blend-multiply' : '');

?>
<div
    class="cart item grid grid-cols-3 lg:grid-cols-7 items-center gap-4 item-info border-b border-whizzy-separator mb-2 py-2 lg:py-4">
    <div data-th="<?= $escaper->escapeHtml(__('Item')) ?>"
        class="col item col-span-4 flex gap-4 lg:gap-8 text-left w-full sm:flex-nowrap lg:w-auto justify-center lg:justify-start items-center h-full">
        <?php if ($block->hasProductUrl()): ?>
            <a href="<?= $escaper->escapeUrl($block->getProductUrl()) ?>"
                title="<?= $escaper->escapeHtmlAttr($block->getProductName()) ?>" tabindex="-1"
                class="product-item-photo shrink-0">
            <?php else: ?>
                <span class="product-item-photo shrink-0">
                <?php endif; ?>
                <div class="bg-whizzy-artic px-2 lg:px-4 rounded-lg h-fit" <?= $product_image_background_custom ?>>
                    <div class="block shrink-0 w-full mx-auto <?= $product_image_background_mixblend ?>">
                        <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')
                            ->setTemplate('Magento_Catalog::product/image.phtml')
                            ->toHtml() ?>
                    </div>
                </div>
                <?php if ($block->hasProductUrl()): ?>
            </a>
        <?php else: ?>
            </span>
        <?php endif; ?>
        <div class="product-item-details grow">
            <div class="product-item-name text-heading text-2xl">
                <?php if ($block->hasProductUrl()): ?>
                    <div class="flex flex-col gap-2 lg:gap-3 h-full">
                        <a href="<?= $escaper->escapeUrl($block->getProductUrl()) ?>"
                            class="text-base lg:text-lg font-medium text-whizzy-body whitespace-normal">
                            <?= $escaper->escapeHtml($block->getProductName()) ?>
                        </a>
                        <span class="text-whizzy-graylighter text-sm">
                            <?= __('Sku: ') ?>     <?= __($productSku) ?>
                        </span>
                    </div>
                <?php else: ?>
                    <span class="text-base lg:text-lg font-medium text-whizzy-body whitespace-normal">
                        <?= $escaper->escapeHtml($block->getProductName()) ?>
                    </span>
                    <span class="text-whizzy-graylighter text-sm">
                        <?= __('Sku: ') ?>     <?= __($productSku) ?>
                    </span>
                <?php endif; ?>
            </div>
            <?php if ($messages = $block->getMessages()): ?>
                <?php foreach ($messages as $message): ?>
                    <div class="cart item message <?= $escaper->escapeHtmlAttr($message['type']) ?>">
                        <div><?= $escaper->escapeHtml($message['text']) ?></div>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
            <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
            <?php if ($addInfoBlock): ?>
                <?= $addInfoBlock->setItem($item)->toHtml() ?>
            <?php endif; ?>
        </div>
    </div>

    <div class="col price block w-full sm:w-1/3 lg:w-auto lg:table-cell text-start">
        <span class="lg:hidden font-regular">
            <?= $escaper->escapeHtml(__('Price')) ?>
        </span>
        <?= $block->getUnitPriceHtml($item) ?>
    </div>

    <div class="col qty block w-full sm:w-1/3 lg:w-auto lg:table-cell text-start">
        <div class="field qty">
            <div class="control qty">
                <label style="margin-bottom: 0px;" for="cart-<?= $escaper->escapeHtmlAttr($item->getId()) ?>-qty">
                    <span class="label sr-only"><?= $escaper->escapeHtml(__('Qty')) ?></span>
                    <input id="cart-<?= $escaper->escapeHtmlAttr($item->getId()) ?>-qty"
                        name="cart[<?= $escaper->escapeHtmlAttr($item->getId()) ?>][qty]"
                        value="<?= $escaper->escapeHtmlAttr($block->getQty()) ?>" type="number" size="4" step="any"
                        title="<?= $escaper->escapeHtmlAttr(__('Qty')) ?>"
                        class="qty form-input px-2 py-2 w-20 text-center" required min="0" data-role="cart-item-qty" />
                </label>
            </div>
        </div>
    </div>

    <div class="col block w-full sm:w-1/3 lg:w-auto lg:table-cell text-start [&_.towishlist]:hidden">
        <?= /* @noEscape */ $block->getActions($item) ?>
    </div>

</div>