<?php
declare(strict_types=1);


use Mirasvit\LayeredNavigation\Model\Config\ExtraFilterConfigProvider;

/**
 * @var $block \Mirasvit\LayeredNavigation\Block\Renderer\SearchRenderer
 * @var $escaper \Magento\Framework\Escaper
 */

$attributeCode = $block->getAttributeCode();
?>

<div class="mst-nav__label mst-nav__search" data-mst-nav-filter="search" id="mst-nav__search" x-data="{...initLabelRenderer(), ...initSearchRenderer()}" x-init="initSearch()">
    <div class="mst-nav__search-field">
        <div class="mst-nav__search-wrapper relative">
        <label for="mst-nav__search-filter"></label>
        <input
            type="text"
            name="<?= ExtraFilterConfigProvider::SEARCH_FILTER_FRONT_PARAM ?>"
            placeholder="<?= $block->getFilter()->getName() ?>"
            id="mst-nav__search-filter"
            autocomplete="off"
            class="form-input w-full"
        >
        <a id="mst-nav__search-apply" href="" class="action search absolute right-1 top-2.5 <?= !$block->isUseFulltext() ? 'hidden' : '' ?>" data-element="filter" @click="handleClick">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="w-8 h-8 md:h-6 md:w-6 hover:text-black" width="25" height="25">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
            </svg>
        </a>
        </div>
        <div class="mst-nav__search-suggestion border-container absolute w-full left-0 md:w-96 max-h-96 z-10 card overflow-y-auto" id="mst-nav__search-suggestion" style="display: none"></div>
    </div>

    <ol class="items">
        <?php foreach ($block->getAppliedSearchTerms() as $term): ?>
            <div class="filter-current">
                <li data-element="filter" class="mst-nav__state-filter item _checked _highlight" <?=  $block->isHighlightEnabled() ? ('style="color: ' . $block->getHighlightColor() . '"') : ''?>>
                    <span class="filter-value"><?= $term['label'] ?></span>
                    <a class="mst-nav__search-term action remove" href="<?= $term['url'] ?>" @click="handleClick">X</a>
                </li>
            </div>
        <?php endforeach; ?>
    </ol>
</div>

