<?php
//@codingStandardsIgnoreFile
/** @var \Mirasvit\Search\Block\Index\Magento\Catalog\Category $block */

$collection = $this->getCollection();
?>
<div class="mst-search__index mst-search__index-magento-catalog-category mt-6 mb-12">
    <ul class="mst-search__list list-disc">
        <?php foreach ($collection as $item): ?>
            <?php $path = $block->getFullPath($item->getId()); ?>
            <li class="mb-2 uppercase text-sm">
                <div class="mst-search__index-title _crumbs hover:underline">
                    <?php foreach ($path as $parent): ?>
                        <a href="<?= $parent->getUrl() ?>"><?= $parent->getName() ?></a>
                    <?php endforeach ?>

                    <a href="<?= $item->getUrl() ?>"><?= $item->getName() ?></a>
                </div>
            </li>
        <?php endforeach ?>
    </ul>
</div>