<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Hyva\Theme\ViewModel\SvgIcons;
use Hyva\Theme\ViewModel\Store;
use Magento\Framework\Escaper;
use Mirasvit\Review\Block\Form;
use Hyva\Theme\ViewModel\ReCaptcha;

//phpcs:disable Generic.Files.LineLength

/** @var Escaper $escaper */
/** @var Form $block */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

/** @var Store $viewModelStore */
$viewModelStore = $viewModels->require(Store::class);

$formId = 'review_form';

// Do not replace this with $viewModels->require(ReCaptcha::class); that might break the dependency
// on Magento_ReCaptchaReview module
/** @var ReCaptcha $recaptcha */
$recaptcha = $block->getData('viewModelRecaptcha');


?>
<div class="mx-auto py-6 items-center" id="review-form" tabindex="-1">
    <div class="w-full">

        <?php if ($block->getAllowWriteReviewFlag()): ?>
            <form class="review-form"
                  id="<?= $escaper->escapeHtmlAttr($formId) ?>"
                  action="<?= $escaper->escapeUrl($block->getAction()) ?>"
                  method="post"
                  enctype='multipart/form-data'
            >
                <input name="form_key" type="hidden" value="<?= /* @noEscape */ $block->getFormKey() ?>"/>
                <?= $block->getChildHtml('form_fields_before') ?>
                <?= $recaptcha ? $recaptcha->getInputHtml(ReCaptcha::RECAPTCHA_FORM_ID_PRODUCT_REVIEW) : '' ?>
                <fieldset>
                    <legend class="text-sm">
                        <span>
                            <?= $escaper->escapeHtml(
                                __("You're reviewing:")
                            ) ?>
                        </span>
                        <span class="font-semibold">
                            <?= $escaper->escapeHtml($block->getProductInfo()->getName()) ?>
                        </span>
                    </legend>
                    <?php if ($block->getRatings() && $block->getRatings()->getSize()): ?>
                        <fieldset name="rating-group">
                            <div class="flex flex-col mt-4 mb-3">
                                <div class="text-md <?php if ($block->getRatings()->getSize() <= 1): ?>hidden<?php endif ?>">
                                    <?= $escaper->escapeHtml(__('Your Rating')) ?>:
                                </div>
                                <div class="mt-4">
                                    <div id="product-review-table">
                                        <?php foreach ($block->getRatings() as $rating): ?>
                                            <div class="table-row">
                                                <label
                                                    class="table-cell pr-6 align-middle text-left"
                                                    id="<?= $escaper->escapeHtml($rating->getRatingCode()) ?>_rating_label"
                                                >
                                                    <span>
                                                        <?php if ($block->getRatings()->getSize() <= 1): ?>
                                                            <?= $escaper->escapeHtml(__('Your Rating')) ?>:
                                                        <?php else: ?>
                                                            <?= $escaper->escapeHtml($rating->getRatingCode()) ?>
                                                        <?php endif ?>
                                                    </span>
                                                </label>
                                                <div
                                                    class="flex flex-row grow-0 focus-within:ring-4 ring-primary ring-opacity-50"
                                                    x-data="{ clickedRatingId: 0 }"
                                                >
                                                    <?php $options = $rating->getOptions(); ?>
                                                    <?php $iterator = 1;
                                                    foreach ($options as $option): ?>
                                                        <div
                                                            class="relative"
                                                            @click="clickedRatingId = <?= (int)$iterator ?> || 0"
                                                        >
                                                            <label
                                                                class="rating-<?= (int)$iterator ?> m-0 cursor-pointer text-gray-400"
                                                                for="<?= $escaper
                                                                    ->escapeHtmlAttr(
                                                                        $rating->getRatingCode() . '_' . $option->getValue()
                                                                    ) ?>"
                                                                id="<?= $escaper
                                                                    ->escapeHtmlAttr(
                                                                        $rating->getRatingCode() . '_' . $option->getValue()
                                                                    ) ?>_label"
                                                            >
                                                                <span :class="<?= (int)$iterator ?> <= clickedRatingId
                                                                    ? 'text-yellow-400'
                                                                    : 'text-gray-400'"
                                                                >
                                                                    <?= $heroiconsSolid->starHtml('', 32, 32, ["aria-hidden" => "true"]); ?>
                                                                </span>
                                                                <input
                                                                    class="absolute opacity-0 bottom-0 left-0 cursor-pointer"
                                                                    type="radio"
                                                                    <?php if ($iterator === 1): ?>required<?php endif; ?>
                                                                    name="ratings[<?= $escaper->escapeHtmlAttr($rating->getId()) ?>]"
                                                                    id="<?= $escaper->escapeHtmlAttr($rating->getRatingCode() . '_' . $option->getValue()) ?>"
                                                                    value="<?= $escaper->escapeHtmlAttr($option->getId()) ?>"
                                                                    <?php if ($iterator === 1): ?>
                                                                        aria-label="<?= $escaper->escapeHtmlAttr(__('1 star')) ?>"
                                                                    <?php else: ?>
                                                                        aria-label="<?= $escaper->escapeHtmlAttr(__('%1 stars', $iterator)) ?>"
                                                                    <?php endif; ?>
                                                                />
                                                            </label>

                                                        </div>
                                                        <?php $iterator++; ?>
                                                    <?php endforeach; ?>
                                                </div>
                                            </div>
                                        <?php endforeach; ?>
                                    </div>
                                    <input type="hidden" name="validate_rating" value=""/>
                                </div>
                            </div>
                        </fieldset>
                    <?php endif ?>
                    <div>
                        <div>
                            <label for="nickname_field" class="sr-only">
                                <span><?= $escaper->escapeHtml(__('Nickname')) ?></span>
                            </label>
                            <div>
                                <input class="form-input mt-3 block w-full"
                                       required
                                       placeholder="<?= $escaper->escapeHtmlAttr(__('Nickname') . '*') ?>" type="text"
                                       name="nickname" id="nickname_field"/>
                            </div>
                        </div>
                        <div>
                            <label for="summary_field" class="sr-only">
                                <span><?= $escaper->escapeHtml(__('Summary')) ?></span>
                            </label>
                            <div>
                                <input class="form-input mt-3 block w-full"
                                       required
                                       placeholder="<?= $escaper->escapeHtml(__('Summary') . '*') ?>" type="text"
                                       name="title"
                                       id="summary_field"/>
                            </div>
                        </div>
                        <div>
                            <label for="review_field" class="sr-only">
                                <span><?= $escaper->escapeHtml(__('Review')) ?></span>
                            </label>
                            <div>
                            <textarea class="form-input mt-3 block w-full"
                                      required
                                      placeholder="<?= $escaper->escapeHtml(__('Review') . '*') ?>" name="detail"
                                      id="review_field" cols="5"
                                      rows="3"></textarea>
                            </div>
                        </div>

                        <?php if (method_exists($block, 'displayProsAndCons') && $block->displayProsAndCons()): ?>
                            <div class="field review-field-text">
                                <label for="pros_field" class="sr-only">
                                    <span><?= $block->escapeHtml(__('Pros')) ?></span>
                                </label>
                                <textarea name="pros" id="pros_field" cols="5" rows="3" class="form-input mt-3 block w-full" placeholder="<?= $block->escapeHtml(__('Pros')) ?>"></textarea>
                            </div>
                            <div class="field review-field-text">
                                <label for="cons_field" class="sr-only">
                                    <span><?= $block->escapeHtml(__('Cons')) ?></span>
                                </label>
                                <textarea name="cons" id="cons_field" cols="5" rows="3" class="form-input mt-3 block w-full" placeholder="<?= $block->escapeHtml(__('Cons')) ?>"></textarea>
                            </div>
                        <?php endif;?>

                        <?= $block->getChildBlock('review.image')->toHtml() ?>
                    </div>
                </fieldset>
                <div class="my-3">
                    <div>
                        <button type="submit"
                                class="btn btn-primary">
                            <span>
                                <?= $escaper->escapeHtml(__('Submit Review')) ?>
                            </span>
                        </button>
                    </div>
                    <?= $block->getChildHtml('form_additional_after') ?>
                    <?= $recaptcha ? $recaptcha->getLegalNoticeHtml(ReCaptcha::RECAPTCHA_FORM_ID_PRODUCT_REVIEW) : '' ?>
                </div>
            </form>
        <?php else: ?>
            <div
                id="review-form"
                tabindex="-1"
                class="message warning notlogged mt-3"
            >
                <div class="pb-6">
                    <?= $escaper->escapeHtml(
                        __(
                            'Only registered users can write reviews. Please <a href="%1" class="underline">Sign in</a> or <a href="%2" class="underline">create an account</a>',
                            $block->getLoginLink(),
                            $block->getRegisterUrl()
                        ),
                        ['a']
                    ) ?>
                </div>
            </div>
        <?php endif ?>
    </div>
</div>
