<?php
declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\HeroiconsSolid;

/** @var \Mirasvit\Review\Block\Product\Review $block */

$review = $block->getReview();

if (!$review)
{
    return '';
}

/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);
?>

<div itemscope itemprop="review" itemtype="http://schema.org/Review"
    class="border p-6 border-gray-300 rounded-lg bg-white mb-6">
    <?php if (count($review->getRatingVotes())): ?>
        <div class="table">
            <?php foreach ($review->getRatingVotes() as $vote): ?>
                <?php
                $rating = $vote->getPercent();
                $ratingSteps = 5;
                $starsFilled = is_numeric($rating) ? floor($rating / 100 * $ratingSteps) : 0;
                $starsEmpty = floor($ratingSteps - $starsFilled);
                ?>
                <div class="table-row" itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">
                    <div class="table-cell pr-6 align-middle text-left">
                        <?= $escaper->escapeHtml($vote->getRatingCode()) ?>
                    </div>
                    <span class="hidden" itemprop="ratingValue"><?= /** @noEscape */ $starsFilled; ?></span>
                    <div class="flex flex-row" role="img"
                        aria-label="<?= $escaper->escapeHtmlAttr(__('%1 rating. %2 out of %3 stars', $block->getReview()->getProduct()->getName(), $starsFilled, $ratingSteps)) ?>">
                        <?php $i = 0; ?>
                        <?php while ($i < $starsFilled): ?>
                            <?= $heroiconsSolid->starHtml('text-yellow-400', 24, 24, ["aria-hidden" => "true"]); ?>
                            <?php $i++; ?>
                        <?php endwhile; ?>
                        <?php $i = 0; ?>
                        <?php while ($i < $starsEmpty): ?>
                            <?= $heroiconsSolid->starHtml('text-gray-400', 24, 24, ["aria-hidden" => "true"]); ?>
                            <?php $i++; ?>
                        <?php endwhile; ?>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
    <div class="text-lg my-2 flex items-center" itemprop="name">
        <?= $escaper->escapeHtml($review->getTitle()) ?>
        <?php if ($block->displayProductOption()): ?>
            <div class="review-product-option ml-3 text-sm text-secondary">
                <?= /* @noEscape */ $block->getProductOptions($review); ?>
            </div>
        <?php endif; ?>
    </div>
    <div class="flex flex-wrap items-center">
        <span><?= $escaper->escapeHtml(__('Review by')) ?></span>
        <strong class="ml-1" itemprop="author" itemscope itemtype="https://schema.org/Person">
            <span itemprop="name"><?= $escaper->escapeHtml($review->getNickname()) ?></span>
        </strong>
        <?php if ($block->displayVerifiedBuyer() && $review->getIsVerifiedBuyer()): ?>
            <span class="ml-1 text-green-500">Verified Buyer</span>
        <?php endif; ?>
        <time class="text-gray-700 inline-block ml-2" itemprop="datePublished"
            datetime="<?= $escaper->escapeHtmlAttr($block->getFormattedDate($review->getCreatedAt())); ?>">
            <span class="sr-only">
                <?= $escaper->escapeHtml($block->getFormattedDate($review->getCreatedAt())) ?>
            </span>
            <span aria-hidden="true">
                <?= $escaper->escapeHtml($block->getFormattedDate($review->getCreatedAt())) ?>
            </span>
        </time>
        <?php if ($block->getLocation($review)): ?>
            <div class="review-country text-secondary">
                <strong>
                    <?= /* @noEscape */ $block->getLocation($review); ?>
                </strong>
                <?php if ($block->getCountryCode($review)): ?>
                    <div class="flag flag-<?= $block->escapeHtmlAttr($block->getCountryCode($review)) ?>"></div>
                <?php endif; ?>
            </div>
        <?php endif; ?>
    </div>
    <div class="mt-2" itemprop="description">
        <?= /* @noEscape */ nl2br($escaper->escapeHtml($review->getDetail())) ?>
    </div>
    <?php
    echo $block->getChildBlock('proscons')
        ->setReview($review)
        ->toHtml();
    ?>
    <?php
    if ($block->isShowGallery())
    {
        echo $block->getChildBlock('review.gallery')
            ->setReview($review)
            ->setProductId((int)$review->getProductId())
            ->toHtml();
    }
    ?>
    <?php if ($commentBlock = $block->getChildBlock('review.comment')): ?>
        <?= $commentBlock->setEntityType('review')->setEntityId((int)$review->getId())->toHtml() ?>
    <?php endif; ?>
</div>