<?php
/**
 * @category    FishPig
 * @package     FishPig_WordPress
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php $posts = $block->getPosts() ?>
<?php if (count($posts) > 0): ?>
    <div class="post-list-wrapper">
        <ol class="post-list grid grid-cols-1 lg:grid-cols-2 gap-6 lg:gap-8 post-list">
            <?php foreach ($posts as $post): ?>
                <?php if ($renderedPostHtml = $block->renderPost($post)): ?>
                    <?php // phpcs:ignore -- long line ?>
                    <li class="item<?php if ($post->isSticky()): ?> is-sticky<?php endif; ?><?php if ($postFormat = $post->getPostFormat()): ?> <?= $block->escapeHtmlAttr($postFormat) ?><?php endif; ?>">
                        <?= /* @noEscape */ $renderedPostHtml ?>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ol>
        <div class="mt-4 lg:mt-6">
            <?= /* @noEscape */  $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif; ?>