<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Checkout\Block\Cart\Item\Renderer\Actions\Remove;
use Magento\Framework\Escaper;

/** @var Remove $block */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */

$themeIcons = $viewModels->require(\MgtWizards\Base\ViewModel\ThemeIcons::class);
$item = $block->getItem();

if ($item->getProductType() === 'configurable') {
    $productOptions = $item->getProduct()->getTypeInstance()->getOrderOptions($item->getProduct());
    $productName = $productOptions["simple_name"];
} else {
    $productName = $item->getName();
}
?>
<button
    class="action action-delete flex items-center justify-center gap-2 text-whizzy-graylighter font-medium hover:text-whizzy-body transitition-all duration-200"
    x-data="{}" @click.prevent='hyva.postForm(<?= /* @noEscape */ $block->getDeletePostJson() ?>)'
    aria-label="<?= $escaper->escapeHtmlAttr(__('Remove %1', $productName)) ?>" type="button">
    <?= $themeIcons->renderHtml('close', '', 16, 16, ["aria-hidden" => "true"]) ?>
    <?= __('Remove') ?>
</button>