<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Shop By Brand Compatibility with Hyva for Magento 2
 */
/** @var HeroiconsOutline $heroicons */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

$heroicons = $viewModels->require(HeroiconsOutline::class);
$themeIcons = $viewModels->require(\MgtWizards\Base\ViewModel\ThemeIcons::class);
// phpcs:disable Generic.Files.LineLength.TooLong
?>
<section class="my-12 text-gray-700 body-font" x-data="{...amMoreFromBrand(), ...amMoreFromBrandSlider()}"
    @resize.window.debounce="calcPageSize(); $nextTick( function() { calcActive() })" x-init="moreFromBrandsInit()">
    <template x-if="products && products.length">
        <div class="relative w-full">
            <div class="w-full flex justify-center">
                <div class="text-2xl lg:text-4xl font-bold tracking-tight pb-4 text-whizzy-body mb-12" x-html="title">
                </div>
            </div>
            <div class="relative w-full overflow-x-hidden">
                <div class="relative flex flex-nowrap w-full overflow-auto transition-all js_slides snap"
                    @scroll.debounce="calcActive">
                    <template x-for="product in products" :key="product.id">
                        <?= $block->getChildHtml('product_item') ?>
                    </template>
                    <div :class="{
                        'js_dummy_slide w-1/2 md:w-1/3 lg:w-1/4 xl:w-1/5 flex flex-shrink-0 py-1' : pageFillers > 0
                        }"></div>
                    <div :class="{
                        'js_dummy_slide w-1/2 md:w-1/3 lg:w-1/4 xl:w-1/5 flex flex-shrink-0 py-1' : pageFillers > 1
                        }"></div>
                    <div :class="{
                        'js_dummy_slide w-1/2 md:w-1/3 lg:w-1/4 xl:w-1/5 flex flex-shrink-0 py-1' : pageFillers > 2
                        }"></div>
                </div>
            </div>
            <div style="min-height: 65px">
                <template x-if="products.length && products.length > pageSize">
                    <div class="flex items-center justify-center flex-1 p-4" x-cloak>
                        <button aria-label="<?= $escaper->escapeHtmlAttr(__('Previous')) ?>"
                            class="bg-white shadow-whizzy-base p-2 lg:p-4 -mb-16 -ml-2 lg:-ml-4 text-black rounded outline-none focus:outline-none absolute top-1/2 -left-4 -translate-y-1/2 z-10 opacity-100 cursor-pointer"
                            :class="{ 'invisible' : active === 0 }" @click="getSlider().scrollLeft =
                                (getSlider().scrollWidth / (products.length + pageFillers)) * (active - pageSize);
                                active -= pageSize;">
                            <?= $themeIcons->renderHtml('arrow-left', 'mx-auto', 20, 20) ?>
                        </button>
                        <template x-for="(product, index) in products" :key="index">
                            <span class="flex-shrink-0 block w-2 h-2 mx-1 bg-whizzy-body rounded-full shadow
                                         cursor-pointer" :class="{'bg-opacity-100 w-5': active === index,
                                        'bg-opacity-50': active !== index,
                                        'hidden': (pageSize !== 1 && !!(index % pageSize))
                                        }" @click="getSlider().scrollLeft =
                                          (getSlider().scrollWidth / (products.length + pageFillers)) * index;
                                          active = index;">
                            </span>
                        </template>
                        <button aria-label="<?= $escaper->escapeHtmlAttr(__('Next')) ?>"
                            class="bg-white shadow-whizzy-base p-2 lg:p-4 -mb-16 -mr-2 lg:-mr-4 text-black rounded outline-none focus:outline-none absolute top-1/2 -right-4 -translate-y-1/2 z-10 opacity-100 cursor-pointer"
                            :class="{ 'invisible' : active >= products.length-pageSize }" @click="getSlider().scrollLeft =
                                (getSlider().scrollWidth / (products.length + pageFillers)) * (active + pageSize);
                                active += pageSize">
                            <?= $themeIcons->renderHtml('arrow-right', 'mx-auto', 20, 20) ?>
                        </button>
                    </div>
                </template>
            </div>
        </div>
    </template>
</section>

<?= $block->getChildHtml('more_from_brand_js') ?>