<?php

declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Hyva\Theme\Model\ViewModelRegistry $viewModels */

// The item to render is set on the block before the template is rendered:

$item = $block->getData('item');
$text_color = $item['slide_elements_color'] ?? '';
$slide_main_color = $item['slide_main_color'] ?? '';
$shadow = '';
if ($item['slide_shadow'] == 1)
{
	$shadow = "[&_picture]:before:content-[''] [&_picture]:before:rounded-xl [&_picture]:before:w-full [&_picture]:before:h-full [&_picture]:before:absolute [&_picture]:before:left-0 [&_picture]:before:bottom-0 [&_picture]:before:bg-gradient-to-t [&_picture]:before:from-[#000000] [&_picture]:before:to-[transparent] [&_picture]:before:opacity-10";
}
switch ($text_color)
{
	case 'text-white':
		$btn_classes = 'border-2 border-white text-black bg-white hover:bg-black hover:text-white hover:border-black';
		break;
	case 'text-black':
		$btn_classes = 'border-2 border-black text-white bg-black hover:bg-white hover:text-black hover:border-white';
		break;
	case 'text-whizzy-primary':
		$btn_classes = 'border-2 border-whizzy-primary text-white bg-whizzy-primary hover:bg-whizzy-primary-darker hover:text-white hover:border-whizzy-primary-darker';
		break;
	case 'text-gray-900':
		$btn_classes = 'border-2 border-gray-900 text-white bg-gray-900 hover:bg-white hover:text-black hover:border-white';
		break;
	case 'text-gray-300':
		$btn_classes = 'border-2 border-gray-300 text-black bg-gray-300 hover:bg-black hover:text-white hover:border-black';
		break;
	default:
		$btn_classes = 'border-2 border-black text-white bg-black hover:bg-white hover:text-black hover:border-white';
		break;
}
?>
<div class="w-full h-min relative <?= $shadow ?> <?= $item['slide_classes'] ?>">
	<?= $item['slide_image_html'] ?>
	<?php if ($item['slide_text_html'] != '' || $item['slide_headline'] != '' || $item['slide_heading'] != '' || $item['slide_button_label'] != ''): ?>
		<div class="absolute inset-0 flex justify-center">
			<div class="container mx-auto relative">
				<div class="slide-content p-6 <?= $item['slide_elements_position'] ?>">
					<div class="flex flex-wrap flex-col gap-2 <?= $text_color ?>">
						<?php if ($item['slide_headline'] != ''): ?>
							<div class="uppercase font-semibold" <?= ($slide_main_color) ? 'style="color: ' . $slide_main_color . ';"' : ''; ?>>
								<?= $item['slide_headline'] ?>
							</div>
						<?php endif; ?>
						<?php if ($item['slide_heading'] != ''): ?>
							<div class="text-heading text-3xl lg:text-6xl wrap-balance font-bold mb-2 lg:mb-4">
								<?= $item['slide_heading'] ?>
							</div>
						<?php endif; ?>
						<?php if ($item['slide_text_html'] != ''): ?>
							<div class="text-sm lg:text-base wrap-balance"><?= $item['slide_text_html'] ?></div>
						<?php endif; ?>
						<?php if ($item['slide_button_label'] != ''): ?>
							<div class="mt-3 lg:mt-6">
								<a class="transition-all px-10 py-2.5 text-base rounded-md hover:opacity-75 <?= $btn_classes ?>"
									href="<?= $item['slide_button_url'] ?>" <?= ($slide_main_color) ? 'style="background-color: ' . $slide_main_color . '; border-color: ' . $slide_main_color . ';"' : ''; ?>>
									<span class="p-0 mt-0.5"><?= $item['slide_button_label'] ?></span>
								</a>
							</div>
						<?php endif; ?>
					</div>
				</div>
			</div>
		</div>

	<?php endif; ?>
</div>