<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

// phpcs:disable Magento2.Templates.ThisInTemplate

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Cart\ItemOutput;
use Hyva\Theme\ViewModel\Modal;
use Magento\Checkout\Block\Cart\Grid;
use Magento\Checkout\ViewModel\Cart as CartViewModel;
use Magento\Framework\Escaper;

/** @var Grid $block */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */

/** @var CartViewModel $cartViewModel */
$cartViewModel = $viewModels->require(CartViewModel::class);

/** @var Modal $modalViewModel */
$modalViewModel = $viewModels->require(Modal::class);

/** @var ItemOutput $cartItemOutputViewModel */
$cartItemOutputViewModel = $viewModels->require(ItemOutput::class);
?>
<?php $mergedCells = ($cartItemOutputViewModel->isItemPriceDisplayBoth() ? 2 : 1); ?>
<?= $block->getChildHtml('form_before') ?>
<form action="<?= $escaper->escapeUrl($block->getUrl('checkout/cart/updatePost')) ?>" x-data="{}"
    @submit.prevent="hyva.postCart($event.target)" method="post" id="form-validate"
    class="form form-cart w-full float-left">
    <?= $block->getBlockHtml('formkey') ?>
    <div class="cart table-wrapper<?= $mergedCells == 2 ? ' detailed' : '' ?>">
        <?php if ($block->getPagerHtml()): ?>
            <div class="cart-products-toolbar cart-products-toolbar-top toolbar">
                <?= $block->getPagerHtml() ?>
            </div>
        <?php endif ?>
        <div id="shopping-cart-table sticky top-6">
            <div
                class="cart items hidden lg:grid grid-cols-7 gap-x-4 w-full bg-white shadow-whizzy-header mb-4 py-4 px-6 rounded-lg text-whizzy-graylighter uppercase font-bold text-sm leading-wide">
                <div class="col col-span-4 item text-left" scope="col">
                    <?= $escaper->escapeHtml(__('Product')) ?>
                </div>
                <div class="col price text-left" scope="col">
                    <?= $escaper->escapeHtml(__('Price')) ?>
                </div>
                <div class="col qty text-left" scope="col">
                    <?= $escaper->escapeHtml(__('Qty')) ?>
                </div>
                <div class="col" scope="col">
                </div>
            </div>

            <?php foreach ($block->getItems() as $item): ?>
                <?= $block->getItemHtml($item) ?>
            <?php endforeach ?>
        </div>

        <?php if ($block->getPagerHtml()): ?>
            <div class="cart-products-toolbar cart-products-toolbar-bottom toolbar">
                <?= $block->getPagerHtml() ?>
            </div>
        <?php endif ?>
    </div>
    <div class="cart actions flex flex-col sm:flex-row justify-end gap-4 items-center my-4">
        <?php if ($cartViewModel->isClearShoppingCartEnabled()): ?>
            <script>
                function initClearShoppingCartModal() {
                    return Object.assign(
                        hyva.modal(),
                        {
                            postData: {
                                action: '<?= $escaper->escapeUrl($block->getUrl('checkout/cart/updatePost')) ?>',
                                data: { update_cart_action: 'empty_cart' }
                            }
                        }
                    );
                }
            </script>
            <div x-data="initClearShoppingCartModal()">
                <?= /** @noEscape */ ($confirmation = $modalViewModel->confirm(__('Are you sure?'))->withDetails(__('Are you sure you want to remove all items from your shopping cart?'))) ?>
                <button
                    @click="<?= /** @noEscape */ $confirmation->getShowJs() ?>.then(result => result && hyva.postForm(postData))"
                    type="button" title="<?= $escaper->escapeHtmlAttr(__('Clear Shopping Cart')) ?>" class="action clear"
                    id="empty_cart_button">
                    <span><?= $escaper->escapeHtml(__('Clear Shopping Cart')) ?></span>
                </button>
            </div>

        <?php endif ?>
        <button type="submit" name="update_cart_action" data-cart-item-update="" value="update_qty"
            title="<?= $escaper->escapeHtmlAttr(__('Update Shopping Cart')) ?>"
            class="action update btn text-black hover:text-white bg-gray-300 border-gray-300 py-3.5 px-10 w-full lg:w-auto">
            <?= $escaper->escapeHtml(__('Update Shopping Cart')) ?>
        </button>
    </div>
</form>
<?= $block->getChildHtml('checkout.cart.order.actions') ?>
<?= $block->getChildHtml('shopping.cart.table.after') ?>