<?php
/**
 * @var $block \ShopWhizzy\DigitalTheme\Block\SubCategories
 */
use Magento\Framework\Escaper;
use Magento\Catalog\Model\Category;
use Magento\Catalog\Model\ResourceModel\Product\CollectionFactory;

/** @var Escaper $escaper */
$themeIcons = $viewModels->require(\MgtWizards\Base\ViewModel\ThemeIcons::class);
?>

<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$mediaUrl = $objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');
$subcategories = $category->getChildrenCategories();
$productCollectionFactory = $objectManager->get(CollectionFactory::class);
?>

<?php if (!count($subcategories) > 0): ?>
    <?php
    $subparentid = $category->getParentId();
    $subparentcategory = $objectManager->create('Magento\Catalog\Model\Category')->load($subparentid);
    $childrens = $subparentcategory->getChildrenCategories();
    $childrenscount = count($childrens);
    if ($childrenscount > 0): ?>
        <section class="container">
            <div class="flex flex-col gap-6 lg:gap-12 mt-6 lg:mt-12">
                <div class="flex flex-col gap-3 font-bold">
                    <div class="text-black text-sm font-semibold uppercase mb-3">
                        <?= __("Take a look at") ?>
                    </div>
                    <div class="text-xl lg:text-3xl font-semibold tracking-tight">
                        <?php if ($subparentcategory->getName() == 'Root' || $subparentcategory->getName() == 'Default Category'): ?>
                            <?= __('More options from our shop') ?>
                        <?php else: ?>
                            <?= __('More options inside <a href="%2" class="text-whizzy-primary hover:text-whizzy-primary-darker">%1</a>', $subparentcategory->getName(), $subparentcategory->getUrl()) ?>
                        <?php endif ?>
                    </div>
                </div>

                <ol class="flex flex-wrap gap-2 lg:gap-x-4 snap-proximity snap-x">
                    <?php $i = 1;
                    foreach ($childrens as $subcategory): ?>
                        <?php
                        // Load subcategory
                        $subcategory = $objectManager->create(Category::class)->load($subcategory->getId());

                        // Get product collection for the subcategory and its descendants
                        $productCollection = $productCollectionFactory->create();
                        $productCollection->addCategoryFilter($subcategory)
                            ->addAttributeToFilter('status', \Magento\Catalog\Model\Product\Attribute\Source\Status::STATUS_ENABLED)
                            ->addAttributeToFilter('visibility', [
                                'in' => [
                                    \Magento\Catalog\Model\Product\Visibility::VISIBILITY_BOTH,
                                    \Magento\Catalog\Model\Product\Visibility::VISIBILITY_IN_CATALOG,
                                    \Magento\Catalog\Model\Product\Visibility::VISIBILITY_IN_SEARCH
                                ]
                            ]);
                        $total_count = $productCollection->getSize(); // Get total product count
                        ?>
                        <?php if ($subcategory->getId() != $category->getId()): ?>
                            <li class="item flex items-center w-full md:w-auto">
                                <a class="block relative px-4 py-2 whitespace-nowrap hover:text-white flex items-center gap-2 bg-whizzy-primary-lighter hover:bg-whizzy-primary rounded transition duration-200 w-full md:w-auto justify-between md:justify-center text-sm md:text-base"
                                    href="<?= $subcategory->getUrl() ?>">
                                    <span class="font-semibold"><?= $subcategory->getName() ?></span>
                                    <span
                                        class="bg-white text-whizzy-body p-1 text-xs rounded-md"><?= $escaper->escapeHtml($total_count) ?></span>
                                </a>
                            </li>
                            <?php $i++; ?>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </ol>
            </div>
        </section>
    <?php endif; ?>
<?php endif; ?>