<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Theme\Block\Html\Breadcrumbs;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var Breadcrumbs $block */
/** @var array[] $crumbs */

$themeIcons = $viewModels->require(\MgtWizards\Base\ViewModel\ThemeIcons::class);

// Function to remove trailing slash from URL
$removeTrailingSlash = function ($url)
{
    return rtrim($url, '/');
};
?>
<?php if ($crumbs && is_array($crumbs)): ?>
    <nav class="breadcrumbs" aria-label="Breadcrumb">
        <div class="container">
            <ol class="items list-reset pt-4 lg:pt-6 flex flex-wrap items-center text-sm text-gray-400">
                <?php foreach ($crumbs as $crumbName => $crumbInfo): ?>
                    <li class="item flex items-center <?= $escaper->escapeHtmlAttr($crumbName) ?>">
                        <?php if ($crumbInfo['link']): ?>
                            <a href="<?= $escaper->escapeUrl($removeTrailingSlash($crumbInfo['link'])) ?>"
                                class="no-underline hover:text-whizzy-graylighter"
                                title="<?= $escaper->escapeHtmlAttr($crumbInfo['title']) ?>"><?= $escaper->escapeHtml($crumbInfo['label']) ?></a>
                        <?php elseif ($crumbInfo['last']): ?>
                            <span class="text-whizzy-graylighter font-semibold"
                                aria-current="page"><?= $escaper->escapeHtml($crumbInfo['label']) ?></span>
                        <?php else: ?>
                            <?= $escaper->escapeHtml($crumbInfo['label']) ?>
                        <?php endif; ?>
                    </li>
                    <?php if (!$crumbInfo['last']): ?>
                        <?= $themeIcons->renderHtml('circle-solid-rounded', 'text-gray-400 mx-2 lg:mx-4', 6, 6, ['aria-hidden' => 'true']) ?>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ol>
        </div>
    </nav>
<?php endif; ?>