<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

$blockId = $block->getBlockId() ?: 'collapsible';
$blockClass = $block->getBlockCss();
$blockTitle = $block->getBlockTitle() ?: __('Details');
$isNav = $block->getIsNav() !== null ? $block->getIsNav() : false;

$themeIcons = $viewModels->require(\MgtWizards\Base\ViewModel\ThemeIcons::class);
?>

<div class="bg-white shadow-whizzy-header py-6 px-4 rounded-lg mb-6 <?= $escaper->escapeHtmlAttr($blockClass) ?>"
    x-data="initAccountNavigation()" x-init="checkIsMobileResolution()"
    @resize.window.debounce="checkIsMobileResolution()" @visibilitychange.window.debounce="checkIsMobileResolution()">
    <button type="button" id="<?= $escaper->escapeHtmlAttr($blockId) ?>-title"
        class="group py-2 flex justify-between items-center w-full block md:hidden" @click="blockOpen = !blockOpen"
        :aria-expanded="blockOpen" :aria-disabled="!isMobile" :disabled="!isMobile ? '' : null">

        <span class="text-xl font-bold">
            <?= $escaper->escapeHtml($blockTitle) ?>
        </span>
        <span class="px-1 py-1 bg-white rounded md:hidden" x-ref="AccountNavigationMobileToggleIcon">
            <?= $themeIcons->renderHtml('arrow-down', "transition-transform duration-300 ease-in-out transform group-aria-expanded:rotate-180", 24, 24, ['aria-hidden' => 'true']) ?>
        </span>
    </button>
    <?php if ($isNav): ?>
        <nav id="<?= $escaper->escapeHtmlAttr($blockId) ?>"
            aria-labelledby="<?= $escaper->escapeHtmlAttr($blockId) ?>-title" class="hidden md:block py-3 my-2"
            :class="{ 'hidden': !blockOpen }">
            <?= $block->getChildHtml() ?>
        </nav>
    <?php else: ?>
        <div id="<?= $escaper->escapeHtmlAttr($blockId) ?>" class="hidden md:block py-3 my-2"
            :class="{ 'hidden': !blockOpen }">
            <?= $block->getChildHtml() ?>
        </div>
    <?php endif; ?>
</div>
<script>
    function initAccountNavigation() {
        return {
            isMobile: false,
            blockOpen: false,
            checkIsMobileResolution() {
                const mobileElement = this.$refs.AccountNavigationMobileToggleIcon;
                this.isMobile = mobileElement
                    ? getComputedStyle(mobileElement).display !== 'none'
                    : window.matchMedia('(max-width: 767px)').matches; // Fallback to `md` breakpoint
            }
        }
    }
</script>