<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="pt-4 lg:pt-8">
    <div class="lg:border-t lg:border-whizzy-linee w-full">
        <div
            class="flex justify-start items-center py-4 lg:py-6 text-base text-whizzy-body hover:text-whizzy-graylighter transition-all duration-100 underline font-medium w-fit">
            <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>">
                <span><?= $block->escapeHtml(__('Back')) ?></span>
            </a>
        </div>
    </div>
</div>