<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Magento\Newsletter\Block\Subscribe;
/** @var Subscribe $block */

$firstname = $this->getData('show_firstname');
$lastname = $this->getData('show_lastname');
$type = $this->getData('layout_type') ? $this->getData('layout_type') : 'inline';
$id = $this->getHtmlId();
?>
<div class="mgz-newsletter-form-wrapper">
    <form class="<?= $id ?> mgz-newsletter-form mgz-newsletter-form-<?= $type ?>"
        action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
        method="post"
        x-data="{...hyva.formValidation($el), ...validateForm()}"
        @submit.prevent="onSubmit"
    >
        <div class="mgz-newsletter-fields">
            <div class="mb-2 mgz-newsletter-field email required">
                <input class="h-11 form-input inline-flex w-1/2" name="email" type="email"
                       placeholder="<?= $block->escapeHtmlAttr(__('Your email')) ?>"
                       data-validate='{"required": true, "email": true}'
                />
            </div>
            <?php if ($firstname) { ?>
            <div class="mb-2 mgz-newsletter-field firstname required">
                <input class="h-11 form-input inline-flex w-1/2" name="firstname" type="text"
                       placeholder="<?= $block->escapeHtmlAttr(__('First Name')) ?>"
                       data-validate="{required:true}"
                       @change="onChange"
                />
            </div>
            <?php } ?>
            <?php if ($lastname) { ?>
            <div class="mgz-newsletter-field lastname required">
                <input class="h-11 form-input inline-flex w-1/2" name="lastname" type="text"
                       placeholder="<?= $block->escapeHtmlAttr(__('Last Name')) ?>"
                       data-validate="{required:true}"
                       @change="onChange"
                />
            </div>
            <?php } ?>
        </div>
        <div class="actions mt-2 mb-2">
            <button class="inline-flex shrink-0 ml-auto xl:mt-0 btn btn-primary action primary mgz-newsletter-btn"
                    title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>"
                    type="submit"
                    aria-label="Subscribe">
                <span><?= $block->escapeHtml(__('Subscribe')) ?></span>
            </button>
        </div>
    </form>
</div>
<script>
    function validateForm() {
        return {
            onSubmit(event) {
                event.preventDefault();
                this.validate()
                    .then(() => {
                        let form = $(event.target);
                        form.addClass('loading');
                        form.find('button').attr('disabled', 'disabled');
                        var data = form.serialize();
                        $.ajax({
                            url: form.attr('action'),
                            data: data,
                            type: 'post',
                            dataType: 'json',
                            success: function(res) {
                                form.find('button').removeAttr('disabled', 'disabled');
                                form.removeClass('loading');
                                form.parent().children('.mgz-newsletter-message').remove();
                                if (res.message) {
                                    var message = '<div class="mgz-newsletter-message ' + (res.status ? 'mgz-newsletter-message-success message success' : 'mgz-newsletter-message-error message error') + '">' + res.message + '</div>';
                                    form.parent().append(message);
                                    form.find('input').val('');
                                }
                                if (res.status) {
                                    $.ajax({
                                        url: "<?= $block->escapeUrl($block->getFormActionUrl()) ?>",
                                        data: data,
                                        type: 'post',
                                        dataType: 'json',
                                        success: function(res) {
                                            if (res.status) {

                                            }
                                        }
                                    });
                                }
                            }
                        });
                    })
                    .catch((invalid) => {
                        if (invalid.length > 0) {
                            invalid[0].focus();
                        }
                    });
            }
        }
    }
</script>