<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\ReCaptcha;
use Magento\Framework\Escaper;
use Magento\Newsletter\Block\Subscribe;

/** @var Subscribe $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var ReCaptcha $recaptcha */
/** @var HeroiconsOutline $heroicons */

$heroicons = $viewModels->require(HeroiconsOutline::class);

// Do not replace this with $viewModels->require(ReCaptcha::class); that might break the dependency
// on the Magento_ReCaptchaNewsletter module
$recaptcha = $block->getData('viewModelRecaptcha');
?>
<div>
    <form class="form subscribe flex flex-col gap-y-4 w-full m-0 text-whizzy-body"
        action="<?= $escaper->escapeUrl($block->getFormActionUrl()) ?>" method="post" x-data="initNewsletterForm()"
        @submit.prevent="submitForm()" id="newsletter-validate-detail"
        aria-label="<?= $escaper->escapeHtmlAttr(__('Recevoir la Newsletter Atomik')) ?>">
        <div class="font-semibold uppercase">
            <span><?= $escaper->escapeHtml(__('Recevoir la Newsletter Atomik')) ?></span>
        </div>
        <div class="w-full">
            <span class="sr-only"><?= $escaper->escapeHtml(__('Email Address')) ?></span>
            <input type="email" id="newsletter-subscribe" name="email"
                class="form-input w-full pb-2 pt-4 px-0 mb-3 rounded-none bg-transparent border-0 border-b border-black focus:border-b focus:border-black focus:ring-0 focus:offset-0 focus:outline-none"
                required placeholder="<?= $escaper->escapeHtmlAttr(__('Votre adresse email')) ?>">
            <?= $block->getBlockHtml('formkey') ?>
            <?= $recaptcha ? $recaptcha->getInputHtml(ReCaptcha::RECAPTCHA_FORM_ID_NEWSLETTER) : '' ?>
            <button
                class="btn flex justify-center transition-all duration-300 lg:text-base p-2 rounded focus:ring-0 cursor-pointer w-full">
                <?= $escaper->escapeHtml(__('Inscription')) ?>
            </button>
        </div>
        <template x-if="displayErrorMessage">
            <p class="flex items-center text-red mt-2">
                <?= $heroicons->exclamationCircleHtml('inline-block mr-3'); ?>
                <template x-for="errorMessage in errorMessages">
                    <span x-html="errorMessage"></span>
                </template>
            </p>
        </template>
    </form>
    <div class="w-full">
        <?= $recaptcha ? $recaptcha->getLegalNoticeHtml(ReCaptcha::RECAPTCHA_FORM_ID_NEWSLETTER) : '' ?>
    </div>
    <script>
        function initNewsletterForm() {
            return {
                errors: 0,
                hasCaptchaToken: 0,
                displayErrorMessage: false,
                errorMessages: [],
                setErrorMessages(messages) {
                    this.errorMessages = [messages]
                    this.displayErrorMessage = this.errorMessages.length
                },
                submitForm() {
                    // Do not rename $form, the variable is expected to be declared in the recaptcha output
                    const $form = document.querySelector('#newsletter-validate-detail');
                    <?= $recaptcha ? $recaptcha->getValidationJsHtml(ReCaptcha::RECAPTCHA_FORM_ID_NEWSLETTER) : '' ?>

                    if (this.errors === 0) {
                        $form.submit();
                    }
                }
            }
        }
    </script>
</div>