<?php
/**
 * @category    FishPig
 * @package     FishPig_WordPress
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
// phpcs:ignoreFile -- long lines (todo)
?>
<?php $posts = $block->getPosts() ?>
<?php if (count($posts) > 0): ?>
    <div class="block block-blog block-recent-posts mb-4 lg:mb-6">
        <?php if ($title = $block->getTitle()): ?>
            <div class="font-semibold uppercase text-heading mb-2 lg:mb-4">
                <span><?= $block->escapeHtml(__($title)) ?></span>
            </div>
        <?php endif; ?>
        <div class="block-content">
            <ul id="<?= $block->escapeHtmlAttr($block->getListId()) ?>" class="flex flex-col gap-4">
            <?php foreach ($posts as $post): ?>
                <li class="item bg-whizzy-beigehv rounded-lg">
                    <a href="<?= $block->escapeUrl($post->getUrl()) ?>" title="<?= $block->escapeHtml($post->getPostTitle()) ?>" class="flex flex-col xl:flex-row items-start xl:items-center gap-2 h-fit group p-4">
                        <span class="w-1/2 flex-auto h-20 relative">
                            <?php if ($image = $post->getImage()): ?>
                                <?php $imageUrl = $image->getResizer()
                                        ? $image->getResizer()->constrainOnly(true)
                                            ->keepFrame(false)
                                            ->keepAspectRatio(true)
                                            ->resize(600, null)
                                        : $image->getImageUrl(['large', 'medium']) ?>
                                <img src="<?= $block->escapeUrl($imageUrl) ?>" class="h-full w-full rounded-lg object-cover" alt="<?= $block->escapeHtml($post->getName()) ?>"/>
                            <?php else: ?>
                                <img src="<?= $this->getBaseUrl() . 'media/placeholder-blog.jpg' ?>" class="h-full w-full rounded-lg object-cover" alt="<?= __('Placeholder Image Atomik') ?>">
                            <?php endif; ?>
                        </span>
                        <span class="w-1/2 flex-auto group-hover:underline transition-all duration-300 font-medium">
                            <?= $block->escapeHtml($post->getPostTitle()) ?>
                        </span>
                    </a>
                </li>
            <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>