<?php
declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\HeroiconsSolid;

/** @var \Mirasvit\Review\Block\Widget\Review\Card $block */

/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

$review = $block->getReview();
?>

<?php if (!$review)
{
    return '';
} ?>
<div class="review-grid-item grid-item w-full md:w-1/2 lg:w-1/3 xl:w-1/4 p-2">
    <div
        class="review-grid-item-card card text-gray-900 p-4 border border-whizzy-separator rounded-lg shadow hover:shadow-lg transition-shadow duration-300">
        <?php if ($imageUrl = $block->getMainImageUrl()): ?>
            <img src="<?= $block->escapeUrl($imageUrl) ?>" alt="<?= $block->escapeHtmlAttr($review->getTitle()) ?>"
                class="review-image rounded mb-2" />
        <?php endif; ?>

        <div class="review-title font-semibold mb-2" itemprop="name">
            <?= $block->escapeHtml($review->getTitle()) ?>
        </div>

        <?php if (count($review->getRatingVotes())): ?>
            <div class="table mb-2">
                <?php foreach ($review->getRatingVotes() as $vote): ?>
                    <?php
                    $rating = $vote->getPercent();
                    $ratingSteps = 5;
                    $starsFilled = is_numeric($rating) ? floor($rating / 100 * $ratingSteps) : 0;
                    $starsEmpty = floor($ratingSteps - $starsFilled);
                    ?>
                    <div class="table-row mb-2" itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">
                        <div class="table-cell pr-6 align-middle text-left">
                            <?= $escaper->escapeHtml($vote->getRatingCode()) ?>
                        </div>
                        <span class="hidden" itemprop="ratingValue"><?= /** @noEscape */ $starsFilled; ?></span>
                        <div class="flex flex-row" role="img"
                            aria-label="<?= $escaper->escapeHtmlAttr(__('%1 rating. %2 out of %3 stars', $block->getReview()->getProduct()->getName(), $starsFilled, $ratingSteps)) ?>">
                            <?php $i = 0; ?>
                            <?php while ($i < $starsFilled): ?>
                                <?= $heroiconsSolid->starHtml('text-yellow-400', 24, 24, ["aria-hidden" => "true"]); ?>
                                <?php $i++; ?>
                            <?php endwhile; ?>
                            <?php $i = 0; ?>
                            <?php while ($i < $starsEmpty): ?>
                                <?= $heroiconsSolid->starHtml('text-gray-400', 24, 24, ["aria-hidden" => "true"]); ?>
                                <?php $i++; ?>
                            <?php endwhile; ?>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>

        <div class="review-product mb-2">
            <a class="block hover:underline"
                href="<?= $block->escapeUrl($review->getProduct()->getProductUrl()) ?>"><?= $block->escapeHtml($review->getProduct()->getName()) ?></a>
            <?php if ($block->displayProductOption()): ?>
                <small class="review-product-option">
                    <?= /* @noEscape */ $block->getProductOptions($review); ?>
                </small>
            <?php endif; ?>
        </div>

        <div class="review-content-container prose text-sm my-4">
            <div class="review-content" itemprop="description">
                <?= /* @noEscape */
                nl2br($block->escapeHtml($review->getDetail())) ?>
            </div>
        </div>

        <div class="flex flex-wrap items-center text-sm">
            <span><?= $escaper->escapeHtml(__('Review by')) ?></span>
            <span class="ml-1 font-semibold" itemprop="author" itemscope itemtype="https://schema.org/Person">
                <span itemprop="name"><?= $escaper->escapeHtml($review->getNickname()) ?></span>
            </span>
            <?php if ($block->displayVerifiedBuyer() && $review->getIsVerifiedBuyer()): ?>
                <span class="ml-1 text-green-500">Verified Buyer</span>
            <?php endif; ?>
            <time class="text-gray-700 inline-block ml-2" itemprop="datePublished"
                datetime="<?= $escaper->escapeHtmlAttr($block->getFormattedDate($review->getCreatedAt())); ?>">
                <span class="sr-only">
                    <?= $escaper->escapeHtml($block->getFormattedDate($review->getCreatedAt())) ?>
                </span>
                <span aria-hidden="true">
                    <?= $escaper->escapeHtml($block->getFormattedDate($review->getCreatedAt())) ?>
                </span>
            </time>
            <?php if ($block->getLocation($review)): ?>
                <div class="review-country text-secondary">
                    <strong>
                        <?= /* @noEscape */ $block->getLocation($review); ?>
                    </strong>
                    <?php if ($block->getCountryCode($review)): ?>
                        <div class="flag flag-<?= $block->escapeHtmlAttr($block->getCountryCode($review)) ?>"></div>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>