<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_item = $block->getItem(); ?>
<?php $_order = $block->getItem()->getOrder(); 

// ***Add product image on sales emails by Jopin***
$productId = $_item->getProductId();
$objectManagerHere = \Magento\Framework\App\ObjectManager::getInstance();
$product = $objectManagerHere->get('Magento\Catalog\Model\Product')->load($productId);
$productImage = $this->helper('Magento\Catalog\Helper\Image')->init($product, 'category_page_list', array('height' => '135' , 'width'=> '135'))->getUrl();
// ***Add product image on sales emails by Jopin***
?>
<tr>
    <td class="item-thumbnail">
        <img src="<?= $productImage ?>" alt="<?= __('Product Image');?>" style="vertical-align:top;" />
    </td>
    <td class="item-info<?php if ($block->getItemOptions()): ?> has-extra<?php endif; ?>">
        <p class="product-name"><?= $block->escapeHtml($_item->getName()) ?></p>
        <p class="sku"><?= /* @escapeNotVerified */  __('SKU') ?>: <?= $block->escapeHtml($block->getSku($_item)) ?></p>
        <?php if ($block->getItemOptions()): ?>
        <dl class="item-options">
            <?php foreach ($block->getItemOptions() as $option): ?>
            <dt><strong><em><?= /* @escapeNotVerified */  $option['label'] ?></em></strong></dt>
            <dd>
                <?= /* @escapeNotVerified */  nl2br($option['value']) ?>
            </dd>
            <?php endforeach; ?>
        </dl>
        <?php endif; ?>
               
        <!-- Product quantity -->
        <p class="qty"><?= /* @escapeNotVerified */  __('QTY') ?>: <?= $_item->getQty() * 1 ?></p>
        
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) :?>
        <?= $addInfoBlock->setItem($_item->getOrderItem())->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="item-price">
        <?= /* @escapeNotVerified */  $block->getItemPrice($_item->getOrderItem()) ?>
    </td>
</tr>
