<?php
/**
 * @category   MgtWizards
 * @package    MgtWizards_Popups
 * @author     bgaiteiro@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace MgtWizards\Popups\Controller\Adminhtml\Items;

class Index extends \MgtWizards\Popups\Controller\Adminhtml\Items
{
    /**
     * Items list.
     *
     * @return \Magento\Backend\Model\View\Result\Page
     */
    public function execute()
    {
        /** @var \Magento\Backend\Model\View\Result\Page $resultPage */
        $resultPage = $this->resultPageFactory->create();
        $resultPage->setActiveMenu('MgtWizards_Popups::test');
        $resultPage->getConfig()->getTitle()->prepend(__('Popup Items'));
        $resultPage->addBreadcrumb(__('Test'), __('Popup'));
        $resultPage->addBreadcrumb(__('Items'), __('Items'));
        return $resultPage;
    }
}