<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\ProductListItem;
use Hyva\Theme\ViewModel\ProductPage;
use Hyva\Theme\ViewModel\Store;
use Magento\Catalog\Block\Product\ReviewRendererInterface as ProductReviewRenderer;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var Store $viewModelStore */
$viewModelStore = $viewModels->require(Store::class);

/** @var ProductPage $productViewModel */
$productViewModel = $viewModels->require(ProductPage::class);

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
$themeIcons = $viewModels->require(\MgtWizards\Base\ViewModel\ThemeIcons::class);

/** @var ProductListItem $productListItemViewModel */
$productListItemViewModel = $viewModels->require(ProductListItem::class);

$viewMode = 'grid';
$imageDisplayArea = 'category_page_grid';
$showDescription = false;

$title = (string)$block->getTitle();
$headingTag = $block->getData('heading_tag') ?: 'h3';
$items = $block->getItems() ?? [];
if (is_object($items) && $items instanceof Iterator)
{
    $items = iterator_to_array($items);
}
if (!$itemCount = count($items))
{
    return '';
}

$sliderIndex = 1;
$sliderItemRenderer = $block->getLayout()->getBlock('product_list_item')
    ?: $block->getChildBlock('slider.item.template')
    ?: $block->getLayout()->createBlock(Template::class);

$hideRatingSummary = (bool)$block->getData('hide_rating_summary');
$hideDetails = (bool)$block->getData('hide_details');

$sliderItemRenderer->setData('hide_details', $hideDetails);
$sliderItemRenderer->setData('hide_rating_summary', $hideRatingSummary);

// The slider item renderer block is often a shared instance.
// If a specific item template is set for this slider, the previously set template must be reset later
// so the item template is only replaced for the one slider it is specified on.
$sharedItemRendererTemplate = null;
$isSharedItemRenderer = $sliderItemRenderer !== $block->getChildBlock('slider.item.template');
if ($isSharedItemRenderer && $block->getChildBlock('slider.item.template'))
{
    $sharedItemRendererTemplate = $sliderItemRenderer->getTemplate();
    $sliderSpecificItemTemplate = $block->getChildBlock('slider.item.template')->getTemplate();
    $sliderItemRenderer->setTemplate($sliderSpecificItemTemplate);
}

// Whizzy Helper
$whizzyUpdaterTemplate = $this->helper('ShopWhizzy\DigitalTheme\Helper\UpdaterTemplate');
$card_layout_template = $whizzyUpdaterTemplate->setCardLayout();
$sliderItemRenderer->setTemplate($card_layout_template);

?>
<script>
    'use strict';

    function initSliderComponent() {
        return {
            active: 0,
            itemCount: 0,
            getSlider() {
                return this.$root.querySelector('.js_slides');
            },
            pageSize: 4,
            pageFillers: 0,
            calcPageSize() {
                const slider = this.getSlider();
                if (slider) {
                    this.itemCount = slider.querySelectorAll('.js_slide').length;
                    this.pageSize = Math.round(slider.clientWidth / slider.querySelector('.js_slide').clientWidth);
                    this.pageFillers = (
                        this.pageSize * Math.ceil(this.itemCount / this.pageSize)
                    ) - this.itemCount;
                }
            },
            calcActive() {
                const slider = this.getSlider();
                if (slider) {
                    const sliderItems = this.itemCount + this.pageFillers;
                    const calculatedActiveSlide = slider.scrollLeft / (slider.scrollWidth / sliderItems);
                    this.active = Math.round(calculatedActiveSlide / this.pageSize) * this.pageSize;
                }
            },
            scrollPrevious() {
                this.scrollTo(this.active - this.pageSize);
            },
            scrollNext() {
                this.scrollTo(this.active + this.pageSize);
            },
            scrollTo(idx) {
                const slider = this.getSlider();
                if (slider) {
                    const slideWidth = slider.scrollWidth / (this.itemCount + this.pageFillers);
                    slider.scrollLeft = Math.floor(slideWidth) * idx;
                    this.active = idx;
                }
            },
            skipCarouselToNavigation(navSelector) {
                const element = document.getElementById(navSelector)
                if (element) {
                    element.scrollIntoView({ behavior: 'smooth', block: 'end' });
                    const button = element.querySelector('button:not([disabled])');
                    this.$nextTick(() => button && button.focus({ preventScroll: true }))
                }
            }
        }
    }
</script>
<section class="<?=
$escaper->escapeHtmlAttr($block->getData('maybe_purged_tailwind_section_classes'))
?: 'mt-12';
?>" x-data="initSliderComponent()" x-init="calcPageSize();"
    x-id="['slider-nav', 'slider-end', 'slider-desc', 'slider-id']"
    @resize.window.debounce="calcPageSize(); $nextTick( function() { calcActive() })" role="group"
    aria-roledescription="<?= $escaper->escapeHtmlAttr(__('Carousel')) ?>"
    aria-label="<?= $escaper->escapeHtmlAttr(__('Carousel %1', $title)) ?>" :aria-describedby="$id('slider-desc')">
    <?php if ($items): ?>
        <?php if ($title): ?>
            <div class="flex flex-col gap-3 font-bold mb-3 lg:mb-6">
                <div class="text-sm uppercase text-whizzy-graylighter">
                    <?= $escaper->escapeHtml(__('Take a look at')) ?>
                </div>
                <div class="text-3xl lg:text-4xl text-whizzy-body">
                    <?= $escaper->escapeHtml(__($title)); ?>
                </div>
            </div>
        <?php endif; ?>
        <span class="sr-only" :id="$id('slider-desc')" tabindex="-1">
            <?= $escaper->escapeHtml(__('Navigating through the elements of the carousel is possible using the tab key. You can skip the carousel or go straight to carousel navigation using the skip links.')) ?>
        </span>

        <a :href="`#${$id('slider-end')}`"
            class="action skip sr-only focus:not-sr-only focus:absolute focus:z-30 focus:bg-white">
            <?= $escaper->escapeHtml(__('Press to skip carousel')) ?>
        </a>
        <button x-show="itemCount > pageSize" type="button"
            class="action skip sr-only focus:not-sr-only focus:absolute focus:z-30 focus:bg-white"
            @click.prevent="skipCarouselToNavigation($id('slider-nav'))">
            <?= $escaper->escapeHtml(__('Press to go to carousel navigation')) ?>
        </button>
        <div class="relative mb-8 lg:mb-14">
            <div class="flex-none relative w-full overflow-x-hidden">
                <div class="relative flex flex-nowrap w-full overflow-auto js_slides snap" @scroll.debounce="calcActive">
                    <?php foreach ($items as $product): ?>
                        <div class="flex shrink-0 p-1.5 js_slide w-1/2 md:w-1/3 lg:w-1/4" role="group"
                            :aria-hidden="<?= (int)$sliderIndex ?> > active && <?= (int)$sliderIndex ?> <= (active + pageSize) ? 'false' : 'true'"
                            aria-label="<?= $escaper->escapeHtmlAttr(__('Item %1', $sliderIndex++)) ?>"
                            :aria-describedby="`slide-desc-<?= $escaper->escapeHtmlAttr($product->getId()) ?>-${$id('slider-id')}`">
                            <?= /** @noEscape */ $productListItemViewModel->getItemHtmlWithRenderer($sliderItemRenderer, $product, $block, $viewMode, ProductReviewRenderer::SHORT_VIEW, $imageDisplayArea, $showDescription) ?>
                        </div>
                    <?php endforeach; ?>
                    <div :class="{'js_dummy_slide w-1/2 md:w-1/3 lg:w-1/4 flex shrink-0 py-1' : pageFillers > 0}">
                    </div>
                    <div :class="{'js_dummy_slide w-1/2 md:w-1/3 lg:w-1/4 flex shrink-0 py-1' : pageFillers > 1}">
                    </div>
                    <div :class="{'js_dummy_slide w-1/2 md:w-1/3 lg:w-1/4 flex shrink-0 py-1' : pageFillers > 2}">
                    </div>
                </div>
            </div>
            <div class="mt-11">
                <template x-if="itemCount > pageSize">
                    <div class="flex items-center justify-center" :id="$id('slider-nav')">
                        <button type="button" aria-label="<?= $escaper->escapeHtmlAttr(__('Previous slide')) ?>"
                            :disabled="active === 0"
                            class="hidden lg:block bg-white w-11 h-11 ml-6 text-black rounded-lg outline-none focus:outline-none absolute top-1/2 left-0 -translate-y-1/2 z-20 opacity-100 cursor-pointer shadow-whizzy-header"
                            :class="{ 'opacity-25 pointer-events-none' : active === 0 }" @click="scrollPrevious">
                            <?= $themeIcons->renderHtml('arrow-left', 'text-black hover:text-black mx-auto', 24, 24, ['aria-hidden' => 'true']) ?>
                        </button>

                        <div class="flex flex-wrap w-full md:w-auto justify-center">
                            <?php for ($i = 0; $i < $itemCount; $i++): ?>
                                <button type="button" :class="{
                                    'hidden': (pageSize !== 1 && !!(<?= (int)$i ?> % pageSize))
                                }" :aria-current="active === <?= (int)$i ?>"
                                    :aria-label="hyva.str('<?= $escaper->escapeJs(__('Display slide %1')) ?>', (<?= (int)$i ?> / pageSize) + 1)"
                                    @click="scrollTo(<?= (int)$i ?>)">
                                    <span
                                        class="flex-shrink-0 block transition-all bg-whizzy-body shrink-0 w-2 h-2 m-1 bg-black bg-opacity-25 rounded-full shadow cursor-pointer"
                                        :class="{
                                    'bg-opacity-100 w-5': active === <?= (int)$i ?>,
                                    'bg-opacity-25 w-2': active !== <?= (int)$i ?>,
                                    'hidden': (pageSize !== 1 && !!(<?= (int)$i ?> % pageSize))
                                }" @click="scrollTo(<?= (int)$i ?>)"></span>
                                </button>
                            <?php endfor; ?>
                        </div>

                        <button type="button" aria-label="<?= $escaper->escapeHtmlAttr(__('Next slide')) ?>"
                            :disabled="active >= itemCount-pageSize"
                            class="hidden lg:block bg-white w-11 h-11 mr-6 text-black rounded-lg outline-none focus:outline-none absolute top-1/2 right-0 -translate-y-1/2 z-20 opacity-100 cursor-pointer shadow-whizzy-header"
                            :class="{ 'opacity-25 pointer-events-none' : active >= itemCount-pageSize }"
                            @click="scrollNext">
                            <?= $themeIcons->renderHtml('arrow-right', 'text-black hover:text-black mx-auto', 24, 24, ['aria-hidden' => 'true']) ?>
                        </button>
                    </div>
                </template>
            </div>
            <span :id="$id('slider-end')" tabindex="-1"></span>
        <?php endif; ?>
</section>
<?php

if ($sharedItemRendererTemplate)
{
    $sliderItemRenderer->setTemplate($sharedItemRendererTemplate);
}

?>