<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Magento\Framework\View\Element\Template;

/** @var Template $block */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\ProductPage;
use Magento\Catalog\Model\Product;

/** @var Template $block */
/** @var ViewModelRegistry $viewModels */
/** @var ProductPage $productViewModel */
/** @var Product $product */

$productViewModel = $viewModels->require(ProductPage::class);
$product = $productViewModel->getProduct();
$isArchive = $product->getIsArchive();
?>
<?php if (!$isArchive): ?>
    <div class="product-options-bottom flex flex-col flex-no-wrap gap-4">
        <?= $block->getChildHtml('', true) ?>
    </div>
<?php endif; ?>