<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Shop By Brand Compatibility with Hyva for Magento 2
 */

declare(strict_types=1);

/** @var HeroiconsOutline $heroicons */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

$heroicons = $viewModels->require(HeroiconsOutline::class);
$themeIcons = $viewModels->require(\MgtWizards\Base\ViewModel\ThemeIcons::class);

// phpcs:disable Generic.Files.LineLength.TooLong
?>
<section class="my-12 text-gray-700 body-font" x-data="{...amMoreFromBrand(), ...amMoreFromBrandSlider()}"
    @resize.window.debounce="calcPageSize(); $nextTick( function() { calcActive() })" x-init="moreFromBrandsInit()">
    <template x-if="products && products.length">
        <div class="container relative">
            <div class="flex flex-col gap-3 font-bold mb-6">
                <div class="text-3xl lg:text-4xl text-whizzy-body" x-html="title"></div>
            </div>
            <div class="flex-none relative w-full overflow-x-hidden">
                <div class="relative flex flex-nowrap w-full overflow-auto transition-all js_slides snap"
                    @scroll.debounce="calcActive">
                    <template x-for="product in products" :key="product.id">
                        <?= $block->getChildHtml('product_item') ?>
                    </template>
                    <div :class="{
                        'js_dummy_slide w-full lg:w-1/2 xl:w-1/3 flex shrink-0 py-1' : pageFillers > 0
                        }"></div>
                    <div :class="{
                        'js_dummy_slide w-full lg:w-1/2 xl:w-1/3 flex shrink-0 py-1' : pageFillers > 1
                        }"></div>
                    <div :class="{
                        'js_dummy_slide w-full lg:w-1/2 xl:w-1/3 flex shrink-0 py-1' : pageFillers > 2
                        }"></div>
                </div>
            </div>
            <div style="min-height: 65px">
                <template x-if="products.length && products.length > pageSize">
                    <div class="flex items-center justify-center flex-1 p-4" x-cloak>
                        <button aria-label="<?= $escaper->escapeHtmlAttr(__('Previous')) ?>"
                            class="bg-white shadow-whizzy-header w-11 -mt-16 -ml-2 lg:-ml-4 text-black rounded outline-none focus:outline-none absolute top-1/2 left-0 -translate-y-1/2 z-10 opacity-100 cursor-pointer"
                            :class="{ 'invisible' : active === 0 }" @click="getSlider().scrollLeft =
                                (getSlider().scrollWidth / (products.length + pageFillers)) * (active - pageSize);
                                active -= pageSize;">
                            <?= $themeIcons->renderHtml('arrow-left', 'w-11 h-11 p-1.5 lg:p-3', 20, 20, ["aria-hidden" => "true"]) ?>
                        </button>
                        <div class="flex flex-wrap w-full md:w-auto justify-center">
                            <template x-for="(product, index) in products" :key="index">
                                <button type="button" :class="{
                                        'hidden': (pageSize !== 1 && !!(index % pageSize))
                                    }" :aria-current="active === index"
                                    :aria-label="hyva.str('<?= $escaper->escapeJs(__('Display slide %1')) ?>', (index / pageSize) + 1)"
                                    @click="getSlider().scrollLeft =
                                    (getSlider().scrollWidth / (products.length + pageFillers)) * index;
                                    active = index;">
                                    <span
                                        class="flex-shrink-0 block transition-all bg-whizzy-body shrink-0 w-2 h-2 m-1 bg-black bg-opacity-25 rounded-full shadow cursor-pointer"
                                        :class="{
                                          'bg-opacity-100': active === index,
                                          'bg-opacity-25': active !== index,
                                          'hidden': (pageSize !== 1 && !!(index % pageSize))
                                      }" @click="getSlider().scrollLeft =
                                      (getSlider().scrollWidth / (products.length + pageFillers)) * index;
                                      active = index;"></span>
                                </button>
                            </template>
                        </div>
                        <button aria-label="<?= $escaper->escapeHtmlAttr(__('Next')) ?>"
                            class="bg-white shadow-whizzy-header w-11 -mt-16 -mr-2 lg:-mr-4 text-black rounded outline-none focus:outline-none absolute top-1/2 right-0 -translate-y-1/2 z-10 opacity-100 cursor-pointer"
                            :class="{ 'invisible' : active >= products.length-pageSize }" @click="getSlider().scrollLeft =
                                (getSlider().scrollWidth / (products.length + pageFillers)) * (active + pageSize);
                                active += pageSize">
                            <?= $themeIcons->renderHtml('arrow-right', 'w-11 h-11 p-1.5 lg:p-3', 20, 20, ["aria-hidden" => "true"]) ?>
                        </button>
                    </div>
                </template>
            </div>
        </div>
    </template>
</section>

<?= $block->getChildHtml('more_from_brand_js') ?>