<?php
/**
 * @category   MgtWizards
 * @package    MgtWizards_Popups
 * @author     bgaiteiro@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace MgtWizards\Popups\Model\ResourceModel;

class Popups extends \Magento\Framework\Model\ResourceModel\Db\AbstractDb
{
    /**
     * Define main table
     */
    protected function _construct()
    {
        $this->_init('mgtwizards_popups', 'popups_id');   //here "mgtwizards_popups" is table name and "popups_id" is the primary key of custom table
    }
}