<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Catalog\Model\Product;

/** @var Escaper $escaper */
/** @var Product $product */
$product = $block->getProduct();

$brandHelper = $this->helper(\MgtWizards\Base\Helper\Brand::class);
$brandName = $brandHelper->getBrandName($product);

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
$connection = $resource->getConnection();
$tableName = $resource->getTableName('amasty_amshopby_option_setting');
$sql = "SELECT * FROM " . $tableName . " WHERE value='" . $product->getBrand() . "';";
$result = $connection->fetchAll($sql);
//var_dump($result);exit;
$brand = [];
?>
<?php if (count($result) > 0): ?>
    <?php $hasimage = false; ?>
    <?php foreach ($result as $brand): ?>
        <div class="product-brands-wrapper flex flex-wrap justify-end w-fit">
            <span class="amshopby-option-link flex flex-col items-start">
                <span class="brand-title">
                    <a href="<?= $block->escapeHtml($block->getUrl() . 'marques/' . $brand['url_alias']) ?>"
                        class="amshopby-brand-title-link text-whizzy-graylighter text-sm font-semibold uppercase mb-3 hover:text-whizzy-body transition-all duration-200">
                        <?php if ($brand['slider_image'] != ''): ?>
                            <img src="<?= $block->getUrl() . 'media/amasty/shopby/option_images/slider/' . $brand['slider_image'] ?>"
                                alt="<?= __($brandName) ?>" />
                            <?php $hasimage = true; ?>
                        <?php endif ?>
                        <?php if (!$hasimage): ?>
                            <span>
                                <?= __($brandName) ?>
                            </span>
                        <?php endif ?>
                    </a>
                </span>
            </span>
        </div>
    <?php endforeach ?>
<?php endif ?>