<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);
$themeIcons = $viewModels->require(\MgtWizards\Base\ViewModel\ThemeIcons::class);

/** @var string[] $menu */
$item = $block->getData('item');
$level = $block->getData('level');
$menuId = str_replace('-', '_', $item['id']);
?>

<?php if (!empty($item['childData'])): ?>
    <li class="level-<?= $level ?>" data-id="<?= /* @noEscape */ $menuId ?>" x-data="initSubMenuDesktopItem"
        @click.outside="close">
        <button type="button"
            class="group w-[calc(100%-16px)] flex justify-between items-center gap-1 p-2 rounded-md hover:bg-whizzy-primary-lighter hover:text-whizzy-primary aria-expanded:text-whizzy-primary aria-expanded:bg-whizzy-primary-lighter data-[has-current]:font-semibold"
            x-ref="childmenuToggle" @click="toggle" aria-expanded="false" :aria-expanded="open"
            aria-controls="<?= $escaper->escapeHtml($item['id']) ?>-desktop-menu-panel">
            <span class="relative"><?= $escaper->escapeHtml($item['name']) ?></span>
            <?= $themeIcons->renderHtml('arrow-right', "flex self-center transition text-inherit hover:text-whizzy-primary group-aria-expanded:text-whizzy-primary", 16, 16, ['aria-hidden' => 'true']) ?>
        </button>
        <ul id="<?= $escaper->escapeHtml($item['id']) ?>-desktop-menu-panel"
            class="absolute inset-0 ml-3 pl-3 border-l-2 border-whizzy-artic bg-white flex flex-col gap-1 w-72 translate-x-72"
            x-show="open" x-ref="childmenuWrapper" @keydown.escape.stop="close">
            <li>
                <a href="<?= $escaper->escapeUrl($item['url']) ?>"
                    class="w-[calc(100%-16px)] flex p-2 rounded-md hover:bg-whizzy-primary-lighter hover:text-whizzy-primary font-semibold"
                    x-ref="childmenuViewAll"><?= $escaper->escapeHtml(__('See all %1', $item['name'])) ?></a>
            </li>
            <?php foreach ($item['childData'] as $subMenu): ?>
                <?= $block->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Magento_Theme::html/header/menu/desktop_2_item.phtml")->setItem($subMenu)->setLevel($level + 1)->toHtml(); ?>
            <?php endforeach; ?>
        </ul>
    </li>
<?php else: ?>
    <li class="level-<?= $level ?>">
        <a href="<?= $escaper->escapeUrl($item['url']) ?>"
            class="level-<?= $level ?> w-[calc(100%-16px)] flex p-2 rounded-md hover:bg-whizzy-primary-lighter hover:text-whizzy-primary aria-[current=page]:font-semibold"><?= $escaper->escapeHtml($item['name']) ?></a>
    </li>
<?php endif; ?>