<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Hyva\Theme\ViewModel\Navigation;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Magento\Cms\Block\BlockByIdentifier as CmsBlock;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var Navigation $viewModelNavigation */
$viewModelNavigation = $viewModels->require(Navigation::class, $block);

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);
$themeIcons = $viewModels->require(\MgtWizards\Base\ViewModel\ThemeIcons::class);

$maxLevel = $block->getmaxLevel() ?: 3;
$canOpenOnHover = $block->getOpenTopLevelMenuOnHover();

// Order is important here: 1. build the menu data, 2. then set the cache tags from the view model identities
$menu = $viewModelNavigation->getNavigation(2 + $maxLevel);
$block->setData('cache_tags', $viewModelNavigation->getIdentities());

// Whizzy Helper
$whizzyHelper = $this->helper('ShopWhizzy\DigitalTheme\Helper\Data');
$header_layout = $whizzyHelper->getConfigValue('header/header_layout');
$menu_shop_wrap_text = $whizzyHelper->getConfigValue('header/menu_shop_wrap_text') ?: __('Shop');

$sale_link = (($whizzyHelper->getConfigValue('header/sale_link')) ? $whizzyHelper->getConfigValue('header/sale_link') : 'sale');
$menu_background_color = (($menu_background_color_value = $whizzyHelper->getConfigValue('header/menu_background_color')) ? 'bg-[' . $menu_background_color_value . ']' : 'bg-white');
$menu_text_color = (($menu_text_color_value = $whizzyHelper->getConfigValue('header/menu_text_color')) ? 'text-[' . $menu_text_color_value . ']' : 'text-whizzy-body');

$hover_classes = "aria-expanded:text-black";
$menu_text_color_hover = (($menu_text_color_hover_value = $whizzyHelper->getConfigValue('header/menu_text_color_hover')) ? 'aria-expanded:text-[' . $menu_text_color_hover_value . '] hover:text-[' . $menu_text_color_hover_value . ']' : 'hover:text-whizzy-graylighter');
$show_sale_link = $whizzyHelper->getConfigValue('header/show_sale_link');

$menu_show_home = $whizzyHelper->getConfigValue('header/menu_show_home');
$menu_items_after = (($whizzyHelper->getConfigValue('header/menu_items_after')) ?: '');
$menu_items_after_decoded = (json_decode($menu_items_after, true) ?: []);
?>
<nav class="z-20 navigation hidden lg:flex items-center <?= $header_layout ?>"
    aria-label="<?= $escaper->escapeHtmlAttr(__('Main menu')) ?>" data-max-level="<?= $maxLevel ?>"
    x-data="initMenuDesktop" x-ref="nav-desktop" @load.window="setActiveMenu">
    <ul class="flex flex-wrap gap-x-6 items-center py-3">

        <?php if ($menu_show_home): ?>
            <li class="level-0">
                <a href="<?= $escaper->escapeUrl($block->getBaseUrl()) ?>"
                    class="level-0 group w-full flex justify-between items-center gap-1 p-2 font-medium transition top-menu-item aria-[current=page]:underline data-[has-current]:underline hover:underline underline-offset-4 <?= $menu_text_color . ' ' . $menu_text_color_hover ?>">
                    <?= $themeIcons->renderHtml('home', "flex self-center transition <?= $menu_text_color . ' ' . $menu_text_color_hover ?>", 28, 28, ['aria-hidden' => 'true']) ?>
                    <span class="relative sr-only"><?= $escaper->escapeHtml(__('Home')) ?></span>
                </a>
            </li>
        <?php endif; ?>

        <li @click.outside="close" @keydown.escape.stop="close" <?php if ($canOpenOnHover): ?>
                @mouseenter="canHover(() => { open = true })" @mouseleave="canHover(() => { open = false })" <?php endif ?>>
            <button type="button"
                class="group w-full flex justify-between items-center gap-1 py-3 px-6 font-medium transition top-menu-item has-sub aria-[current=page]:underline data-[has-current]:underline hover:underline underline-offset-4 bg-white rounded-lg hover:rounded-none	hover:rounded-t-lg aria-expanded:rounded-none aria-expanded:rounded-t-lg hover:bg-white aria-expanded:bg-white shadow-whizzy-header <?= $menu_text_color . ' ' . $menu_text_color_hover ?>"
                @click="toggle" aria-expanded="false" :aria-expanded="open" aria-controls="desktop-menu-panel">
                <span class="relative"><?= $escaper->escapeHtml($menu_shop_wrap_text) ?></span>
                <?= $themeIcons->renderHtml('arrow-down', "flex self-center transition group-aria-expanded:rotate-180 $menu_text_color group-aria-expanded:text-inherit", 16, 16, ['aria-hidden' => 'true']) ?>
            </button>
            <div id="desktop-menu-panel"
                class="z-40 absolute top-18 left-0 bg-white overflow-auto shadow-whizzy-submenu w-full p-8 overflow-hidden <?= !empty($cmsBlockHtml) ? "grid grid-cols-[minmax(0px,1fr)_theme('spacing.72')]" : '' ?>"
                x-show="open" x-transition x-cloak>
                <div class="container relative overflow-auto">
                    <ul class="flex flex-col gap-0.5 w-72 text-sm">
                        <?php foreach ($menu as $item): ?>
                            <?= $block->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Magento_Theme::html/header/menu/desktop_2_item.phtml")->setItem($item)->setLevel(0)->toHtml(); ?>
                        <?php endforeach; ?>
                    </ul>
                </div>
                <?php
                $menuId = 'desktop-menu-panel';
                $cmsBlockHtml = $this->getLayout()
                    ->createBlock(CmsBlock::class)
                    ->setIdentifier($menuId)
                    ->toHtml();
                if (!empty($cmsBlockHtml)):
                    ?>
                    <div class="max-w-[50%]">
                        <?= /** @noEscape */ $cmsBlockHtml ?>
                    </div>
                <?php endif; ?>
            </div>
        </li>

        <?php $i = 1; ?>
        <?php foreach ($menu_items_after_decoded as $item): ?>
            <?php $linkurl = ($item['url'] === '#') ? null : $escaper->escapeUrl($block->getBaseUrl() . $item['url']); ?>
            <?php if ($item['block']): ?>
                <?php $cmsDropdownBlockHtml = $this->getLayout()->createBlock(CmsBlock::class)->setIdentifier($item['block'])->toHtml(); ?>
                <li class="level-0" x-data="{
                        open: false,
                        canHover(func) {
                            const isHoverableDevice = window.matchMedia('(hover: hover) and (pointer: fine)').matches;
                            if (!isHoverableDevice) return;
                            func();
                        }
                    }" @click.outside="open = false" <?php if ($canOpenOnHover): ?>
                        @mouseenter="canHover(() => { open = true })" @mouseleave="canHover(() => { open = false })" <?php endif ?>
                    @keydown.escape="open = false" <?= ($linkurl) ? "onclick=\"location.href='$linkurl';\"" : '' ?>>
                    <?php $menuId = 'desktop-menu-after-' . $i ?>
                    <button type="button"
                        class="level-0 group w-full flex justify-between items-center gap-1 py-3 font-medium transition top-menu-item has-sub aria-[current=page]:underline data-[has-current]:underline hover:underline underline-offset-4 <?= $menu_text_color . ' ' . $menu_text_color_hover ?>"
                        @click="open = !open" aria-expanded="false" :aria-expanded="open"
                        aria-controls="<?= $escaper->escapeHtml($menuId) ?>">
                        <?php if ($item['icon']): ?>
                            <?= $themeIcons->renderHtml($item['icon'], "flex self-center transition $menu_text_color group-aria-expanded:text-inherit", 20, 20, ['aria-hidden' => 'true']) ?>
                        <?php endif; ?>
                        <span class="relative"><?= $escaper->escapeHtml($item['title']) ?></span>
                        <?= $themeIcons->renderHtml('arrow-down', "flex self-center transition group-aria-expanded:rotate-180 $menu_text_color group-aria-expanded:text-inherit", 16, 16, ['aria-hidden' => 'true']) ?>
                    </button>
                    <div id="<?= $escaper->escapeHtml($menuId) ?>"
                        class="z-40 absolute top-18 bg-white overflow-auto shadow-whizzy-submenu p-8 overflow-hidden <?= ($item['width'] === 'fullwidth') ? 'left-0 w-full' : 'rounded-lg min-w-80'; ?> <?= $header_layout === 'header_3' ? 'rounded-b-lg' : '' ?>"
                        x-show="open === true" x-transition x-cloak>
                        <?php if ($item['width'] === 'fullwidth'): ?>
                            <div class="container">
                            <?php endif; ?>
                            <div id="$menuId" class="text-whizzy-body">
                                <?= /** @noEscape */ $cmsDropdownBlockHtml ?>
                            </div>
                            <?php if ($item['width'] === 'fullwidth'): ?>
                            </div>
                        <?php endif; ?>
                    </div>
                </li>
            <?php else: ?>
                <li>
                    <?php if ($linkurl): ?>
                        <a href="<?= $escaper->escapeUrl($linkurl) ?>" title="<?= $escaper->escapeHtmlAttr($item['title']) ?>"
                            class="level-0 group w-full flex justify-between items-center gap-1 py-3 font-medium transition aria-[current=page]:underline data-[has-current]:underline hover:underline underline-offset-4 <?= $menu_text_color . ' ' . $menu_text_color_hover ?>">
                            <?php if ($item['icon']): ?>
                                <?= $themeIcons->renderHtml($item['icon'], "flex self-center transition $menu_text_color group-aria-expanded:text-inherit", 20, 20, ['aria-hidden' => 'true']) ?>
                            <?php endif; ?>
                            <span class="relative"><?= $escaper->escapeHtml($item['title']) ?></span>
                        </a>
                    <?php else: ?>
                        <span
                            class="level-0 group w-full flex justify-between items-center gap-1 py-3 font-medium transition aria-[current=page]:underline data-[has-current]:underline hover:underline underline-offset-4 cursor-pointer <?= $menu_text_color . ' ' . $menu_text_color_hover ?>">
                            <?php if ($item['icon']): ?>
                                <?= $themeIcons->renderHtml($item['icon'], "flex self-center transition $menu_text_color group-aria-expanded:text-inherit", 20, 20, ['aria-hidden' => 'true']) ?>
                            <?php endif; ?>
                            <span class="relative"><?= $escaper->escapeHtml($item['title']) ?></span>
                        </span>
                    <?php endif; ?>
                </li>
            <?php endif; ?>
            <?php $i++; ?>
        <?php endforeach; ?>
    </ul>
</nav>
<script>
    function initMenuDesktop() {
        return {
            open: false,
            maxLevel: parseInt(this.$root.dataset.maxLevel),
            toggle() {
                this.open = !this.open;
            },
            close() {
                this.open = false;
            },
            canHover(func) {
                const isHoverableDevice = window.matchMedia('(hover: hover) and (pointer: fine)').matches;
                if (!isHoverableDevice) return;
                func();
            },
            setActiveMenu() {
                const maxLevel = this.$root.dataset.maxLevel;
                Array.from(this.$root.querySelectorAll('a'))
                    .filter(link => link.href === window.location.href.split('?')[0])
                    .forEach(item => {
                        item.setAttribute('aria-current', 'page');

                        for (let level = 0; level < maxLevel; level++) {
                            const closestMenu = item.closest(`.level-${level}`);

                            if (closestMenu) {
                                const button = closestMenu.querySelector('button');
                                if (button) {
                                    button.setAttribute('data-has-current', '');
                                }
                            }
                        }
                    }
                    );
            }
        }
    }

    function initSubMenuDesktopItem() {
        return {
            open: false,
            toggle() {
                this.open = !this.open;
                this.$nextTick(() => {
                    this.$refs.childmenuViewAll.focus();
                    this.$refs.childmenuWrapper.scrollIntoView({
                        behavior: 'smooth',
                        block: 'nearest',
                        inline: 'end'
                    });
                });
            },
            close() {
                this.open = false;
                this.$refs.childmenuToggle.focus();
            },
        }
    }

    window.addEventListener('alpine:init', () => {
        Alpine.data('initMenuDesktop', initMenuDesktop);
        Alpine.data('initSubMenuDesktopItem', initSubMenuDesktopItem);
    }, { once: true })
</script>
<?php $hyvaCsp->registerInlineScript() ?>