<?php
/**
 * @category    FishPig
 * @package     FishPig_WordPress
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
// phpcs:ignoreFile -- long lines (todo)

/** @var ViewModelRegistry $viewModels */
$themeIcons = $viewModels->require(\MgtWizards\Base\ViewModel\ThemeIcons::class);
?>
<?php if ($post = $block->getPost()): ?>
    <?php if (!$post->isViewableForVisitor()): ?>
        <?= $block->getPasswordProtectHtml() ?>
    <?php else: ?>
        <div class="post-view">
            <div class="post-entry relative group">
                <div class="mb-4 lg:mb-6 relative">
                    <div class="post-entry h-64 lg:h-[250px] overflow-hidden rounded-lg">
                        <?php if ($image = $post->getImage()): ?>
                            <?php $imageUrl = $image->getResizer()
                                    ? $image->getResizer()->constrainOnly(true)
                                        ->keepFrame(false)
                                        ->keepAspectRatio(true)
                                        ->resize(600, null)
                                    : $image->getImageUrl(['large', 'medium']) ?>
                            <img src="<?= $block->escapeUrl($imageUrl) ?>" class="h-full w-full object-cover" alt="<?= $block->escapeHtml($post->getName()) ?>"/>
                        <?php else: ?>
                            <img src="<?= $this->getBaseUrl() . 'media/placeholder-blog.jpg' ?>" class="h-full w-full object-cover" alt="<?= __('Placeholder Image Atomik') ?>">
                        <?php endif; ?>
                        <div class="post-excerpt"><?= /* @noEscape */ $post->getExcerpt(60) ?></div>
                    </div>
                    <div class="post-meta absolute bottom-2 left-4 lg:left-8 flex flex-wrap lg:flex-row gap-3 lg:gap-4 items-center">
                        <div class="post-date post-meta-item">
                            <div class="inline-flex items-center gap-2 bg-white py-2 px-3 lg:py-3 lg:px-4 rounded-lg transition-all duration-300 text-xs lg:text-base">
                                <span><?= $themeIcons->renderHtml('calendar-03', '', 22, 22) ?></span>
                                <span><?= $block->escapeHtml($post->getPostDate()) ?></span>
                            </div>
                        </div>
                        <?php if ($categoryString = $post->getTermCollectionAsString('category')): ?>
                            <div class="post-categories post-meta-item">
                                <div class="inline-flex items-center gap-2 bg-white/60 py-2 px-3 lg:py-3 lg:px-4 rounded-lg hover:bg-white transition-all duration-300 cursor-pointer text-xs lg:text-base">
                                    <span><?= $themeIcons->renderHtml('tag', '', 22, 22) ?></span> 
                                    <span><?= $block->escapeHtml($categoryString, ['a']) ?></span>
                                </div>
                            </div>
                        <?php endif; ?>
                        <?php if ($tagString = $post->getTermCollectionAsString('post_tag')): ?>
                            <div class="post-tags post-meta-item">
                                <div class="inline-flex items-center gap-2 bg-white/60 py-2 px-3 lg:py-3 lg:px-4 rounded-lg hover:bg-white transition-all duration-300 cursor-pointer text-xs lg:text-base capitalize !decoration-0">
                                    <span><?= $themeIcons->renderHtml('tag', '', 22, 22) ?></span>
                                    <span><?= $block->escapeHtml($tagString, ['a']) ?></span>
                                </div>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
                <div>
                    <?php if (($content = trim($post->getContent())) !== ''): ?>
                        <div class="post-content"><?= /* @noEscape */ $content ?></div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    <?php endif; ?>
<?php endif; ?>
