<?php

use Bol\CheckoutViaBol\Block\Checkout\Link;
use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/**
 * @var Link $block
 * @var Escaper $escaper
 * @var SecureHtmlRenderer $secureRenderer
 */

?>
<?php if ($block->isMethodAllowed() && $block->displayCvbCheckoutButton()): ?>

    <div class="cvb-link">
        <cvb-checkout-button
            type="cart"
            font-url="<?= $escaper->escapeHtmlAttr($block->getViewFileUrl("Bol_CheckoutViaBol::fonts/Graphik-Regular.ttf")) ?>"
            label-url="<?= $escaper->escapeHtmlAttr($block->getViewFileUrl("Bol_CheckoutViaBol::images/button_checkout_via_bol.svg")) ?>"
            info="<?= $block->getButtonDescription() ?>"
            label="<?= $block->getButtonLabel() ?>"
            @click="CVBCheckoutButton.wrapOnClick($event.target, async function (event) {
                const response = await fetch('/cvb/session/create');
                const json = await response.json();
                window.location.href = json['redirectUrl'];
            });"
        />
    </div>

<?php endif ?>
