<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package FAQ and Product Questions for Magento 2
 */
/**
 * @var \Amasty\Faq\Block\Catalog\Product\Tab $block
 */
?>
<section class="py-6 lg:py-12">
    <div class="container">
        <div class="flex flex-col gap-3 font-bold">
            <div class="text-sm uppercase text-whizzy-graylighter"><?= $block->escapeHtml(__('Know more about it')); ?>
            </div>
            <div class="text-3xl lg:text-4xl text-whizzy-body"><?= $block->escapeHtml(__('Customer Questions')); ?>
            </div>
        </div>
        <div class="pt-4 lg:pt-8">
            <?= /** @noEscape */ $block->getChildHtml('amasty_faq_questions'); ?>
            <?php
            if ($block->showAskQuestionForm())
            {
                echo $block->getChildHtml('amasty_faq_ask_question_form');
            }
            ?>
        </div>
    </div>
</section>