<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
?>
<script>
    function initPriceBox() {
        return {
            updatePrice(priceData) {
                const regularAmount = priceData.oldPrice
                    ? priceData.oldPrice.amount
                    : priceData.baseOldPrice
                        ? priceData.baseOldPrice.amount
                        : priceData.finalPrice.amount;

                if (priceData.finalPrice.amount < regularAmount) {
                    regularPriceLabel && regularPriceLabel.classList.add('hidden');
                } else {
                    regularPriceLabel && regularPriceLabel.classList.remove('hidden');
                }
                regularPriceElement && (regularPriceElement.innerText = hyva.formatPrice(priceData.finalPrice.amount));
                basePriceElement && (basePriceElement.innerText = hyva.formatPrice(priceData.basePrice.amount));
            }
        }
    }
</script>