<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\ProductAttributes;
use Hyva\Theme\ViewModel\ProductCompare;
use Hyva\Theme\ViewModel\ProductPage;
use Hyva\Theme\ViewModel\Wishlist;
use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var ProductPage $productViewModel */
$productViewModel = $viewModels->require(ProductPage::class);
/** @var ProductAttributes $attributesViewModel */
$attributesViewModel = $viewModels->require(ProductAttributes::class);
/** @var Product $product */
$product = $productViewModel->getProduct();
$productType = $product->getTypeId();
$productName = $product->getName();
$productId = $product->getId();
$productShortDescription = $product->getShortDescription();
$hideRatingSummary = $block->getData('hide_rating_summary') ?: false;

// Whizzy Helper
$whizzyHelper = $this->helper('ShopWhizzy\DigitalTheme\Helper\Data');
$product_price_green = ($whizzyHelper->getConfigValue('products_listing/product_price_green') ? 'price-green' : '');
?>
<div class="flex flex-col w-full">

    <div class="flex flex-col gap-2 mb-4">
        <div class="flex justify-between items-center">
            <?php if (!$hideRatingSummary): ?>
                <?= $block->getChildHtml('product.info.review') ?>
            <?php endif; ?>
            <?php if ($additionalActions = $block->getChildHtml('product.info.additional.actions')): ?>
                <?= /** @noEscape */ $additionalActions; ?>
            <?php endif; ?>
        </div>
        <h1 class="font-bold text-3xl lg:text-4xl" itemprop="name">
            <?= $escaper->escapeHtmlAttr($productName) ?>
        </h1>
    </div>

    <?= $block->getChildHtml("product.info.below.title.wrapper") ?>

    <div class="flex flex-row justify-between items-end text-base lg:text-xl lg:mt-2 mb-4">
        <div role="group" class="price-wrapper <?= $product_price_green ?>"
            aria-label="<?= $escaper->escapeHtmlAttr('Price') ?>">
            <?php if ($productType === 'grouped'): ?>
                <?= $this->getProductPrice($product); ?>
            <?php else: ?>
                <?= $block->getChildHtml("product.info.price") ?>
            <?php endif; ?>
        </div>
        <div class="flex flex-row gap-4">
            <div class="flex flex-col gap-2 text-sm font-regular">
                <?= $block->getChildHtml("product.info.stockstatus") ?>
                <?= $block->getChildHtml("alert.urls") ?>
                <div class="w-full">
                    <dl id="product-details">
                        <?php foreach ($block->getAttributes() as $attributeConfig):
                            $attribute = $attributesViewModel->getAttributeFromLayoutConfig($attributeConfig); ?>
                            <?php if ($value = $attribute['value'] ?? null): ?>
                                <?php if ($attribute['label'] === 'Color'): ?>
                                <?php else: ?>
                                    <div class="flex attribute-<?=/* @noEscape */ $attribute['code'] ?: "" ?>">
                                        <div class="w-full inline-flex items-center justify-end">
                                            <dt class="text-left product-detail-label">
                                                <?= $escaper->escapeHtml($attribute['label']) ?>
                                            </dt>
                                            <dd class="hyphens-none break-normal ml-2 text-left product-detail-value">
                                                <?= $value ?>
                                            </dd>
                                        </div>
                                    </div>
                                <?php endif; ?>
                            <?php endif ?>
                        <?php endforeach; ?>
                    </dl>
                </div>
            </div>
            <?= $block->getChildHtml('product.info.addtowishlist'); ?>
        </div>
    </div>

    <div x-data="" id="gallery-mobile"></div>

    <?php /*$optionProcessor = $viewModels->require(\Amasty\ShopbyBrand\ViewModel\OptionProcessor::class); ?>
<?= $this->getLayout()->createBlock("Amasty\ShopbyBase\Block\Product\AttributeIcon")
->setData(['attribute_codes' => ['merk'], 'option_processor' => $optionProcessor, 'product' => $product, 'page_type' => 'listing'])
->setTemplate("Amasty_ShopByBrandHyvaCompatibility::attribute/icon.phtml")
->toHtml(); */ ?>

    <?php if ($productShortDescription): ?>
        <div class="product-short-description">
            <?= __($productShortDescription) ?>
        </div>
    <?php endif; ?>

    <?= $block->getChildHtml('product.info.form') ?>

    <?php if ($productType === 'grouped'): ?>
    <?php elseif ($productType === 'simple'): ?>
        <?php if ($tierPriceBlock = $block->getChildHtml("product.price.tier")): ?>
            <div class="tier-price-container">
                <?= /** @noEscape */ $tierPriceBlock ?>
            </div>
        <?php endif; ?>
    <?php endif; ?>

    <div class="flex flex-col gap-y-3">
        <?php if ($product->isSaleable()): ?>
            <div class="flex flex-row gap-3">
                <?= $block->getChildHtml("product.info.quantity") ?>
                <?= $block->getChildHtml("product.info.addtocart") ?>
            </div>
        <?php endif; ?>
    </div>

    <?= $block->getChildHtml("product.info.additional") ?>
</div>

<script>
    /* https://github.com/nabeghe/alpine-portal */
    !function (e) { "function" == typeof define && define.amd ? define(e) : e() }((function () { "use strict"; function e(e) { this.target = null, this.screen = 0; const t = e.parentElement; let n = null; this.update = () => { n && (n.removeEventListener("change", this.onResize), n = null), 0 !== this.screen && (n = window.matchMedia(`(${this.screen > 0 ? "min" : "max"}-width: ${Math.abs(this.screen)}px)`), n.addEventListener("change", this.onResize)) }, this.onResize = n => { n.matches ? document.querySelector(this.target).appendChild(e) : t.appendChild(e) }, window.Alpine.nextTick((() => this.onResize(n))) } const t = []; document.addEventListener("alpine:init", (() => { window.Alpine.directive("portal", ((n, { value: i, expression: s }, { evaluate: a }) => { i || void 0 !== n._x_portal || (n._x_portal = new e(n), t.push(n._x_portal)), !1 !== s && (i ? s = a(s) : i = "target", n._x_portal[i] = s, i && "screen" === i && n._x_portal.update()) })) })) }));
</script>