<?php

use Magento\Catalog\Pricing\Price\TierPrice;
use Magento\Catalog\Pricing\Render\PriceBox;
use Magento\Framework\Escaper;

/** @var PriceBox $block */
/** @var Escaper $escaper */

/** @var TierPrice $tierPriceModel */
$tierPriceModel = $block->getPrice();
$tierPrices = $tierPriceModel->getTierPriceList();
$product = $block->getSaleableItem();
?>
<?php if (count($tierPrices)): ?>
    <ul class="<?= $escaper->escapeHtmlAttr((
    $block->hasListClass() ? $block->getListClass() : 'prices-tier items'
    )) ?> grid grid-cols-3 gap-3 w-full">
        <?php foreach ($tierPrices as $index => $price): ?>
            <li class="item border-l-2 border-green-400 pl-2 lg:pl-3 text-xs lg:text-sm text-whizzy-graylighter">
                <?php
                $productId = $product->getId();
                $isSaleable = $product->isSaleable();
                $priceAmountBlock = $block->renderAmount(
                    $price['price'],
                    [
                        'price_id' => $index,
                        'id_suffix' => '-' . $index,
                        'include_container' => true,
                        'zone' => \Magento\Framework\Pricing\Render::ZONE_ITEM_OPTION
                    ]
                );
                ?>
                <?= /* @noEscape */ ($block->getShowDetailedPrice() !== false) ? __(
                'Buy <strong class="text-whizzy-body">%1</strong> for <strong class="text-whizzy-body">%2</strong> each and ' .
                '<strong class="benefit text-whizzy-body">save<span class="percent text-whizzy-body tier-%3">&nbsp;%4</span>%</strong>',
                $price['price_qty'],
                $priceAmountBlock,
                $index,
                $block->formatPercent($tierPriceModel->getSavePercent($price['price']))) : __('Buy %1 for %2 each', $price['price_qty'],
                $priceAmountBlock
                );
                ?>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>