<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Magento\Framework\Escaper;
use Magento\Review\Block\Product\ReviewRenderer;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsSolid;

/** @var ReviewRenderer $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);
$themeIcons = $viewModels->require(\MgtWizards\Base\ViewModel\ThemeIcons::class);

$rating = $block->getRatingSummary();
$ratingSteps = 5;
$starsFilled = is_numeric($rating) ? floor($rating / 100 * $ratingSteps) : 0;
$starFragment = $rating / 100 * $ratingSteps - $starsFilled;
$starsEmpty = floor($ratingSteps - $starsFilled - $starFragment);
$productName = $block->getProduct()->getName();
$productId = $block->getProduct()->getId();
$uniqueId = $productId . uniqid();
$reviewCount = $block->getReviewsCount();
?>

<?php if ($block->isReviewEnabled() && $reviewCount): ?>
    <div x-data="initRating<?= /* @noEscape */ $uniqueId ?>()" x-defer="intersect" @keyup.enter="scrollToRatings()"
        @click="scrollToRatings()" class="rating-summary flex items-center gap-1 text-sm"
        :class="{'cursor-pointer' : reviewsSection}" <?php if (!$rating): ?>
            title="<?= $escaper->escapeHtmlAttr(__('Be the first to review this product')) ?>" <?php endif; ?>
        :tabindex="reviewsSection ? '0' : '-1'" :aria-label="reviewsSection
            ? '<?= $escaper->escapeJs(__('%1 rating. %2 out of %3 stars. Click to go to reviews.', $productName, $starsFilled + $starFragment, $ratingSteps)) ?>'
            : '<?= $escaper->escapeJs(__('%1 rating. %2 out of %3 stars', $productName, $starsFilled + $starFragment, $ratingSteps)) ?>'
        " :role="reviewsSection ? 'button' : 'img'">
        <?= $themeIcons->renderHtml('star-solid-rounded', 'text-yellow-500 mb-1', 14, 14, ['aria-hidden' => 'true']) ?>
        <span class="font-medium">
            <?= $rating / 20 ?>
        </span>
        <span class="text-gray-500">
            (<span><?= $reviewCount ?></span>)
        </span>
    </div>

    <script>
        'use strict';

        function initRating<?= /* @noEscape */ $uniqueId ?>() {
        return {
            reviewsSection: document.getElementById('customer-review-list')
                || document.getElementById('customer-reviews')
                || document.getElementById('review-form'),
            scrollToRatings() {
                let scrollTimeout = null

                if (!this.reviewsSection) {
                    return
                }

                addEventListener('scroll', () => {
                    clearTimeout(scrollTimeout);

                    scrollTimeout = setTimeout(() => {
                        if (this.reviewsSection) {
                            this.reviewsSection.focus()
                        }
                    }, 50);
                }, { once: true });

                this.reviewsSection.scrollIntoView({ behavior: 'smooth' })
            }
        }
                                        }
    </script>
<?php endif; ?>