<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Shop By Brand Compatibility with Hyva for Magento 2
 */
/** @var HeroiconsOutline $heroicons */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Hyva\Theme\ViewModel\ProductCompare;
use Hyva\Theme\ViewModel\Wishlist;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

$heroicons = $viewModels->require(HeroiconsOutline::class);
/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);
/** @var Wishlist $wishlistViewModel */
$wishlistViewModel = $viewModels->require(Wishlist::class);
/** @var ProductCompare $compareViewModel */
$compareViewModel = $viewModels->require(ProductCompare::class);
// phpcs:disable Generic.Files.LineLength.TooLong

$themeIcons = $viewModels->require(\MgtWizards\Base\ViewModel\ThemeIcons::class);

// Whizzy Helper
$whizzyHelper = $this->helper('ShopWhizzy\DigitalTheme\Helper\Data');
$product_image_background = (($whizzyHelper->getConfigValue('general/product_image_background')) ? 'bg-whizzy-artic' : '');
$product_image_background_custom = (($product_image_background_custom_value = $whizzyHelper->getConfigValue('general/product_image_background_custom')) ? "style=\"background-color:{$product_image_background_custom_value}\";" : '');
$product_image_background_mixblend = ($whizzyHelper->getConfigValue('general/product_image_background_mixblend') ? 'mix-blend-multiply' : '');
$product_image_padding = ($whizzyHelper->getConfigValue('general/product_image_padding') ? 'p-3 lg:p-6' : '');
$product_image_shadow = $whizzyHelper->getConfigValue('general/product_image_shadow');
$product_image_background_mixblend = ($whizzyHelper->getConfigValue('general/product_image_background_mixblend') ? 'mix-blend-multiply' : '');
$product_image_square = ($whizzyHelper->getConfigValue('general/product_image_square') ? 'aspect-square object-center object-contain' : 'object-cover');

?>
<div class="flex-none w-full py-1 js_slide md:w-1/2 lg:w-1/3 xl:w-1/4" x-init="$nextTick(() => slideRendered())">
    <div class="item product product-item group product_addtocart_form flex flex-col w-full px-2">
        <div class="relative mb-3">
            <a :href="getProductUrl(product)" :title="product.name" tabindex="-1"
                class="product photo product-item-photo block mx-auto rounded-lg <?= $product_image_background ?> <?= $product_image_padding ?>">
                <img class="mx-auto rounded-lg <?= $product_image_background_mixblend ?> <?= $product_image_square ?>"
                    :src="product.small_image.url" :alt="product.small_image.label" loading="lazy" width="500"
                    height="500" />
                <?php if ($product_image_shadow): ?>
                    <span
                        class="shadow-elem absolute z-10 bg-gradient-to-t from-black to-transparent h-full w-full rounded-lg bottom-0 left-0 opacity-20"></span>
                <?php endif; ?>
            </a>
            <div class="wishlist-elem absolute z-10 bottom-0 lg:bottom-auto lg:top-6 left-0 lg:left-6">
                <?php if ($wishlistViewModel->isEnabled()): ?>
                    <button @click.prevent="addToWishlist(product.id)"
                        :aria-label="hyva.str('<?= $escaper->escapeJs(__('Add to Wishlist %1')) ?>', product.name)"
                        type="button"
                        class="btn btn-primary flex justify-center bg-transparent lg:bg-whizzy-primary hover:bg-whizzy-primary-darker p-1 lg:p-2 text-sm w-10 lg:w-12 h-10 lg:h-12 border-0 opacity-100 lg:opacity-0 group-hover:opacity-100 transition-all duration-300">
                        <?= $themeIcons->renderHtml('heart', "text-whizzy-body lg:text-white w-5 lg:w-6", 24, 24, ['aria-hidden' => 'true']) ?>
                    </button>
                <?php endif; ?>
            </div>

            <div class="cart-elem absolute z-20 bottom-0 lg:bottom-6 right-0 lg:right-auto lg:left-6">
                <a class="btn btn-primary add-to-cart flex justify-center bg-transparent lg:bg-whizzy-primary hover:bg-whizzy-primary-darker p-2 text-sm w-12 h-12 border-0 opacity-100 lg:opacity-0 group-hover:opacity-100 transition-all duration-300 relative"
                    :href="getProductUrl(product)" :title="product.name">
                    <?= $themeIcons->renderHtml('cart', 'text-whizzy-body lg:text-white w-5 lg:w-6', 24, 24, ['aria-hidden' => 'true']) ?>
                    <span class="ml-2 hidden"><?= $escaper->escapeHtml(__('View Product')) ?></span>
                </a>
            </div>
        </div>
        <div class="product-info flex flex-col grow text-black">
            <div
                class="name-elem mt-2 mb-1 items-center font-semibold text-base lg:text-xl tracking-tight leading-5 lg:leading-7">
                <a class="product-item-link" :href="getProductUrl(product)" :title="product.name">
                    <span x-html="product.name"></span>
                </a>
            </div>

            <template x-if="product.price_range.minimum_price?.final_price?.value">
                <div class="flex flex-col lg:flex-row gap-2 lg:gap-0 justify-between items-start lg:mt-2"
                    x-text="hyva.formatPrice(product.price_range.minimum_price.final_price.value)"></div>
            </template>
        </div>
    </div>
</div>