<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Catalog\Block\Product\ListProduct;

/** @var ListProduct $block */
/** @var ViewModelRegistry $viewModels */

$sliderViewModel = $viewModels->require(\Hyva\Theme\ViewModel\Slider::class);
$whizzyHelper = $this->helper('ShopWhizzy\DigitalTheme\Helper\Data');
$category_id = $block->getData('category_id');
$product_count = $block->getData('count');
$items = $whizzyHelper->getCategoryItems($category_id, $product_count);
?>
<?php if ($items): ?>
    <div class="mx-auto relative w-full h-full">
        <?php
        $itemsTemplate = 'Magento_Catalog::product/list/item_2.phtml';
        $sliderTemplate = 'ShopWhizzy_DigitalTheme::sliders/carousel_slider_2.phtml';
        ?>
        <?= $sliderViewModel->getSliderForItems($itemsTemplate, $items, $sliderTemplate)->toHtml() ?>
    </div>
<?php endif ?>