<?php
/**
 * Copyright © MageWorx. All rights reserved.
 * See https://www.mageworx.com/terms-and-conditions for license details.
 */

/** @var \Magento\Framework\Escaper $escaper */
/** @var \MageWorx\Downloads\Block\Catalog\Product\Attachments $sectionBlock */
?>

<div class="container mx-auto flex pt-6 pb-3 mb-6 md:flex-row border-b-2 border-gray-300">
    <h2 class="text-gray-900 text-2xl title-font font-base text-center md:text-left w-full">
        <?= $escaper->escapeHtml($sectionBlock->getSectionTitle()); ?>
    </h2>
</div>
