<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\LocaleFormatter;
use Magento\Framework\Escaper;
use Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer;

/** @var DefaultRenderer $block */
/** @var Escaper $escaper */
/** @var LocaleFormatter $localeFormatter */

$item = $block->getItem();
$cols = $block->getData('is_context_shipment') ? 3 : ($block->getData('is_context_creditmemo') ? 7 : 5);
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$imageHelper = $objectManager->get('\Magento\Catalog\Helper\Image');
?>
<div class="lg:grid grid-cols-<?= $escaper->escapeHtmlAttr($cols) ?> gap-4 lg:gap-6">
    <div class="col-span-2 mb-4 lg:mb-0">
        <?php if ($block->getData('is_context_creditmemo')): ?>
            <?php $product = $objectManager->get('Magento\Catalog\Model\Product')->loadByAttribute('sku', $item->getSku()); ?>
            <img class="rounded-lg shrink-0"
                src="<?= $image_url = $imageHelper->init($product, 'product_thumbnail_image')->setImageFile($product->getFile())->resize(100, 100)->getUrl(); ?>"
                alt="<?= $escaper->escapeHtml($item->getName()) ?>" width="100" height="100" />
            <span class="text-base lg:text-lg text-heading font-medium">
                <?= $escaper->escapeHtml($item->getName()) ?>
            </span>
        <?php else: ?>
            <div class="flex flex-col lg:flex-row items-center gap-3">
                <?php $product = $objectManager->get('Magento\Catalog\Model\Product')->loadByAttribute('sku', $item->getSku()); ?>
                <img class="rounded-lg shrink-0"
                    src="<?= $image_url = $imageHelper->init($product, 'product_thumbnail_image')->setImageFile($product->getFile())->resize(100, 100)->getUrl(); ?>"
                    alt="<?= $escaper->escapeHtml($item->getName()) ?>" width="100" height="100" />
                <span class="text-base lg:text-lg text-heading font-medium">
                    <?= $escaper->escapeHtml($item->getName()) ?>
                </span>
            </div>
        <?php endif ?>
        <!--
            <div class="item-options flex flex-col items-stretch justify-between">
                <?php if ($block->getData('is_context_creditmemo')): ?>
                <?php else: ?>
                    <div class="flex">
                        <?php if ($options = $block->getItemOptions()): ?>
                            <div
                                class="order-2 lg:order-3 w-full bg-whizzy-artic rounded-lg text-whizzy-body text-sm py-1 px-1.5 text-center">
                                <span><?= __('Active customizations') ?></span>
                            </div>
                        <?php endif; ?>
                    </div>
                <?php endif ?>
            </div>
            -->
    </div>

    <?php if (!$block->getData('is_context_shipment')): ?>
        <div class="flex justify-between lg:block text-base text-whizzy-body mb-2 lg:mb-0">
            <p class="lg:sr-only"><?= $escaper->escapeHtml(__('Price')) ?></p>
            <?= $block->getItemPriceHtml() ?>
        </div>
    <?php endif; ?>

    <div class="flex justify-between lg:block mb-2 lg:mb-0">

        <div class="lg:sr-only text-right text-base text-whizzy-body mb-2 lg:mb-0">
            <?php if ($block->getData('is_context_invoice')): ?>
                <?= $escaper->escapeHtml(__('Qty Invoiced')) ?>
            <?php elseif ($block->getData('is_context_shipment')): ?>
                <div class="text-start">
                    <?= $escaper->escapeHtml(__('Qty Shipped')) ?>
                </div>
            <?php else: ?>
                <?= $escaper->escapeHtml(__('Qty')) ?>
            <?php endif; ?>
        </div>

        <div class="text-right lg:text-left text-base text-whizzy-body mb-2 lg:mb-0">
            <?php if ($block->getData('is_context_invoice') || $block->getData('is_context_creditmemo')): ?>
                <span class="content">
                    <?= /** @noEscape */ $localeFormatter->formatNumber($block->getItem()->getQty()) ?>
                </span>
            <?php endif; ?>
            <?php if ($block->getData('is_context_shipment')): ?>
                <span class="content">
                    <?= /** @noEscape */ $localeFormatter->formatNumber($block->getItem()->getQty()) ?>
                </span>
            <?php endif; ?>
            <?php if ($block->getData('is_context_order')): ?>
                <?php if ($block->getItem()->getQtyOrdered() > 0): ?>
                    <p class="mb-1">
                        <span class="title"><?= $escaper->escapeHtml(__('Ordered')) ?>:</span>
                        <span
                            class="content"><?= /** @noEscape */ $localeFormatter->formatNumber($block->getItem()->getQtyOrdered()) ?></span>
                    </p>
                <?php endif; ?>
                <?php if ($block->getItem()->getQtyShipped() > 0): ?>
                    <p class="mb-1">
                        <span class="title"><?= $escaper->escapeHtml(__('Shipped')) ?>:</span>
                        <span
                            class="content"><?= /** @noEscape */ $localeFormatter->formatNumber($block->getItem()->getQtyShipped()) ?></span>
                    </p>
                <?php endif; ?>
                <?php if ($block->getItem()->getQtyCanceled() > 0): ?>
                    <p class="mb-1">
                        <span class="title"><?= $escaper->escapeHtml(__('Canceled')) ?>:</span>
                        <span
                            class="content"><?= /** @noEscape */ $localeFormatter->formatNumber($block->getItem()->getQtyCanceled()) ?></span>
                    </p>
                <?php endif; ?>
                <?php if ($block->getItem()->getQtyRefunded() > 0): ?>
                    <p class="mb-1">
                        <span class="title"><?= $escaper->escapeHtml(__('Refunded')) ?>:</span>
                        <span
                            class="content"><?= /** @noEscape */ $localeFormatter->formatNumber($block->getItem()->getQtyRefunded()) ?></span>
                    </p>
                <?php endif; ?>
            <?php endif; ?>
        </div>
    </div>
    <?php if (!$block->getData('is_context_shipment')): ?>
        <div class="text-right flex justify-between lg:block">
            <p class="lg:sr-only text-right text-base text-whizzy-body mb-2 lg:mb-0">
                <?= $escaper->escapeHtml(__('Subtotal')) ?>
            </p>
            <?= $block->getItemRowTotalHtml() ?>
        </div>
    <?php endif; ?>
    <?php if ($block->getData('is_context_creditmemo')): ?>
        <div class="text-right flex justify-between lg:block">
            <p class="lg:sr-only text-right text-base text-whizzy-body mb-2 lg:mb-0">
                <?= $escaper->escapeHtml(__('Discount Amount')) ?>
            </p>
            <?= /* @noEscape */ $block->getOrder()->formatPrice($item->getDiscountAmount()) ?>
        </div>
        <div class="text-right flex justify-between lg:block">
            <p class="lg:sr-only text-right text-base text-whizzy-body mb-2 lg:mb-0">
                <?= $escaper->escapeHtml(__('Row Total')) ?>
            </p>
            <?= $block->getItemRowTotalAfterDiscountHtml() ?>
        </div>
    <?php endif; ?>
</div>