<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Shop By Hyva Compatibility
 */

declare(strict_types=1);

use Amasty\Shopby\Block\Navigation\State;
use Amasty\ShopbyHyvaCompatibility\ViewModel\ProductListAjax;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var State $block */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var ProductListAjax $productListAjax */
$productListAjax = $viewModels->require(ProductListAjax::class);

$filters = $block->getActiveFilters();
$value = [];
$pageLayout = $productListAjax->getPageLayout() ?: $block->getLayout()->getUpdate()->getPageLayout();
$isOneColumn = $pageLayout === '1column' || $pageLayout === 'cms-full-width' || $pageLayout === 'product-full-width';
$unfoldedCount = $block->getUnfoldedCount();
// phpcs:disable Generic.Files.LineLength.TooLong
?>

<?php if (!empty($filters)): ?>
    <div class="am-filter-state order-1 mt-4 filter-current filter-options-content card mb-8
        <?= /* @noEscape */ $isOneColumn ? 'max-w-[500px]' : ''; ?>"
         x-data="{ open: window.innerWidth > 768 }">
        <div class="filter-options-title flex justify-between items-center cursor-pointer"
             @click="open = !open"
             :aria-expanded="open ? 'true' : 'false'"
             role="button"
             tabindex="0"
        >
            <span class="font-semibold">
                <?= $escaper->escapeHtml(__('Active filtering')) ?>
                <span class="inline-block md:hidden">(<?= count($filters) ?>)</span>
            </span>
            <?php if (!$isOneColumn): ?>
            <span class="py-1 px-1">
                <?= $heroicons->chevronDownHtml('transition-transform transform duration-300 ease-in-out',18,18,[":class" => "{ 'rotate-180': open }"]); ?>
            </span>
            <?php endif; ?>
        </div>
        <div class="items am-filter pt-3" data-amshopby-filter-request-var="state" x-show="open">
            <?php foreach ($filters as $filter): ?>
                <?php
                $filterSetting = $block->getFilterSetting($filter->getFilter());

                /** @var \Magento\Catalog\Model\Layer\Filter\Item $filter */
                $value = $value ?: $filter->getValue();
                $resultValue = $block->getFilterValue($value, $filter);
                ?>
                <div class="amshopby-remove-item mb-1 flex justify-between items-center<?= /* @noEscape */ $filterSetting->isMultiselect() ? '' : ' radio-remove-item' ?>"
                    data-container="<?= /* @noEscape */ $filter->getFilter()->getRequestVar() ?>"
                    data-value="<?= /* @noEscape */ $block->getDataValue($resultValue) ?>"

                    <?php $resultValue = is_array($resultValue) ? $block->getDataValue($resultValue) : $resultValue ?>
                    <?php if (is_object($filter->getFilter()->getData('attribute_model')) && is_string($resultValue)): ?>
                        <?php $attributeId = $filter->getFilter()->getData('attribute_model')->getAttributeId() ?>
                        <?php $value = $productListAjax->getGroupsByAttributeId((int)$attributeId, $resultValue) ?>
                        data-attribute-id="<?= /* @noEscape */ $attributeId ?>"

                        <?php if ($value): ?>
                            data-massset="<?= $escaper->escapeHtmlAttr($value) ?>"
                        <?php else: ?>
                            data-swatchset="<?= $escaper->escapeHtmlAttr($resultValue) ?>"
                        <?php endif ?>
                    <?php endif ?>
                >
                    <span class="flex flex-wrap items-center">
                        <span class="filter-label block text-sm text-whizzy-graylighter after:content-[':'] after:ml-0.5 mr-1"><?= $escaper->escapeHtml(__($filter->getName())) ?></span>
                        <span class="filter-value block">
                            <?= /** @noEscape */ $block->viewLabel($filter) ?>
                        </span>
                    </span>
                    <span>
                        <a class="amshopby-remove py-2 px-2 text-center block action remove text-primary hover:text-primary-darker"
                           href="<?= $escaper->escapeUrl($filter->getRemoveUrl()) ?>"
                           title="<?= $escaper->escapeHtmlAttr(__('Remove This Item')) ?>"
                           @click.prevent.stop="if (document.querySelector('[x-data=\'shopBy()\']')) {
                                   window.dispatchEvent(new CustomEvent('amRemoveElement', {detail: {element: $event.currentTarget}}));
                               } else {
                                   window.location.href = '<?= $escaper->escapeUrl($filter->getRemoveUrl()) ?>';}">
                            <?= $heroicons->trashHtml('', 20, 20); ?>
                        </a>
                    </span>
                </div>
                <?php $value = $block->changeValueForMultiselect($filter->getFilter(), $value) ?>
            <?php endforeach; ?>

            <?php if ($block->getLayer()->getState()->getFilters()): ?>
                <div class="block-actions filter-actions mt-4">
                    <a
                        href="<?= $escaper->escapeUrl($block->getClearUrl()) ?>"
                        class="btn btn-size-sm"
                    ><?= $escaper->escapeHtml(__('Clear All')) ?></a>
                </div>
            <?php endif; ?>
            <div class="amshopby-button-wrap">
                <?php if ($unfoldedCount && $unfoldedCount < count($filters)): ?>
                    <?= /* @noEscape */ $block->createShowMoreButtonBlock() ?>
                <?php endif; ?>
            </div>
        </div>
    </div>
<?php endif; ?>
