<?php
declare(strict_types=1);

/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Shopby Base Hyva Compatibility (System)
 */

use Amasty\ShopbyBase\Api\Data\OptionSettingInterface;
use Amasty\ShopbyBase\Block\Product\AttributeIcon;
use Amasty\ShopbyBase\ViewModel\OptionProcessorInterface;
use Amasty\ShopByBaseHyvaCompatibility\ViewModel\Tooltip;
use Magento\Framework\Escaper;
use Hyva\Theme\Model\ViewModelRegistry;

/**
 * @var AttributeIcon $block
 * @var Escaper $escaper
 * @var ViewModelRegistry $viewModels
 */
$optionsData = $block->getOptionsData();
$tooltipViewModel = $viewModels->require(Tooltip::class);
// phpcs:disable Generic.Files.LineLength.TooLong
?>

<?php foreach ($optionsData as $setting): ?>
    <?php
    $title = $block->stripTags($setting[OptionProcessorInterface::TITLE]);
    $alt = $block->stripTags($setting[OptionSettingInterface::SMALL_IMAGE_ALT]) ?: $title;
    $img = !empty($setting[OptionProcessorInterface::IMAGE_URL]) ? $setting[OptionProcessorInterface::IMAGE_URL] : null;
    $tooltipJs = $setting[OptionProcessorInterface::TOOLTIP_JS] ?? null;
    ?>
    <?php if ($block->isShowBrandLink($setting)): ?>
        <span class="amshopby-option-link flex flex-col items-start absolute top-5 right-5 p-1 bg-white rounded-md" x-data="{
                  labelledById: '',
                  init() {
                      const timestamp = Date.now();
                      const randomNum = Math.floor(Math.random() * 1000);
                      this.labelledById = `amshopby-option-id-${timestamp}-${randomNum}`;
                  }
              }">
            <?php if ($setting[OptionProcessorInterface::DISPLAY_TITLE] ?? false): ?>
                <span class="brand-title">
                    <a href="<?= $escaper->escapeUrl($setting[OptionProcessorInterface::LINK_URL]); ?>"
                        class="amshopby-brand-title-link">
                        <?= /* @noEscape */ strtoupper($setting[OptionProcessorInterface::TITLE]); ?>
                    </a>
                </span>
            <?php endif; ?>
            <?php if ($setting[OptionProcessorInterface::LINK_URL] && !empty($img)): ?>
                <a href="<?= $escaper->escapeUrl($setting[OptionProcessorInterface::LINK_URL]); ?>"
                    title="<?= $escaper->escapeHtmlAttr($title); ?>" :aria-labelledby="labelledById">
                    <span :id="labelledById" role="button" aria-label="<?= $escaper->escapeHtmlAttr($title); ?>">
                        <?php if (!empty($tooltipJs)): ?>
                            <?= /** @noEscape */ $tooltipViewModel->renderTooltip($setting); ?>
                        <?php else: ?>
                            <img title="<?= $escaper->escapeHtmlAttr($title); ?>" alt="<?= $escaper->escapeHtmlAttr($alt) ?>"
                                src="<?= $escaper->escapeUrl($img) ?>" class="rounded-md w-10 lg:w-12 h-10 lg:h-12" />
                        <?php endif; ?>
                    </span>
                </a>
            <?php endif; ?>
        </span>
    <?php endif; ?>
<?php endforeach; ?>