<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Magento\Sales\Block\Order\Items;
use Magento\Shipping\Helper\Data as ShippingHelper;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper

/** @var Items $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

$order = $block->getOrder();
$shippingHelper = $this->helper(ShippingHelper::class);

$themeIcons = $viewModels->require(\MgtWizards\Base\ViewModel\ThemeIcons::class);

?>
<?php foreach ($order->getShipmentsCollection() as $shipment): ?>
    <?php $tracks = $shipment->getTracksCollection(); ?>

    <div
        class="flex flex-col lg:flex-row justify-between lg:items-center gap-2 p-6 bg-white shadow-whizzy-header rounded-lg h-full w-full mb-8">
        <div class="order-title text-2xl">
            <?= $escaper->escapeHtml(__('Shipment #')) ?>     <?= $escaper->escapeHtml($shipment->getIncrementId()) ?>
        </div>
        <div>
            <a href="<?= $escaper->escapeUrl($block->getUrl('*/*/printShipment', ['shipment_id' => $shipment->getId()])) ?>"
                target="_blank" rel="noopener">
                <div class="inline-flex items-center gap-x-1 lg:gap-x-2">
                    <?= $themeIcons->renderHtml('printer', '', 18, 18); ?>
                    <span
                        class="text-base py-2 lg:py-4 text-whizzy-body hover:text-whizzy-graylighter transition-all duration-200">
                        <?= $escaper->escapeHtml(__('Print Invoice')) ?>
                    </span>
                </div>
            </a>
        </div>
    </div>

    <?php if ($tracks->count()): ?>
        <div class="my-2">
            <p><?= $escaper->escapeHtml(__('Tracking Number(s):')) ?></p>
            <div class="tracking-content">
                <?php
                $i = 1;
                $size = $tracks->count();
                foreach ($tracks as $track): ?>
                    <?php if ($track->isCustom()): ?>
                        <?= $escaper->escapeHtml($track->getNumber()) ?>
                    <?php else: ?>
                        <a href="<?= $escaper->escapeUrl($shippingHelper->getTrackingPopupUrlBySalesModel($track)) ?>" target="_blank"
                            rel="noopener" class="inline-block underline"><span><?= $escaper->escapeHtml($track->getNumber()) ?></span>
                        </a>
                    <?php endif; ?>
                    <?php if ($i != $size): ?>, <?php endif; ?>
                    <?php $i++;
                endforeach; ?>
            </div>
        </div>
    <?php endif; ?>

    <div class="shipment flex flex-col gap-6 h-full mb-4">
        <div class="hidden lg:grid grid-cols-3 text-base text-whizzy-brown font-medium text-start">
            <div class="pb-4 col-span-2">
                <?= $escaper->escapeHtml(__('Product Name')) ?>
            </div>
            <div class="-ml-2 pb-4 col-span-1"><?= $escaper->escapeHtml(__('Qty')) ?></div>
        </div>
        <?php $items = $shipment->getAllItems(); ?>
        <?php foreach ($items as $item): ?>
            <?php if (!$item->getOrderItem()->getParentItem()): ?>
                <div class="p-6 bg-white shadow-whizzy-header rounded-lg h-full">
                    <?= $block->getItemHtml($item) ?>
                </div>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
<?php endforeach; ?>