<?php
/**
 * @category   MgtWizards
 * @package    MgtWizards_Popups
 * @author     bgaiteiro@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace MgtWizards\Popups\Block;

use Magento\Framework\View\Element\Template;
use Magento\Framework\Serialize\Serializer\Json;
use MgtWizards\Popups\Model\ResourceModel\Popups\CollectionFactory;
use Magento\Store\Model\ScopeInterface;
use Magento\Framework\App\Config\ScopeConfigInterface;

class Popups extends Template
{
    const XML_PATH_ENABLED = 'popups/general/enabled';
    const XML_PATH_COOKIE_BASE = 'popups/general/cookie_base_name';

    private $collectionFactory;
    private $json;
    protected $_scopeConfig;

    public function __construct(
        Template\Context $context,
        CollectionFactory $collectionFactory,
        Json $json,
        ScopeConfigInterface $scopeConfig,
        array $data = []
    ) {
        parent::__construct($context, $data);
        $this->collectionFactory = $collectionFactory;
        $this->json = $json;
        $this->_scopeConfig = $scopeConfig;
    }

    public function canShow()
    {
        return $this->_scopeConfig->isSetFlag(self::XML_PATH_ENABLED, ScopeInterface::SCOPE_STORE);
    }

    public function getPopups()
    {
        $collection = $this->collectionFactory->create()
            ->addFieldToFilter('status', 1)
            ->setOrder('sort_order', 'ASC');

        $popups = [];
        foreach ($collection->getItems() as $popup)
        {
            $popups[] = [
                'popup_id' => (int)$popup->getPopupsId(),
                'position' => $popup->getPosition(),
                'image' => $popup->getImage(),
                'title' => $popup->getTitle(),
                'content' => $popup->getContent(),
                'display_mode' => $popup->getDisplayMode(),
                'delay_time' => (int)$popup->getDelayTime(),
                'cookie_time' => (int)$popup->getCookieTime(),
                'visible' => false
            ];
        }
        return $popups;
    }

    public function getCookieBase()
    {
        return $this->_scopeConfig->getValue(self::XML_PATH_COOKIE_BASE, ScopeInterface::SCOPE_STORE) ?: 'mgtw_popup';
    }

    protected function _toHtml()
    {
        return $this->canShow() ? parent::_toHtml() : '';
    }
}