<?php
use Magezon\Builder\Block\Element;
/** @var $block Element */

$elements = $this->getElements();
$count = count($elements);
$element = $this->getElement();
$id_owl = $element->getId();
$coreHelper = $this->helper('\Magezon\Core\Helper\Data');
$carouselOptions = $this->getOwlCarouselOptions();
$classes = $this->getOwlCarouselClasses();
?>

<?php if ($count) { ?>
    <?php
    $items = [];
    foreach ($elements as $index => $_element) {
        $_html = $_element->toHtml();
        $items[] = [
            'element' => $_element,
            'html'    => $_html
        ];
    } ?>
    <div id="<?= $id_owl ?>" class="mgz-carousel owl-carousel <?= implode(' ', $classes) ?>">
        <?php foreach ($items as $index => $item) { ?>
            <?php
            $_element = $item['element'];
            $id       = $_element->getId();
            ?>
            <div class="item mgz-carousel-item">
                <?= $item['html'] ?>
            </div>
        <?php } ?>
    </div>
<?php } ?>

<script>
    loadScript('<?= $block->getViewFileUrl('Hyva_MagezonBuilder::js/jquery.min.js') ?>', 'jquery')
        .then(() => {
            return loadScript('<?= $block->getViewFileUrl('Magezon_Core::js/owl.carousel.min.js') ?>', 'carousel');
        })
        .then(() => {
            return loadScript('<?= $block->getViewFileUrl('Hyva_MagezonBuilder::js/slider.min.js') ?>', 'slider');
        })
        .then(() => {
            $('#<?= $id_owl ?>').slider(<?= $coreHelper->serialize($carouselOptions) ?>);
        })
</script>

