<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package FAQ and Product Questions for Magento 2
 */ /** @var \Amasty\Faq\Block\Widgets\SearchBox $block */ ?>
<div class="am-search-box-wrapper">
    <div class="flex justify-center">
        <div class="w-full max-w-xl">
            <?= /** @noEscape */ $block->getSearchBlockHtml() ?>
        </div>
    </div>
</div>
<style>
    .page-title-wrapper h1.page-title {
        font-size: 28px;
    }
</style>