<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Customer\Block\Form\Login\Info;
use Magento\Framework\Escaper;

$themeIcons = $viewModels->require(\MgtWizards\Base\ViewModel\ThemeIcons::class);

/** @var Info $block */
/** @var Escaper $escaper */
?>
<?php if ($block->getRegistration()->isAllowed()): ?>
    <div class="block-new-customer w-full bg-white shadow-whizzy-base p-8 rounded-b-lg lg:max-w-md mx-auto">
        <div class="flex flex-col lg:flex-row gap-x-2 justify-start text-sm lg:text-base">
            <div class="text-whizzy-body">
                <?= $escaper->escapeHtml(__('No account yet?')) ?>
            </div>
            <a href="<?= $escaper->escapeUrl($block->getCreateAccountUrl()) ?>"
                class="group text-whizzy-graylighter hover:text-whizzy-body transition-all duration-300">
                <div class="inline-flex items-center gap-x-1">
                    <?= $escaper->escapeHtml(__('Create an Account')) ?>
                    <?= $themeIcons->renderHtml('arrow-up-right', 'group-hover:rotate-45 transition-all duration-200', 18, 18, ['aria-hidden' => 'true']) ?>
                </div>
            </a>
        </div>
    </div>
<?php endif; ?>