<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Customer\Block\Account\Dashboard\Address;
use Magento\Framework\Escaper;

/** @var Address $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

$themeIcons = $viewModels->require(\MgtWizards\Base\ViewModel\ThemeIcons::class);
?>
<div class="mb-6 text-sm lg:text-base">
    <div class="py-6 px-4 lg:py-8 lg:px-6">
        <div class="flex flex-col lg:flex-row justify-between items-start lg:items-center gap-y-3 w-full">
            <span class="text-2xl text-heading">
                <?= $escaper->escapeHtml(__('Address Book')) ?>
            </span>
            <a class="action edit text-base lg:text-center text-whizzy-body hover:text-whizzy-graylighter transition-all duration-100 underline font-medium"
                href="<?= $escaper->escapeUrl($block->getAddressBookUrl()) ?>">
                <span><?= $escaper->escapeHtml(__('Manage Addresses')) ?></span>
            </a>
        </div>
    </div>
    <div class="flex flex-col lg:flex-row gap-6">
        <div class="w-full lg:w-1/2">
            <div
                class="flex flex-col lg:flex-row gap-x-3 lg:gap-x-4 py-6 px-4 lg:py-8 lg:px-6 bg-white shadow-whizzy-header rounded-lg h-full">
                <div
                    class="flex flex-col justify-between gap-y-2 lg:gap-y-4 w-full text-base text-start text-whizzy-body">
                    <div class="text-lg text-whizzy-body font-medium">
                        <span><?= $escaper->escapeHtml(__('Default Billing Address')) ?></span>
                    </div>
                    <div class="font-medium text-whizzy-graylighter">
                        <address class="not-italic">
                            <?= $block->getPrimaryBillingAddressHtml() ?>
                        </address>
                    </div>
                    <?= $block->getChildHtml('customer.account.dashboard.info.extra'); ?>
                    <a class="mt-3 w-full inline-flex items-center md:text-sm text-secondary hover:text-secondary-darker"
                        href="<?= $escaper->escapeUrl($block->getPrimaryBillingAddressEditUrl()) ?>"
                        data-ui-id="default-billing-edit-link"
                        aria-label="<?= $escaper->escapeHtmlAttr(__('Edit Address - billing default')) ?>">
                        <span><?= $escaper->escapeHtml(__('Edit Address')) ?></span>
                        <?= $heroicons->arrowRightHtml('ml-2', 16, 16, ['aria-hidden' => 'true']); ?>
                    </a>
                </div>
            </div>
        </div>
        <div class="w-full lg:w-1/2">
            <div
                class="flex flex-col lg:flex-row gap-x-3 lg:gap-x-4 py-6 px-4 lg:py-8 lg:px-6 bg-white shadow-whizzy-header rounded-lg h-full">
                <div
                    class="flex flex-col justify-between gap-y-2 lg:gap-y-4 w-full text-base text-start text-whizzy-body">
                    <div class="text-lg text-whizzy-body font-medium">
                        <span><?= $escaper->escapeHtml(__('Default Shipping Address')) ?></span>
                    </div>
                    <div class="font-medium text-whizzy-graylighter">
                        <address class="not-italic">
                            <?= $block->getPrimaryShippingAddressHtml() ?>
                        </address>
                    </div>
                    <?= $block->getChildHtml('customer.account.dashboard.info.extra'); ?>
                    <a class="mt-3 w-full inline-flex items-center md:text-sm text-secondary hover:text-secondary-darker"
                        href="<?= $escaper->escapeUrl($block->getPrimaryShippingAddressEditUrl()) ?>"
                        data-ui-id="default-billing-edit-link"
                        aria-label="<?= $escaper->escapeHtmlAttr(__('Edit Address - shipping default')) ?>">
                        <span><?= $escaper->escapeHtml(__('Edit Address')) ?></span>
                        <?= $heroicons->arrowRightHtml('ml-2', 16, 16, ['aria-hidden' => 'true']); ?>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>