<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Customer\Block\Address\Book;
use Magento\Framework\Escaper;

/** @var Book $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

$themeIcons = $viewModels->require(\MgtWizards\Base\ViewModel\ThemeIcons::class);

?>
<div class="block block-addresses-default mb-6">
    <div class="text-2xl mb-6 text-heading"><?= $escaper->escapeHtml(__('Default Addresses')) ?></div>
    <div class="flex flex-col lg:flex-row gap-y-6 lg:gap-y-0 gap-x-4 lg:gap-x-6">
        <?php if ($customerDefaultBillingAddress = $block->getDefaultBilling()): ?>
            <div class="w-full lg:w-1/2">
                <div class="relative flex flex-col lg:flex-row gap-x-3 lg:gap-x-4 card h-full">
                    <div class="flex flex-col gap-y-3">
                        <div class="text-lg text-whizzy-body font-medium">
                            <span><?= $escaper->escapeHtml(__('Default Billing Address')) ?></span>
                        </div>
                        <div class="font-medium text-whizzy-body text-sm">
                            <address class="not-italic">
                                <?= $block->getAddressHtml($block->getAddressById($customerDefaultBillingAddress)) ?>
                            </address>
                        </div>
                        <div class="box-actions">
                            <a class="absolute bottom-6 right-6 text-whizzy-body bg-whizzy-primary-lighter hover:bg-whizzy-separator transition-all duration-200 p-3 rounded-lg"
                                href="<?= $escaper->escapeUrl($block->getAddressEditUrl($customerDefaultBillingAddress)) ?>">
                                <?= $themeIcons->renderHtml('edit-01', '', 20, 20, ['aria-hidden' => 'true']); ?>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        <?php else: ?>
            <div class="w-full lg:w-1/2">
                <div class="flex flex-col lg:flex-row gap-x-3 lg:gap-x-4 card h-full">
                    <div class="flex flex-col gap-y-3">
                        <div class="text-lg text-whizzy-body font-medium">
                            <span><?= $escaper->escapeHtml(__('Default Billing Address')) ?></span>
                        </div>
                        <div class="font-medium text-whizzy-body text-sm">
                            <?= $escaper->escapeHtml(__('You have no default billing address in your address book.')) ?>
                        </div>
                    </div>
                </div>
            </div>
        <?php endif ?>
        <?php if ($customerDefaultBillingAddress = $block->getDefaultShipping()): ?>
            <div class="w-full lg:w-1/2">
                <div class="relative flex flex-col lg:flex-row gap-x-3 lg:gap-x-4 card h-full">
                    <div class="flex flex-col gap-y-3">
                        <div class="text-lg text-whizzy-body font-medium">
                            <span><?= $escaper->escapeHtml(__('Default Shipping Address')) ?></span>
                        </div>
                        <div class="font-medium text-whizzy-body text-sm">
                            <address class="not-italic">
                                <?= $block->getAddressHtml($block->getAddressById($customerDefaultBillingAddress)) ?>
                            </address>
                        </div>
                        <div class="box-actions">
                            <a class="absolute bottom-6 right-6 text-whizzy-body bg-whizzy-primary-lighter hover:bg-whizzy-separator transition-all duration-200 p-3 rounded-lg"
                                href="<?= $escaper->escapeUrl($block->getAddressEditUrl($customerDefaultBillingAddress)) ?>">
                                <?= $themeIcons->renderHtml('edit-01', '', 20, 20, ['aria-hidden' => 'true']); ?>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        <?php else: ?>
            <div class="w-full lg:w-1/2">
                <div class="flex flex-col lg:flex-row gap-x-3 lg:gap-x-4 card h-full">
                    <div class="flex flex-col gap-y-3">
                        <div class="text-lg text-whizzy-body font-medium">
                            <span><?= $escaper->escapeHtml(__('Default Shipping Address')) ?></span>
                        </div>
                        <div class="font-medium text-whizzy-body text-sm">
                            <?= $escaper->escapeHtml(__('You have no default shipping address in your address book.')) ?>
                        </div>
                    </div>
                </div>
            </div>
        <?php endif ?>
    </div>
</div>