<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Magento\Framework\Escaper;
use Magento\Review\Block\Product\View as ProductReview;
use Magento\Theme\Block\Html\Pager;

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var ProductReview $block */
/** @var SecureHtmlRenderer $secureRenderer */
/** @var Escaper $escaper */
/** @var Pager $toolbar */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

$reviewCollection = $block->getReviewsCollection();

// Note: Setting the collection on the toolbar block applies pagination, so it has to happen before collection loading.
if ($toolbar = $block->getChildBlock('review_list.toolbar'))
{
    $toolbar->setCollection($reviewCollection);
}
$reviewCollection->load()->addRateVotes();

$items = $reviewCollection->getItems();
$format = $block->getDateFormat() ?: \IntlDateFormatter::SHORT;
$formatLong = $block->getDateFormat() ?: \IntlDateFormatter::LONG;
$formatMedium = $block->getDateFormat() ?: \IntlDateFormatter::MEDIUM;
$headingTag = $block->getData('heading_tag') ?: 'h3';
$productName = $block->getProduct()->getName();

$themeIcons = $viewModels->require(\MgtWizards\Base\ViewModel\ThemeIcons::class);
$flagsIcons = $viewModels->require(\MgtWizards\Base\ViewModel\FlagsIcons::class);
$whizzyReviewGeoIpHelper = $this->helper('MgtWizards\ReviewGeoIp\Helper\GeoIp');
?>
<?php if (!$block->getHideTitle()): ?>
    <div class="flex flex-col gap-3 font-bold mb-3 lg:mb-6">
        <div class="text-sm uppercase text-whizzy-graylighter">
            <?= $escaper->escapeHtml(__('Reviews')) ?>
        </div>
        <div class="text-3xl lg:text-4xl text-whizzy-body">
            <?= $escaper->escapeHtml(__('Customer Reviews')) ?>
        </div>
    </div>
<?php endif ?>
<?php if (count($items)): ?>
    <div class="flex flex-col gap-3 lg:gap-6">
        <div id="customer-review-list" class="grid gap-3">
            <?php foreach ($items as $review): ?>
                <div itemscope itemprop="review" itemtype="https://schema.org/Review"
                    class="border p-6 border-gray-300 rounded-lg bg-white">

                    <div class="grid lg:grid-cols-3 gap-6">
                        <div class="lg:border-r">
                            <div class="mt-4 grid gap-3">
                                <div class="text-sm flex gap-2 items-center font-semibold">
                                    <?= $themeIcons->renderHtml('user', 'text-gray-500 w-5 h-5', 20, 20, ['aria-hidden' => 'true']) ?>
                                    <span itemprop="author" itemscope itemtype="https://schema.org/Person">
                                        <span itemprop="name"><?= $escaper->escapeHtml($review->getNickname()) ?></span>
                                    </span>
                                    <?php if ($review->getCustomerId()): ?>
                                        <span class="text-green-700 ml-2"><?= $escaper->escapeHtml('Verified Buyer') ?></span>
                                    <?php else: ?>
                                        <span class="text-amber-700 ml-2"><?= $escaper->escapeHtml('Guest Reviewer') ?></span>
                                    <?php endif; ?>
                                </div>

                                <?php $reviewGeoIp = $whizzyReviewGeoIpHelper->getGeoDataByReviewId($review->getId()); ?>
                                <?php if ($reviewGeoIp['country_code'] != ''): ?>
                                    <div class="text-sm flex gap-2 items-center">
                                        <div class="shrink-0 w-5 h-5 rounded-full overflow-hidden">
                                            <?= $flagsIcons->renderHtml(strtolower($reviewGeoIp['country_code']), '', 20, 20, ['aria-hidden' => 'true']) ?>
                                        </div>
                                        <span
                                            class="text-gray-500"><?= $escaper->escapeHtml(__('From %1, %2', $reviewGeoIp['city'], $reviewGeoIp['country'])) ?></span>
                                    </div>
                                <?php endif; ?>

                                <?php
                                /** @var \Magento\Customer\Api\CustomerRepositoryInterface $customerRepository */
                                $customerRepository = \Magento\Framework\App\ObjectManager::getInstance()
                                    ->get(\Magento\Customer\Api\CustomerRepositoryInterface::class);
                                $customerSince = null;
                                if ($review->getCustomerId())
                                {
                                    try
                                    {
                                        $customer = $customerRepository->getById($review->getCustomerId());
                                        //$customerSince = date('F, Y', strtotime($customer->getCreatedAt()));
                                        $customerSince = $block->formatDate($customer->getCreatedAt(), $formatMedium);
                                    }
                                    catch (\Magento\Framework\Exception\NoSuchEntityException $e)
                                    {
                                        // Handle the case where the customer does not exist
                                        $customerSince = null;
                                    }
                                }
                                ?>
                                <?php if ($customerSince): ?>
                                    <div class="text-sm flex gap-2 items-center text-gray-500">
                                        <?= $themeIcons->renderHtml('calendar-user', 'text-gray-500 w-5 h-5', 20, 20, ['aria-hidden' => 'true']) ?>
                                        <span><?= $escaper->escapeHtml(__('Customer since %1', $customerSince)) ?></span>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                        <div class="col-span-2">
                            <div class="flex gap-3 flex-wrap items-center mb-2">
                                <div class="text-xl font-semibold grow" itemprop="name">
                                    <?= $escaper->escapeHtml($review->getTitle()) ?>
                                </div>

                                <time class="text-gray-500 text-sm" itemprop="datePublished"
                                    datetime="<?= $escaper->escapeHtmlAttr($block->formatDate($review->getCreatedAt(), $format)); ?>">
                                    <span class="sr-only">
                                        <?= $escaper->escapeHtml($block->formatDate($review->getCreatedAt(), $formatLong)) ?>
                                    </span>
                                    <span aria-hidden="true">
                                        <?= $escaper->escapeHtml($block->formatDate($review->getCreatedAt(), $formatMedium)) ?>
                                    </span>
                                </time>
                            </div>

                            <?php if (count($review->getRatingVotes())): ?>
                                <div class="flex flex-nowrap mb-2 relative">
                                    <?php
                                    $totalPercent = 0;
                                    $voteCount = count($review->getRatingVotes());
                                    foreach ($review->getRatingVotes() as $vote)
                                    {
                                        $totalPercent += $vote->getPercent();
                                    }
                                    $averagePercent = $voteCount > 0 ? $totalPercent / $voteCount : 0;
                                    $ratingSteps = 5;
                                    $starsFilled = is_numeric($averagePercent) ? floor($averagePercent / 100 * $ratingSteps) : 0;
                                    $starsEmpty = $ratingSteps - $starsFilled;
                                    ?>
                                    <div class="table-row text-sm" itemprop="reviewRating" itemscope
                                        itemtype="https://schema.org/Rating">
                                        <span class="hidden" itemprop="ratingValue"><?= /** @noEscape */ $starsFilled; ?></span>
                                        <div class="flex flex-row" role="img"
                                            aria-label="<?= $escaper->escapeHtmlAttr(__('%1 rating. %2 out of %3 stars', $productName, $starsFilled, $ratingSteps)) ?>">
                                            <?php $i = 0; ?>
                                            <?php while ($i < $starsFilled): ?>
                                                <?= $heroiconsSolid->starHtml('text-yellow-400', 24, 24, ["aria-hidden" => "true"]); ?>
                                                <?php $i++; ?>
                                            <?php endwhile; ?>
                                            <?php $i = 0; ?>
                                            <?php while ($i < $starsEmpty): ?>
                                                <?= $heroiconsSolid->starHtml('text-gray-400', 24, 24, ["aria-hidden" => "true"]); ?>
                                                <?php $i++; ?>
                                            <?php endwhile; ?>
                                        </div>
                                    </div>
                                </div>
                            <?php endif; ?>

                            <div class="review-content">
                                <?= /* @noEscape */ nl2br($escaper->escapeHtml($review->getDetail())) ?>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <?php if ($toolbar): ?>
            <div class="toolbar review-toolbar mt-4">
                <?= $toolbar->toHtml() ?>
            </div>
        <?php endif; ?>
    </div>
<?php endif; ?>