<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Customer\ForgotPasswordButton;
use Hyva\Theme\ViewModel\ReCaptcha;
use Magento\Customer\Block\Account\Forgotpassword;
use Magento\Framework\Escaper;

/** @var Forgotpassword $block */
/** @var Escaper $escaper */
/** @var ReCaptcha $recaptcha */
/** @var ForgotPasswordButton $forgotPasswordButtonViewModel */
/** @var ViewModelRegistry $viewModels */

$forgotPasswordButtonViewModel = $viewModels->require(ForgotPasswordButton::class);

$formId = 'user_forgotpassword';

$themeIcons = $viewModels->require(\MgtWizards\Base\ViewModel\ThemeIcons::class);

// Do not replace this with $viewModels->require(ReCaptcha::class); that might break the dependency
// on the Magento_ReCaptchaCustomer module
$recaptcha = $block->getData('viewModelRecaptcha');
?>
<div class="flex flex-col text-sm lg:text-base bg-white shadow-whizzy-header p-8 rounded-lg lg:max-w-md mx-auto">
    <form action="<?= $escaper->escapeUrl($block->getUrl('*/*/forgotpasswordpost')) ?>" method="post"
        id="<?= $escaper->escapeHtmlAttr($formId) ?>" x-data="initPasswordForm()" @submit.prevent="submitForm();">
        <?= $block->getBlockHtml('formkey') ?>
        <input type="hidden" name="formId" value="<?= $escaper->escapeHtmlAttr($formId) ?>" />
        <?= $block->getChildHtml('form_fields_before') ?>
        <fieldset class="fieldset flex flex-col gap-y-4">

            <div class="flex flex-row items-center gap-x-3 mx-auto pb-4">
                <div class="text-whizzy-body page-title title-font text-2xl lg:text-3xl font-semibold text-center">
                    <?= $escaper->escapeHtmlAttr(__('Forgot your Password')) ?>
                </div>
            </div>
            <div class="text-whizzy-graylighter text-sm text-center mb-4">
                <?= $escaper->escapeHtml(__('Please enter your email address below to receive a password reset link.')) ?>
            </div>

            <div class="field email w-full required">
                <label for="email_address" class="label"><span><?= $escaper->escapeHtml(
                __('Email')
                ) ?></span></label>
                <div class="control">
                    <input type="email" name="email" alt="email" id="email_address"
                        class="form-input w-full text-sm lg:text-base" required
                        value="<?= $escaper->escapeHtmlAttr($block->getEmailValue()) ?>"
                        placeholder="<?= __('Your Email') ?>">
                </div>
            </div>

            <?= $recaptcha ? $recaptcha->getInputHtml(ReCaptcha::RECAPTCHA_FORM_ID_CUSTOMER_FORGOT_PASSWORD) : '' ?>
            <?= $block->getChildHtml('form_additional_info') ?>
            <?= $recaptcha ? $recaptcha->getLegalNoticeHtml(ReCaptcha::RECAPTCHA_FORM_ID_CUSTOMER_FORGOT_PASSWORD) : '' ?>
        </fieldset>
        <div class="flex flex-col items-center w-full gap-y-4 mt-8 mb-4">
            <button class="btn btn-primary action submit primary w-full disabled:opacity-75" type="submit" <?php if ($forgotPasswordButtonViewModel->disabled()): ?> disabled="disabled" data-recaptcha-btn<?php endif; ?>>
                <?= $escaper->escapeHtml(__('Reset my Password')) ?>
            </button>
            <a class="w-fit action back text-whizzy-body lg:text-whizzy-graylighter hover:text-whizzy-body cursor-pointer"
                href="<?= $escaper->escapeUrl($block->getLoginUrl()) ?>">
                <span><?= $escaper->escapeHtml(__('Go back')) ?></span>
            </a>
        </div>
    </form>
    <script>
        function initPasswordForm() {
            return {
                errors: 0,
                hasCaptchaToken: 0,
                submitForm() {
                    // Do not rename $form, the variable is expected to be declared in the recaptcha output
                    const $form = document.querySelector('#<?= $escaper->escapeJs($formId) ?>');
                    <?= $recaptcha ? $recaptcha->getValidationJsHtml(ReCaptcha::RECAPTCHA_FORM_ID_CUSTOMER_FORGOT_PASSWORD) : '' ?>

                    if (this.errors === 0) {
                        $form.submit();
                    }
                }
            }
        }
    </script>
</div>