<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Customer\LoginButton;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Hyva\Theme\ViewModel\ReCaptcha;
use Magento\Customer\Block\Form\Login;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var Login $block */
/** @var LoginButton $loginButtonViewModel */
/** @var ViewModelRegistry $viewModels */
/** @var ReCaptcha $recaptcha */
/** @var HeroiconsOutline $heroiconsoutline */
/** @var HeroiconsSolid $heroiconssolid */

$heroiconsoutline = $viewModels->require(HeroiconsOutline::class);
$heroiconssolid = $viewModels->require(HeroiconsSolid::class);
$loginButtonViewModel = $viewModels->require(LoginButton::class);

$themeIcons = $viewModels->require(\MgtWizards\Base\ViewModel\ThemeIcons::class);

// Disabling autocomplete on form fields is not recommended,
// Enable it in Stores->Configuration->Customers configuration->Password Options

// Do not replace this with $viewModels->require(ReCaptcha::class); that might break the dependency
// on the Magento_ReCaptchaCustomer module
$recaptcha = $block->getData('viewModelRecaptcha');
?>
<div class="w-full bg-white shadow-whizzy-base p-8 pb-2 rounded-t-lg lg:max-w-md mx-auto">
    <div aria-labelledby="block-customer-login-heading">
        <form class="form form-login flex flex-col w-full text-sm lg:text-base"
            action="<?= $escaper->escapeUrl($block->getPostActionUrl()) ?>" method="post"
            x-data="initCustomerLoginForm()" @submit.prevent="submitForm()" id="customer-login-form">
            <?= $block->getBlockHtml('formkey') ?>
            <fieldset class="fieldset login flex flex-col gap-y-4">
                <div class="flex flex-row items-center gap-x-3 mx-auto pb-4">
                    <div class="text-whizzy-body page-title title-font text-2xl lg:text-3xl font-semibold text-center">
                        <?= $escaper->escapeHtmlAttr(__('Welcome Back')) ?>
                    </div>
                    <span><?= $themeIcons->renderHtml('waving-hand', '', 36, 36) ?></span>
                </div>

                <div class="field email required">
                    <label class="label" for="email"><span><?= $escaper->escapeHtml(__('Email ')) ?></span></label>
                    <div class="control">
                        <input name="login[username]" class="form-input w-full text-sm lg:text-base" required
                            value="<?= $escaper->escapeHtmlAttr($block->getUsername()) ?>"
                            autocomplete="<?= $block->isAutocompleteDisabled() ? 'off' : 'email' ?>" id="email"
                            type="email" title="<?= $escaper->escapeHtmlAttr(__('Email')) ?>"
                            placeholder="<?= __('Your Email') ?>" />
                    </div>
                </div>
                <div class="field password required">
                    <label for="pass" class="label">
                        <span>
                            <?= $escaper->escapeHtml(__('Password')) ?>
                        </span>
                    </label>
                    <div class="control flex items-center relative">
                        <div class="sr-only" aria-live="polite">
                            <template x-if="!showPassword">
                                <span>
                                    <?= $escaper->escapeHtml(__('Password hidden')) ?>
                                </span>
                            </template>
                            <template x-if="showPassword">
                                <span>
                                    <?= $escaper->escapeHtml(__('Password shown')) ?>
                                </span>
                            </template>
                        </div>
                        <input name="login[password]" class="form-input w-full text-sm lg:text-base" required
                            :type="showPassword ? 'text' : 'password'"
                            autocomplete="<?= $block->isAutocompleteDisabled() ? 'off' : 'current-password' ?>"
                            id="pass" title="<?= $escaper->escapeHtmlAttr(__('Password')) ?>"
                            placeholder="<?= __('Your Password') ?>" />
                        <button type="button" x-on:click="showPassword = !showPassword"
                            :aria-pressed="showPassword ? 'true' : 'false'"
                            class="absolute top-1/2 right-1.5 -translate-y-1/2 cursor-pointer text-whizzy-body bg-whizzy-beige hover:bg-whizzy-separator transition-all duration-200 p-2 rounded-lg"
                            :aria-label="showPassword ? '<?= $escaper->escapeJs(__('Hide Password')) ?>' : '<?= $escaper->escapeJs(__('Show Password')) ?>'">
                            <template x-if="!showPassword">
                                <?= $themeIcons->renderHtml('view-off', 'text-whizzy-graysmooth hover:text-whizzy-body', 18, 18) ?>
                            </template>
                            <template x-if="showPassword">
                                <?= $themeIcons->renderHtml('view-off-slash', 'text-whizzy-graysmooth hover:text-whizzy-body', 18, 18) ?>
                            </template>
                        </button>
                    </div>
                </div>

                <?= $recaptcha ? $recaptcha->getInputHtml(ReCaptcha::RECAPTCHA_FORM_ID_CUSTOMER_LOGIN) : '' ?>
                <?= $block->getChildHtml('form_additional_info') ?>
                <div class="flex flex-col w-full gap-y-4 my-4">
                    <button class="btn btn-primary" type="submit" name="send" <?php if ($loginButtonViewModel->disabled()): ?> disabled="disabled" data-recaptcha-btn<?php endif; ?>>
                        <?= $escaper->escapeHtml(__('Log In')) ?>
                    </button>
                    <a class="w-fit text-whizzy-body lg:text-whizzy-graylighter hover:text-whizzy-body cursor-pointer"
                        href="<?= $escaper->escapeUrl(
                            $block->getForgotPasswordUrl()
                        ) ?>"><span><?= $escaper->escapeHtml(__('Forgot Password')) ?></span>
                    </a>
                </div>
                <div>
                    <template x-if="displayErrorMessage">
                        <p class="text-red flex items-center">
                            <span class="inline-block w-8 h-8 mr-3">
                                <?= $heroiconsoutline->exclamationCircleHtml(); ?>
                            </span>
                            <template x-for="errorMessage in errorMessages">
                                <span x-html="errorMessage"></span>
                            </template>
                        </p>
                    </template>
                </div>
            </fieldset>
        </form>
        <div class="w-full">
            <?= $recaptcha ? $recaptcha->getLegalNoticeHtml(ReCaptcha::RECAPTCHA_FORM_ID_CUSTOMER_LOGIN) : '' ?>
        </div>
    </div>
    <script>
        function initCustomerLoginForm() {
            return {
                errors: 0,
                hasCaptchaToken: 0,
                showPassword: false,
                displayErrorMessage: false,
                errorMessages: [],
                setErrorMessages(messages) {
                    this.errorMessages = [messages]
                    this.displayErrorMessage = this.errorMessages.length
                },
                submitForm() {
                    // do not rename $form, the variable is the expected name in the recaptcha output
                    const $form = document.querySelector('#customer-login-form');
                    <?= $recaptcha ? $recaptcha->getValidationJsHtml(ReCaptcha::RECAPTCHA_FORM_ID_CUSTOMER_LOGIN) : '' ?>

                    if (this.errors === 0) {
                        $form.submit();
                    }
                }
            }
        }
    </script>
</div>