<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
?>
<?php
/**
 * Blog post list item template
 *
 * @var $block \Magefan\Blog\Block\Post\PostList\Item
 */
?>
<?php
$_post = $block->getPost();
$_postUrl = $escaper->escapeUrl($_post->getPostUrl());
$_postName = $escaper->escapeHtml($_post->getTitle());
$imageHelper = $this->helper(\Magefan\Blog\Helper\Image::class);
?>
<li
    class="flex flex-col gap-4 bg-whizzy-artic rounded-lg pb-4 lg:pb-8 post-holder post-holder-<?= (int)$_post->getId() ?>">
    <div class="relative h-full z-10">
        <?php $featuredImage = $_post->getFeaturedListImage() ?: $_post->getFeaturedImage(); ?>
        <?php if ($featuredImage)
        { ?>
            <?php
            $featuredImgAlt = $_post->getData('featured_list_img_alt') ?: $_post->getData('featured_img_alt');
            if (!$featuredImgAlt)
            {
                $featuredImgAlt = $_postName;
            }
            ?>
            <?php $featuredImage = $imageHelper->init($_post->getData('featured_img'))->resize(600, null, false); ?>
            <div class="h-40 lg:h-[250px] overflow-hidden mb-4 lg:mb-6 rounded-lg">
                <a href="<?= /*@noEscape*/ $_postUrl ?>">
                    <img class="h-full w-full object-cover hover:scale-110 transition-transform duration-300 cursor-pointer"
                        src="<?= $escaper->escapeUrl($featuredImage) ?>"
                        alt="<?= $escaper->escapeUrl($featuredImgAlt) ?>" />
                </a>
            </div>
        <?php } ?>
        <?= /*@noEscape*/ $block->getInfoHtml() ?>
        <div class="post-header container flex flex-col gap-2 px-6 lg:px-10 pb-6">
            <div class="post-title-holder flex items-center justify-between flex-wrap">
                <h2
                    class="post-title font-semibold leading-wide text-xl lg:text-2xl text-whizzy-body hover:text-whizzy-graylighter transition-all duration-200">
                    <a class="post-item-link" href="<?= /*@noEscape*/ $_postUrl ?>">
                        <?= /*@noEscape*/ $_postName ?>
                    </a>
                </h2>
            </div>
        </div>
        <div class="px-6 lg:px-10">
            <?php if ($block->authorEnabled())
            { ?>
                <?php if ($_author = $_post->getAuthor())
                { ?>
                    <div class="item post-author flex flex-row items-center gap-3">
                        <?php $featuredAuthorImage = $_author->getFeaturedListImage() ?: $_author->getFeaturedImage(); ?>
                        <?php if ($featuredAuthorImage): ?>
                            <div class="w-fit">
                                <img class="h-12 w-12 rounded-full" src="<?= $featuredAuthorImage ?>"
                                    alt="<?= $block->escapeHtml($_author->getName()) ?>" />
                            </div>
                        <?php endif ?>
                        <div
                            class="blog-post-meta-author flex flex-col gap-1 leading-wide text-sm lg:text-base text-whizzy-body">
                            <?php if ($authorPageEnabled = $block->authorPageEnabled())
                            { ?>
                                <a title="<?= $block->escapeHtml($_author->getTitle()) ?>" class="hover:underline"
                                    href="<?= $block->escapeUrl($_author->getAuthorUrl()) ?>">
                                <?php } ?>
                                <div class="font-semibold">
                                    <?= $block->escapeHtml($_author->getTitle()) ?>
                                </div>
                                <?php if ($authorPageEnabled)
                                { ?>
                                </a>
                            <?php } ?>
                            <?php if ($_post->isPublishDateEnabled())
                            { ?>
                                <div class="post-item-date text-whizzy-graylighter text-xs">
                                    <span><?= __('Updated on') ?></span>
                                    <span class="value"><?= $escaper->escapeHtml($_post->getPublishDate()) ?></span>
                                </div>
                            <?php } ?>

                            <?php
                            $coAuthors = $_post->getRelatedCoauthors();
                            $coAuthorsCount = count($coAuthors);
                            ?>
                            <?php if ($coAuthorsCount)
                            { ?>
                                <?= $block->escapeHtml(__('and')) ?>
                                <?php $z = 0 ?>
                                <?php foreach ($coAuthors as $coAuthor)
                                { ?>
                                    <?php $z++; ?>
                                    <?php if ($block->authorPageEnabled())
                                    { ?>
                                        <a title="<?= $block->escapeHtml($coAuthor->getTitle()) ?>"
                                            href="<?= $block->escapeUrl($coAuthor->getAuthorUrl()) ?>"><?= $block->escapeHtml($coAuthor->getTitle()) ?></a><?php if ($z != $coAuthorsCount)
                                                    echo ', ' ?>
                                    <?php }
                                    else
                                    { ?>
                                        <?= $block->escapeHtml($coAuthor->getTitle()) ?>
                                        <?php if ($z != $coAuthorsCount)
                                            echo ', ' ?>
                                    <?php } ?>
                                <?php } ?>
                            <?php } ?>
                        </div>
                    </div>
                <?php } ?>
            <?php } ?>
        </div>
    </div>
</li>