<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

/**
 * Blog post list template
 *
 * @var $block \Magefan\Blog\Block\Post\PostList
 */

declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$url = $storeManager->getStore()->getBaseUrl();

/** @var ViewModelRegistry $viewModels */
$themeIcons = $viewModels->require(\MgtWizards\Base\ViewModel\ThemeIcons::class);
$sliderViewModel = $viewModels->require(\Hyva\Theme\ViewModel\Slider::class);
?>

<div class="container mb-6 lg:mb-20">

    <h1 class="font-semibold leading-wide text-3xl lg:text-5xl mb-6 lg:mb-12">
        <?= __('Newsroom') ?>
    </h1>

    <?php $_postCollection = $block->getPostCollection(); ?>
    <?php if ($_postCollection->count()): ?>

        <?php
        $itemsTemplate = 'Magefan_Blog::post/list/blog-slider/slider-item.phtml';
        $sliderTemplate = 'Magefan_Blog::post/list/blog-slider/slider.phtml';
        $items = [];
        ?>
        <?php $iterator = 1; ?>
        <?php foreach ($_postCollection as $_post): ?>
            <?php
            if ($iterator > 3) {
                break;
            }
            ?>
            <div class="relative">
                <?php $items[] = $_post; ?>
            </div>
            <?php $iterator++; ?>
        <?php endforeach; ?>
    <?php endif ?>

    <?= $sliderViewModel->getSliderForItems($itemsTemplate, $items, $sliderTemplate)->setData('max_visible', 3)->toHtml() ?>

</div>