<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Catalog\Block\Product\ProductList\Toolbar;
use Magento\Framework\Escaper;

/** @var Toolbar $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
?>
<div
    class="toolbar-sorter sorter flex items-center col-span-2 sm:col-span-5 lg:col-span-6 justify-end flex-1 lg:flex-none">
    <div class="inline-flex items-center gap-x-2 lg:gap-x-4 w-full flex-1 lg:flex-none">
        <div class="hidden lg:block text-base text-whizzy-body font-medium">
            <?= __('Sort by') ?>
        </div>
        <select data-role="sorter"
            class="form-select sorter-options border border-whizzy-separator focus:ring-0 text-sm lg:text-base w-full lg:w-auto"
            aria-label="<?= $escaper->escapeHtmlAttr(__('Sort By')) ?>" @change="changeUrl(
                    'product_list_order',
                    $event.currentTarget.options[$event.currentTarget.selectedIndex].value,
                    options.orderDefault
                )">
            <?php foreach ($block->getAvailableOrders() as $orderCode => $orderLabel): ?>
                <option value="<?= $escaper->escapeHtmlAttr($orderCode) ?>" <?php if ($block->isOrderCurrent($orderCode)): ?>selected="selected" <?php endif; ?>>
                    <?= $escaper->escapeHtml(__($orderLabel)) ?>
                </option>
            <?php endforeach; ?>
        </select>
        <?php if ($block->getCurrentDirection() == 'desc'): ?>
            <a title="<?= $escaper->escapeHtmlAttr(__('Set Ascending Direction')) ?>" href="#"
                class="action sorter-action sort-desc"
                @click.prevent="changeUrl('product_list_dir', 'asc', options.directionDefault)">
                <?= $heroicons->sortAscendingHtml('text-whizzy-body lg:w-6 lg:h-6', 20, 20); ?>
            </a>
        <?php else: ?>
            <a title="<?= $escaper->escapeHtmlAttr(__('Set Descending Direction')) ?>" href="#"
                class="action sorter-action sort-asc"
                @click.prevent="changeUrl('product_list_dir', 'desc', options.directionDefault)">
                <?= $heroicons->sortDescendingHtml('text-whizzy-body lg:w-6 lg:h-6', 20, 20); ?>
            </a>
        <?php endif; ?>
    </div>
</div>