<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
?>
<?php
/**
 * Blog latest posts by category template
 *
 * @var $block \Magefan\BlogExtra\Block\Post\View\CategoryPosts
 */
?>

<?php if ($block->displayPosts()) { ?>
    <?php $postCollection = $block->getPostCollection(); ?>
    <?php if (count($postCollection)) { ?>
        <div class="block related modern my-10">
            <div class="block-title title flex flex-col items-center md:flex-row">
                <strong id="block-relatedposts-heading" class="text-xl lg:text-2xl mb-4 lg:mb-6" role="heading" aria-level="2">
                    <?= $block->escapeHtml(__('Latest From %1', $block->getCategory()->getTitle())) ?>
                </strong>
            </div>
            <ol class="block-content pl-5 list-decimal">
                <?php foreach ($postCollection as $post) { ?>
                    <li class="item mb-2">
                        <a class="post-item-link text-whizzy-body hover:text-whizzy-graylighter transition-all duration-200"
                            title="<?= $block->escapeHtml($post->getTitle()) ?>"
                            href="<?= $block->escapeUrl($post->getPostUrl()) ?>">
                            <?= $block->escapeHtml($post->getTitle()) ?>
                        </a>
                    </li>
                <?php } ?>
            </ol>
        </div>
    <?php } ?>
<?php } ?>