<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$url = $storeManager->getStore()->getBaseUrl();

/** @var ViewModelRegistry $viewModels */
$themeIcons = $viewModels->require(\MgtWizards\Base\ViewModel\ThemeIcons::class);
$whizzyHelper = $this->helper('ShopWhizzy\DigitalTheme\Helper\Data');

//config is set to manage home via CONTENT/PAGES
?>