<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\ReCaptcha;
use Magento\Framework\Escaper;
use Magento\Newsletter\Block\Subscribe;

/** @var Subscribe $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var ReCaptcha $recaptcha */
/** @var HeroiconsOutline $heroicons */

$heroicons = $viewModels->require(HeroiconsOutline::class);

// Do not replace this with $viewModels->require(ReCaptcha::class); that might break the dependency
// on the Magento_ReCaptchaNewsletter module
$recaptcha = $block->getData('viewModelRecaptcha');

// Whizzy Helper
$whizzyHelper = $this->helper('ShopWhizzy\DigitalTheme\Helper\Data');
$footer_layout = $whizzyHelper->getConfigValue('footer/footer_layout');
if ($footer_layout === 'footer_2')
{
    $alignclasses = 'text-center';
}
else
{
    $alignclasses = 'text-start';
}
$footer_newsletter_title = (($whizzyHelper->getConfigValue('footer/footer_newsletter_title')) ? $whizzyHelper->getConfigValue('footer/footer_newsletter_title') : 'Subscribe to Newsletter');
$footer_newsletter_text = $whizzyHelper->getConfigValue('footer/footer_newsletter_text');
?>
<div>
    <form class="form subscribe flex flex-col gap-y-4 w-full m-0 text-whizzy-body"
        action="<?= $escaper->escapeUrl($block->getFormActionUrl()) ?>" method="post" x-data="initNewsletterForm()"
        @submit.prevent="submitForm()" id="newsletter-validate-detail"
        aria-label="<?= $escaper->escapeHtmlAttr(__($footer_newsletter_title)) ?>">
        <div class="<?= $alignclasses ?> flex flex-col gap-y-2">
            <div class="text-xl lg:text-2xl font-bold">
                <span><?= $escaper->escapeHtml(__($footer_newsletter_title)) ?></span>
            </div>
            <?php if ($footer_newsletter_text): ?>
                <div class="text-sm">
                    <?= $escaper->escapeHtml(__($footer_newsletter_text)) ?>
                </div>
            <?php endif; ?>
        </div>
        <div class="w-full">
            <span class="sr-only"><?= $escaper->escapeHtml(__('Email Address')) ?></span>
            <input type="email" id="newsletter-subscribe" name="email"
                class="form-input w-full pl-6 py-3 lg:py-4 shadow-whizzy-header border-0 focus:border-0 focus:ring-0 focus:offset-0 focus:outline-none mb-3"
                required placeholder="<?= $escaper->escapeHtmlAttr(__('Email Address')) ?>">
            <?= $block->getBlockHtml('formkey') ?>
            <?= $recaptcha ? $recaptcha->getInputHtml(ReCaptcha::RECAPTCHA_FORM_ID_NEWSLETTER) : '' ?>
            <button
                class="btn flex justify-center transition-all duration-300 lg:text-base p-2 rounded focus:ring-0 cursor-pointer w-full">
                <?= $escaper->escapeHtml(__('Subscribe')) ?>
            </button>
        </div>
        <template x-if="displayErrorMessage">
            <p class="flex items-center text-red mt-2">
                <?= $heroicons->exclamationCircleHtml('inline-block mr-3'); ?>
                <template x-for="errorMessage in errorMessages">
                    <span x-html="errorMessage"></span>
                </template>
            </p>
        </template>
    </form>
    <div class="w-full">
        <?= $recaptcha ? $recaptcha->getLegalNoticeHtml(ReCaptcha::RECAPTCHA_FORM_ID_NEWSLETTER) : '' ?>
    </div>
    <script>
        function initNewsletterForm() {
            return {
                errors: 0,
                hasCaptchaToken: 0,
                displayErrorMessage: false,
                errorMessages: [],
                setErrorMessages(messages) {
                    this.errorMessages = [messages]
                    this.displayErrorMessage = this.errorMessages.length
                },
                submitForm() {
                    // Do not rename $form, the variable is expected to be declared in the recaptcha output
                    const $form = document.querySelector('#newsletter-validate-detail');
                    <?= $recaptcha ? $recaptcha->getValidationJsHtml(ReCaptcha::RECAPTCHA_FORM_ID_NEWSLETTER) : '' ?>

                    if (this.errors === 0) {
                        $form.submit();
                    }
                }
            }
        }
    </script>
</div>