<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

/**
 * Blog recent posts widget
 *
 * @var $block \Magefan\Blog\Block\Widget\Recent
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Store;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var Store $viewModelStore */
$viewModelStore = $viewModels->require(Store::class);

$themeIcons = $viewModels->require(\MgtWizards\Base\ViewModel\ThemeIcons::class);

$_post = $block->getPostCollection() ?? [];

if (is_object($_post) && $_post instanceof Iterator)
{
    $_post = iterator_to_array($_post);
}
if (!$itemCount = count($_post))
{
    return '';
}
$imageHelper = $this->helper(\Magefan\Blog\Helper\Image::class);
?>
<script>
    'use strict';

    function initSliderComponent() {
        return {
            active: 0,
            itemCount: 0,
            getSlider() {
                return this.$root.querySelector('.js_slides');
            },
            pageSize: 1,
            pageFillers: 0,
            calcPageSize() {
                const slider = this.getSlider();
                if (slider) {
                    this.itemCount = slider.querySelectorAll('.js_slide').length;
                    this.pageSize = Math.round(slider.clientWidth / slider.querySelector('.js_slide').clientWidth);
                    this.pageFillers = (
                        this.pageSize * Math.ceil(this.itemCount / this.pageSize)
                    ) - this.itemCount;
                }
            },
            calcActive() {
                const slider = this.getSlider();
                if (slider) {
                    const slider_post = this.itemCount + this.pageFillers;
                    const calculatedActiveSlide = slider.scrollLeft / (slider.scrollWidth / slider_post);
                    this.active = Math.round(calculatedActiveSlide / this.pageSize) * this.pageSize;
                }
            },
            scrollPrevious() {
                this.scrollTo(this.active - this.pageSize);
            },
            scrollNext() {
                this.scrollTo(this.active + this.pageSize);
            },
            scrollTo(idx) {
                const slider = this.getSlider();
                if (slider) {
                    const slideWidth = slider.scrollWidth / (this.itemCount + this.pageFillers);
                    slider.scrollLeft = Math.floor(slideWidth) * idx;
                    this.active = idx;
                }
            }
        }
    }
</script>
<div class="max-sm:relative <?=
$escaper->escapeHtmlAttr($block->getData('maybe_purged_tailwind_section_classes'))
?: '';
?>" x-data="initSliderComponent()" x-init="calcPageSize();"
    @resize.window.debounce="calcPageSize(); $nextTick( function() { calcActive() })">
    <?php if ($_post): ?>
        <div class="relative">
            <div class="flex-none relative w-full overflow-x-hidden">
                <div class="flex flex-nowrap w-full overflow-auto js_slides snap" @scroll.debounce="calcActive">
                    <?php $total_post = count($_post) ?>
                    <?php $x = 1 ?>
                    <?php foreach ($_post as $_posts)
                    { ?>
                        <?php
                        $_postUrl = $block->escapeUrl($_posts->getPostUrl());
                        $_postName = $block->escapeHtml($_posts->getTitle());

                        $_author = $_posts->getAuthor();
                        $_authorName = $_author->getTitle();
                        $_publishDate = $_posts->getPublishDate();
                        $featuredAuthorImage = $_author->getFeaturedListImage() ?: $_author->getFeaturedImage();

                        $_categoriesCount = $_posts->getCategoriesCount();
                        ?>
                        <div
                            class="flex shrink-0 w-full sm:w-1/2 lg:w-1/4 js_slide w-full shrink-0 px-1 post-holder post-holder-<?= (int)$_posts->getId() ?>">
                            <div class="flex flex-col justify-between w-full h-full">
                                <?php if ($featuredImage = $_posts->getFeaturedImage())
                                { ?>
                                    <?php
                                    $featuredImgAlt = $_posts->getData('featured_img_alt');
                                    if (!$featuredImgAlt)
                                    {
                                        $featuredImgAlt = $_postName;
                                    }
                                    ?>
                                    <div class="relative">
                                        <?php $featuredImage = $imageHelper->init($_posts->getData('featured_img'))->resize(600, null, false); ?>
                                        <div onclick="location.href='<?= /*@noEscape*/ $_postUrl ?>';" class="cursor-pointer">
                                            <div class="h-40 lg:h-[250px] overflow-hidden rounded-t-lg">
                                                <img class="h-full w-full object-cover hover:scale-110 transition-transform duration-300 cursor-pointer"
                                                    src="<?= $escaper->escapeUrl($featuredImage) ?>"
                                                    alt="<?= $escaper->escapeUrl($featuredImgAlt) ?>" />
                                            </div>
                                        </div>
                                        <div class="z-20 absolute top-4 lg:top-6 left-4 lg:left-6">
                                            <div class="item post-categories">
                                                <span class="blog-post-meta-cats flex flex-wrap">
                                                    <?php $n = 0; ?>
                                                    <?php foreach ($_posts->getParentCategories() as $ct)
                                                    { ?>
                                                        <?php $n++; ?>
                                                        <a title="<?= $block->escapeHtml($ct->getTitle()) ?>"
                                                            href="<?= $block->escapeUrl($ct->getCategoryUrl()) ?>"
                                                            class="w-fit tracking-wide transition-all duration-200 bg-whizzy-artic data-[has-current]:bg-whizzy-artic hover:bg-whizzy-separator rounded py-1.5 px-2.5 me-2 cursor-pointer text-xs lg:text-sm font-medium text-whizzy-graylighter hover:text-whizzy-body transition-all duration-200">
                                                            <?= $block->escapeHtml($ct->getTitle()) ?>
                                                        </a>
                                                        <?= /*@noEscape*/ ($n != $_categoriesCount) ? ',' : '' ?>
                                                    <?php } ?>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                <?php } ?>
                                <div class="bg-whizzy-artic py-4 px-6 lg:py-6 lg:px-8 rounded-b-lg h-full flex flex-col justify-center">
                                    <a href="<?= __($_postUrl) ?>" class="mb-4">
                                        <div class="font-semibold leading-wide text-xl lg:text-2xl">
                                            <?= /*@noEscape*/ $_postName ?>
                                        </div>
                                    </a>
                                    <div class="flex flex-row gap-3 items-center">
                                        <div>
                                            <div class="font-semibold">
                                                <?= $block->escapeHtml($_author->getTitle()) ?>
                                            </div>
                                            <div class="text-xs text-whizzy-graylighter">
                                                <span><?= __('Updated on') ?></span>
                                                <span class="value"><?= $escaper->escapeHtml($_posts->getPublishDate()) ?></span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php } ?>
                    <?php $x++ ?>
                    <div :class="{
                        'js_dummy_slide w-full flex-none py-1' : pageFillers > 0
                        }"></div>
                    <div :class="{
                        'js_dummy_slide w-full flex-none py-1' : pageFillers > 1
                        }"></div>
                    <div :class="{
                        'js_dummy_slide w-full flex-none py-1' : pageFillers > 2
                        }"></div>
                    <div :class="{
                        'js_dummy_slide w-full flex-none py-1' : pageFillers > 3
                        }"></div>
                </div>
            </div>
            <template x-if="itemCount > pageSize">
                <div class="flex items-center justify-center" :id="$id('slider-nav')">
                    <button type="button" aria-label="<?= $escaper->escapeHtmlAttr(__('Previous slide')) ?>"
                        :disabled="active === 0"
                        class="bg-white shadow-whizzy-header p-3 lg:p-4 -ml-2 lg:-ml-6 text-black rounded outline-none focus:outline-none absolute top-1/2 left-0 -translate-y-1/2 z-10 opacity-100 cursor-pointer"
                        :class="{ 'opacity-25 pointer-events-none' : active === 0 }" @click="scrollPrevious">
                        <?= $themeIcons->renderHtml('arrow-left', '', 20, 20, ["aria-hidden" => "true"]) ?>
                    </button>

                    <div class="flex flex-wrap w-full md:w-auto justify-center mt-6">
                        <?php for ($i = 0; $i < $itemCount; $i++): ?>
                            <button type="button" :class="{
                                    'hidden': (pageSize !== 1 && !!(<?= (int)$i ?> % pageSize))
                                }" :aria-current="active === <?= (int)$i ?>"
                                :aria-label="hyva.str('<?= $escaper->escapeJs(__('Display slide %1')) ?>', (<?= (int)$i ?> / pageSize) + 1)"
                                @click="scrollTo(<?= (int)$i ?>)">
                                <span
                                    class="flex-shrink-0 block transition-all bg-whizzy-body shrink-0 w-2 h-2 m-1 bg-black bg-opacity-25 rounded-full shadow cursor-pointer"
                                    :class="{
                                    'bg-opacity-100 w-5': active === <?= (int)$i ?>,
                                    'bg-opacity-25 w-2': active !== <?= (int)$i ?>,
                                    'hidden': (pageSize !== 1 && !!(<?= (int)$i ?> % pageSize))
                                }" @click="scrollTo(<?= (int)$i ?>)"></span>
                            </button>
                        <?php endfor; ?>
                    </div>

                    <button type="button" aria-label="<?= $escaper->escapeHtmlAttr(__('Next slide')) ?>"
                        :disabled="active >= itemCount-pageSize"
                        class="bg-white shadow-whizzy-header p-3 lg:p-4 -mr-2 lg:-mr-6 text-black rounded outline-none focus:outline-none absolute top-1/2 right-0 -translate-y-1/2 z-10 opacity-100 cursor-pointer"
                        :class="{ 'opacity-25 pointer-events-none' : active >= itemCount-pageSize }" @click="scrollNext">
                        <?= $themeIcons->renderHtml('arrow-right', '', 20, 20, ["aria-hidden" => "true"]) ?>
                    </button>
                </div>
            </template>
        </div>
    <?php endif; ?>
</div>