<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Magento\Sales\Block\Order\Info\Buttons;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper

/** @var Escaper $escaper */
/** @var Buttons $block */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

$themeIcons = $viewModels->require(\MgtWizards\Base\ViewModel\ThemeIcons::class);

?>
<div
    class="flex flex-col lg:flex-row lg:items-center justify-center md:justify-start flex-wrap gap-4 md:gap-x-6 my-4 md:my-0">
    <?php $order = $block->getOrder() ?>
    <?php if ($this->helper(\Magento\Sales\Helper\Reorder::class)->canReorder($order->getEntityId())): ?>
        <?php $formData = json_decode(
            $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)->getPostData(
                $block->getReorderUrl($order)
            ),
            true
        ) ?>
        <form id="reorder-form" action="<?= $escaper->escapeUrl($formData['action']) ?>" method="post">
            <?= $block->getBlockHtml('formkey'); ?>
            <input type="hidden" name="data" value='<?= /** @noEscape */ json_encode($formData['data']) ?>' />
            <button class="btn btn-primary w-full" type="submit">
                <div class="inline-flex items-center gap-x-3 lg:gap-x-4">
                    <?= $themeIcons->renderHtml('reload', '', 18, 18); ?>
                    <span><?= $escaper->escapeHtml(__('Reorder')) ?></span>
                </div>
            </button>
        </form>
    <?php endif ?>
    <a href="<?= $escaper->escapeUrl($block->getPrintUrl($order)) ?>" class="btn btn-secondary" target="_blank"
        rel="noopener">
        <div class="inline-flex items-center gap-x-3 lg:gap-x-4">
            <?= $themeIcons->renderHtml('printer', '', 18, 18); ?>
            <span><?= $escaper->escapeHtml(__('Print Order')) ?></span>
        </div>
    </a>
    <?= $block->getChildHtml() ?>
</div>