<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Magento\Sales\Block\Order\Info\Buttons;

/** @var Escaper $escaper */
/** @var Buttons $block */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

$themeIcons = $viewModels->require(\MgtWizards\Base\ViewModel\ThemeIcons::class);

?>
<?php $order = $block->getOrder() ?>
<div class="w-fit flex justify-start lg:justify-center">
    <a href="<?= $escaper->escapeUrl($block->getUrl('*/*/printInvoice', ['order_id' => $order->getId()])) ?>"
        class="btn btn-primary h-fit" target="_blank" rel="noopener">
        <div class="inline-flex items-center gap-x-3 lg:gap-x-4">
            <?= $themeIcons->renderHtml('printer', '', 18, 18); ?>
            <span class="mt-0.5"><?= $escaper->escapeHtml(__('Print All Invoices')) ?></span>
        </div>
    </a>
</div>
<?= $block->getChildHtml() ?>