<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Hyva\Theme\ViewModel\BlockJsDependencies;
use Hyva\Theme\ViewModel\ProductCompare;
use Hyva\Theme\ViewModel\ProductListItem;
use Hyva\Theme\ViewModel\ProductPage;
use Hyva\Theme\ViewModel\Wishlist;
use Magento\Catalog\Block\Product\AbstractProduct;
use Magento\Catalog\Helper\Output as CatalogOutputHelper;
use Magento\Catalog\ViewModel\Product\OptionsData as ProductOptionsData;
use Magento\Framework\Escaper;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper
// phpcs:disable Generic.Files.LineLength.TooLong

/** @var AbstractProduct $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var ProductPage $productViewModel */
$productViewModel = $viewModels->require(ProductPage::class);

/** @var ProductListItem $productListItemViewModel */
$productListItemViewModel = $viewModels->require(ProductListItem::class);

/** @var CatalogOutputHelper $catalogOutputHelper */
$catalogOutputHelper = $this->helper(CatalogOutputHelper::class);

/** @var ProductCompare $compareViewModel */
$compareViewModel = $viewModels->require(ProductCompare::class);
/** @var Wishlist $wishlistViewModel */
$wishlistViewModel = $viewModels->require(Wishlist::class);

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

$productOptionsViewmodel = $viewModels->require(ProductOptionsData::class);

/** @var Magento\Catalog\Model\Product $product */
if (!($product = $block->getData('product')))
{
    return;
}
$imageDisplayArea = $block->getData('image_display_area');
$templateType = $block->getData('template_type');
$viewMode = $block->getData('view_mode');
$showDescription = $block->getData('show_description');
$showAddToWishlist = $wishlistViewModel->isEnabled();
$showAddToCompare = $compareViewModel->showInProductList();
$viewIsGrid = $viewMode === 'grid';
$productType = $product->getTypeId();
$isProductGroupedOrBundle = $productType === 'bundle' || $productType === "grouped";
$productId = $product->getId();
$options = $productOptionsViewmodel->getOptionsData($product);

$hideDetails = $block->getData('hide_details') ?: false;
$hideRatingSummary = $block->getData('hide_rating_summary') ?: false;

$imageCustomAttributes = $product->getData('image_custom_attributes')
    ?? $block->getData('image_custom_attributes')
    ?? [];
$productName = $catalogOutputHelper->productAttribute($product, $product->getName(), 'name');
$themeIcons = $viewModels->require(\MgtWizards\Base\ViewModel\ThemeIcons::class);

// Whizzy Helper
$whizzyHelper = $this->helper('ShopWhizzy\DigitalTheme\Helper\Data');
$product_image_background_category_bypass = $whizzyHelper->getConfigValue('general/product_image_background_category_bypass');
$product_image_background = (($whizzyHelper->getConfigValue('general/product_image_background') && !$product_image_background_category_bypass) ? 'bg-whizzy-artic' : '');
$product_image_background_custom = (($product_image_background_custom_value = $whizzyHelper->getConfigValue('general/product_image_background_custom')) ? "style=\"background-color:{$product_image_background_custom_value}\";" : '');
$product_image_background_mixblend = ($whizzyHelper->getConfigValue('general/product_image_background_mixblend') && !$product_image_background_category_bypass ? 'mix-blend-multiply' : '');
$product_image_padding = ($whizzyHelper->getConfigValue('general/product_image_padding') ? 'p-3 lg:p-6' : '');
$product_image_shadow = $whizzyHelper->getConfigValue('general/product_image_shadow');

$is_hot_rated_border = '';
$is_hot_rated = $whizzyHelper->isHotRated($product);
if ($is_hot_rated)
{
    $is_hot_rated_border = 'rounded-lg border-2 border-transparent [background:conic-gradient(from_var(--border-angle),theme(colors.whizzy.primary-lighter)_80%,theme(colors.whizzy.primary)_90%,theme(colors.whizzy.primary-lighter))_border-box] animate-border';
    $hot_rated_label = $whizzyHelper->getConfigValue('products_listing/hot_rated_label') ?: __('Hot Rated');
}
$brand_attribute = $whizzyHelper->getConfigValue('products_listing/brand_attribute');
$product_price_green = ($whizzyHelper->getConfigValue('products_listing/product_price_green') ? 'price-green' : '');
$product_image_gallery = $whizzyHelper->getConfigValue('products_listing/product_image_gallery');
$showDescription = $whizzyHelper->getConfigValue('products_listing/product_show_description');

// Ensure the required JS is rendered on the page
$viewModels->require(BlockJsDependencies::class)->setBlockTemplateDependency($block, 'Magento_Catalog::product/list/js/price-box.phtml');
?>

<?php if ($product->isSaleable()): ?>
    <form method="post"
        action="<?= $escaper->escapeUrl($productViewModel->getAddToCartUrl($product, ['useUencPlaceholder' => true])) ?>"
        class="item item_v2 product product-item bg-white rounded-xl relative group product_addtocart_form flex flex-col w-full h-full overflow-hidden shadow-lg overflow-hidden <?= $viewIsGrid ? '' : 'md:flex-row' ?> <?= $product_price_green ?>"
        <?php if ($product->getOptions()): ?> enctype="multipart/form-data" <?php endif; ?>>
        <?= /** @noEscape */ $block->getBlockHtml('formkey') ?>
        <input type="hidden" name="product" value="<?= (int)$productId ?>" />
        <?php foreach ($options as $optionItem): ?>
            <input type="hidden" name="<?= $escaper->escapeHtml($optionItem['name']) ?>"
                value="<?= $escaper->escapeHtml($optionItem['value']) ?>">
        <?php endforeach; ?>
    <?php else: ?>
        <div
            class="item item_v2 product product-item bg-white rounded-xl relative group flex flex-col w-full h-full overflow-hidden shadow-lg overflow-hidden <?= $viewIsGrid ? '' : 'md:flex-row' ?> <?= $product_price_green ?>">
        <?php endif; ?>
        <div class="relative mb-3 z-20 <?= $is_hot_rated_border ?>">
            <?php /* Product Image */ ?>
            <?php if (!$product_image_gallery): ?>
                <div class="product photo product-item-photo block mx-auto w-full <?= $product_image_background ?> <?= $product_image_padding ?> <?= $viewIsGrid ? '' : 'md:w-2/6 md:mb-0 md:mr-5 md:shrink-0' ?>"
                    tabindex="-1" <?= $product_image_background_custom ?>>
                    <?= $block->getImage($product, $imageDisplayArea)->setTemplate('Magento_Catalog::product/list/image_2.phtml')->setData('custom_attributes', $imageCustomAttributes)->setProductId($productId)->toHtml(); ?>
                    <?php if ($product_image_shadow): ?>
                        <span
                            class="shadow-elem absolute z-10 bg-gradient-to-t from-black to-transparent h-full w-full bottom-0 left-0 opacity-20"></span>
                    <?php endif; ?>
                </div>
            <?php else: ?>
                <div class="block product photo product-item-photo block mx-auto w-full <?= $product_image_background ?> <?= $product_image_padding ?> <?= $viewIsGrid ? '' : 'md:w-2/6 md:mb-0 md:mr-5 md:shrink-0' ?>"
                    tabindex="-1" <?= $product_image_background_custom ?>>
                    <?= $block->getImage($product, $imageDisplayArea)->setTemplate('Magento_Catalog::product/list/image_2.phtml')->setData('custom_attributes', $imageCustomAttributes)->setProductId($productId)->toHtml(); ?>
                    <?php if ($product_image_shadow): ?>
                        <span
                            class="shadow-elem absolute z-10 bg-gradient-to-t from-black to-transparent h-full w-full bottom-0 left-0 opacity-20"></span>
                    <?php endif; ?>
                </div>
            <?php endif; ?>

            <div class="wishlist-elem absolute z-10 top-6 left-6 flex flex-col gap-2">
                <?php if ($showAddToWishlist): ?>
                    <button x-data="initWishlist()" x-defer="intersect"
                        @click.prevent="addToWishlist(<?= (int)$productId ?>)"
                        aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Wish List') . ' ' . $productName) ?>"
                        type="button"
                        class="group btn btn-primary flex justify-center rounded-full bg-whizzy-primary-lighter text-black hover:bg-whizzy-primary hover:text-white p-1 lg:p-2 text-sm w-10 lg:w-12 h-10 lg:h-12 border-0 transition-all duration-300"
                        data-addto="wishlist">
                        <?= $themeIcons->renderHtml('heart', "text-inherit w-5 lg:w-6", 24, 24, ['aria-hidden' => 'true']) ?>
                    </button>
                <?php endif; ?>
                <?php if ($showAddToCompare): ?>
                    <button x-data="initCompareOnProductList()" x-defer="intersect"
                        @click.prevent="addToCompare(<?= (int)$productId ?>)"
                        aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Compare') . ' ' . $productName) ?>"
                        type="button"
                        class="group btn btn-primary flex justify-center rounded-full bg-whizzy-primary-lighter text-black hover:bg-whizzy-primary hover:text-white p-1 lg:p-2 text-sm w-10 lg:w-12 h-10 lg:h-12 border-0 transition-all duration-300"
                        data-addto="compare">
                        <?= $themeIcons->renderHtml('compare', "text-inherit w-5 lg:w-6", 24, 24, ['aria-hidden' => 'true']) ?>
                    </button>
                <?php endif; ?>
                <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                    <?= $addToBlock->setProduct($product)->getChildHtml() ?>
                <?php endif; ?>
            </div>

            <?php if ($is_hot_rated): ?>
                <div class="absolute right-3 bottom-3 flex flex-nowrap gap-2 items-center">
                    <div
                        class="flex gap-1 items-center rounded-full px-3 py-1 text-sm font-semibold bg-whizzy-primary text-white">
                        <span><?= $escaper->escapeHtmlAttr($hot_rated_label) ?></span>
                    </div>
                </div>
            <?php endif; ?>
        </div>

        <div class="product-info flex flex-col grow px-6 pb-6">
            <?php if ($brand_attribute): ?>
                <div class="text-xs text-gray-500 uppercase">
                    <?= $product->getAttributeText($brand_attribute) ?>
                </div>
            <?php endif; ?>
            <div class="name-elem mt-2 mb-1 items-center font-semibold text-md lg:text-base tracking-tight text-left">
                <a class="product-item-link" href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>"
                    :id="`slide-desc-<?= $escaper->escapeHtmlAttr($product->getId()) ?>-${$id('slider-id')}`">
                    <?= /* @noEscape */ $productName ?>
                </a>
            </div>

            <?php if ($showDescription): ?>
                <div class="mt-2 mb-1 text-sm text-gray-500 line-clamp-3">
                    <?= /* @noEscape */ $productViewModel->getShortDescriptionForProduct($product) ?>
                </div>
            <?php endif; ?>

            <?php if ($isProductGroupedOrBundle): ?>
                <span class="sr-only">
                    <?= $escaper->escapeHtml(__('The price depends on the options chosen on the product page')) ?>
                </span>
            <?php endif; ?>

            <div class="flex flex-col lg:flex-row gap-2 lg:gap-0 justify-between items-start lg:mt-2">
                <div>
                    <div class="price-elem" x-data="initPriceBox()" x-defer="intersect"
                        @update-prices-<?= (int)$productId ?>.window="updatePrice($event.detail);">
                        <?= /* @noEscape */ $productListItemViewModel->getProductPriceHtml($product) ?>
                    </div>
                </div>
                <?php if (!$hideRatingSummary): ?>
                    <div>
                        <?= $block->getReviewsSummaryHtml($product, 'short') ?>
                    </div>
                <?php endif; ?>
            </div>

            <?php if ($product->isAvailable() && !$hideDetails): ?>
                <?= $block->getProductDetailsHtml($product) ?>
            <?php endif; ?>
        </div>
        <?php if ($product->isSaleable()): ?>
            <div class="cart-elem w-full <?= $viewIsGrid ? '' : 'md:justify-center' ?>">
                <button
                    class="btn btn-primary add-to-cart flex justify-between rounded-none bg-whizzy-primary hover:bg-whizzy-primary-darker px-4 lg:px-6 py-2 lg:py-3 w-full border-0 opacity-100 lg:opacity-0 group-hover:opacity-100 transition-all duration-300 relative text-sm lg:text-base"
                    title="<?= $escaper->escapeHtmlAttr(__('Add to Cart') . ' ' . $productName) ?>"
                    aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Cart') . ' ' . $productName) ?>" data-addto="cart">
                    <span>
                        <?= $escaper->escapeHtml(__('Add to Cart')) ?>
                    </span>
                    <?= $themeIcons->renderHtml('cart', 'text-white w-5', 20, 20, ['aria-hidden' => 'true']) ?>
                </button>
            </div>
        <?php else: ?>
            <div class="cart-elem w-full <?= $viewIsGrid ? '' : 'md:justify-center' ?>">
                <div class="btn btn-primary flex justify-between rounded-none text-yellow-800 bg-yellow-500 hover:text-yellow-800 hover:bg-yellow-500 px-4 lg:px-6 py-2 lg:py-3 w-full border-0 opacity-100 lg:opacity-0 group-hover:opacity-100 transition-all duration-300 relative text-sm lg:text-base"
                    title="<?= $escaper->escapeHtmlAttr(__('Out of stock')) ?>"
                    aria-label="<?= $escaper->escapeHtmlAttr(__('Out of stock')) ?>">
                    <span>
                        <?= $block->getChildBlock('stockstatus')->setData('product', $product)->toHtml() ?>
                    </span>
                    <?= $themeIcons->renderHtml('alert', 'text-yellow-800 w-5', 20, 20, ['aria-hidden' => 'true']) ?>
                </div>
            </div>
        <?php endif; ?>
        <?php if ($product->isSaleable()): ?>
    </form>
<?php else: ?>
    </div>
<?php endif; ?>