<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package FAQ and Product Questions Hyva
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Amasty\Faq\Block\Forms\AskQuestion;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\GraphqlViewModel\ViewModel\GraphqlViewModel;
use Amasty\FaqHyva\ViewModel\GraphQlQueries;
use Amasty\FaqHyva\ViewModel\QuestionsConfig;
use Hyva\Theme\ViewModel\Store as StoreViewModel;
use Amasty\InvisibleCaptcha\ViewModel\Captcha;

/** @var AskQuestion $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var GraphqlViewModel $viewModelGraphQl */
$viewModelGraphQl = $viewModels->require(GraphqlViewModel::class);

/** @var GraphQlQueries $viewModelQueries */
$viewModelQueries = $viewModels->require(GraphQlQueries::class);

/** @var StoreViewModel $viewModelStore */
$viewModelStore = $viewModels->require(StoreViewModel::class);

/** @var QuestionsConfig $viewModelQuestions */
$viewModelQuestions = $viewModels->require(QuestionsConfig::class);

/** @var Captcha $viewModelCaptcha */
$viewModelCaptcha = $viewModels->require(Captcha::class);

$uniqueId = uniqid();
$additionalField = $block->getAdditionalField();
$validationLabel = 'Please enter a valid email address (Ex: johndoe@domain.com)';
// phpcs:disable Generic.Files.LineLength.TooLong
?>
<form class="ask-question-form widget" id="amfaq-ask-form-inline"
    action="<?= $escaper->escapeUrl($block->getUrlAction()) ?>" method="post"
    x-data="faqQuestionsForm_<?= $escaper->escapeHtml($uniqueId) ?>()" x-init="initQuestionsForm()"
    @submit.prevent.stop="submitQuestionForm()" @amrecaptcha-callback.window="getCaptchaToken($el)"
    @private-content-loaded.window="receiveCustomerData($event.detail.data)">
    <template x-if="!isShowForm && formSettings">
        <div class="button-container">
            <div class="button-info">
                <?= $escaper->escapeHtml(__('Please, mind that only logged in users can submit questions')) ?>
            </div>
        </div>
    </template>
    <template x-if="isShowForm && formSettings">
        <div class="button-container flex items-center mt-3">
            <p class="button-info mr-4 text-base">
                <?= $escaper->escapeHtml(__('Did you find what you were looking for?')) ?>
            </p>
            <button type="button" title="<?= $escaper->escapeHtml(__('Ask a Question')) ?>"
                class="form-toggle-button action btn" @click="toggleFaqForm()" x-ref="formToggle">
                <span x-text="formBtnText"></span>
                <template x-if="isFormActive">
                    <span class="sr-only"> <?= $escaper->escapeHtml(__('Go to the form below')) ?></span>
                </template>
            </button>
        </div>
    </template>

    <div class="ask-form-container" x-show="isFormActive">
        <div class="fieldset">
            <input type="hidden" name="form_key" :value="formKey">
            <template x-if="additionalField">
                <input type="hidden" :name="additionalField.field" :value="additionalField.value">
            </template>
            <div class="field required mb-4">
                <label class="label" for="amfaq-title">
                    <?= $escaper->escapeHtml(__('Your question:')) ?>
                </label>
                <div class="control">
                    <textarea name="title" id="amfaq-title" title="<?= $escaper->escapeHtml(__('Question')) ?>"
                        class="form-input w-full" cols="5" rows="3" required x-model="userQuestion"
                        placeholder="<?= $escaper->escapeHtml(__('Type your question here...')) ?>"></textarea>
                </div>
            </div>
            <template x-if="formSettings && formSettings.isEnableGdprConsent">
                <div class="field required choice flex items-center mb-4 am-gdpr">
                    <input type="checkbox" class="checkbox" name="gdpr" id="amfaq-gdpr"
                        title="<?= $escaper->escapeHtml(__('GDPR')) ?>" x-model="isNameFieldEnabled" required value="1">
                    <label class="label" for="amfaq-gdpr" x-html="formSettings.gdprConsentText"></label>
                </div>
            </template>
            <template x-if="isNameFieldEnabled || (formSettings && !formSettings.isEnableGdprConsent)">
                <div class="field mb-4">
                    <label class="label" for="amfaq-name">
                        <?= $escaper->escapeHtml(__('Your name:')) ?>
                    </label>
                    <div class="control">
                        <input name="name" id="amfaq-name" class="form-input w-full"
                            title="<?= $escaper->escapeHtml(__('Name')) ?>" x-model="userName" type="text">
                    </div>
                </div>
            </template>
            <template x-if="isNotifyUser">
                <div class="notify-user mb-4">
                    <template x-if="isNameFieldEnabled || (formSettings && !formSettings.isEnableGdprConsent)">
                        <div class="fields-wrapper mb-4">
                            <div class="field flex items-center choice mb-4">
                                <input type="checkbox" class="checkbox" name="notification" id="amfaq-notification"
                                    title="<?= $escaper->escapeHtml(__('Notification')) ?>"
                                    x-model="isEmailFieldEnabled" value="1">
                                <label class="label" for="amfaq-notification">
                                    <?= $escaper->escapeHtml(__('get notification on email when the answer is ready')) ?>
                                </label>
                            </div>
                            <?= /* @noEscape */
                            $block->getGdprCheckboxes() ?>
                        </div>
                    </template>
                    <template x-if="(isEmailFieldEnabled && isNameFieldEnabled)
                                        || (formSettings && !formSettings.isEnableGdprConsent && isEmailFieldEnabled)">
                        <div class="field email-field required">
                            <label class="label required" for="amfaq-email">
                                <?= $escaper->escapeHtml(__('Your e-mail:')) ?>
                            </label>
                            <div class="control">
                                <input name="email" id="amfaq-email" class="form-input w-full"
                                    title="<?= $escaper->escapeHtml(__('Email')) ?>"
                                    @input="validateForm($event.target)" x-model="userEmail" type="email" required>
                            </div>
                        </div>
                    </template>
                </div>
            </template>
            <div class="submit-wrapper relative inline-flex">
                <button type="submit" class="btn btn-primary">
                    <?= $escaper->escapeHtml(__('Send the Question')) ?>
                </button>
                <?= /** @noEscape */ $block->fetchView($block->getTemplateFile('Hyva_Theme::ui/loading-block.phtml')) ?>
            </div>
        </div>
    </div>
</form>
<script>
    function faqQuestionsForm_<?= $escaper->escapeHtml($uniqueId) ?>() {
        const fieldCategory = 'category_ids';
        const fieldProduct = 'product_ids';
        return {
            isLoading: false,
            isLoggedIn: false,
            isShowForm: false,
            isFormActive: false,
            formSettings: null,
            isNotifyUser: <?= $block->isNotifyUser() ? 'true' : 'false' ?>,
            showFormBtnText: '<?= $escaper->escapeJs(__('Ask a Question')) ?>',
            hideFormBtnText: '<?= $escaper->escapeJs(__('Hide form')) ?>',
            additionalField: <?= /** @noEscape */ json_encode($additionalField) ?>,
            formBtnText: '',
                isNameFieldEnabled: false,
                    isEmailFieldEnabled: false,
                        formKey: hyva.getFormKey(),
                            userQuestion: '',
                                userName: '',
                                    userEmail: '',
                                        getCaptchaEnabled: <?= $viewModelQuestions->getCaptchaEnabled() ? 'true' : 'false' ?>,
                                            isFaqFormToProtect: false,
                                                gcaptchaToken: '',
                                                    allowedCaptchaForm: '<?= $escaper->escapeJs(implode(',', $viewModelCaptcha->getAllFormSelectors())) ?>',
                                                        verifyUrl: '<?= $escaper->escapeJs($viewModelQuestions->getVerifyUrl()) ?>',
                                                            isFormReadyToSubmit: false,
                                                                isFormVerifiedByCaptcha: true,
                                                                    validateEmailsRegex: /^([a-z0-9,!\#\$%&'\*\+\/=\?\^_`\{\|\}~-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z0-9,!\#\$%&'\*\+\/=\?\^_`\{\|\}~-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*@([a-z0-9-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z0-9-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*\.(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]){2,})$/i,
                                                                        queries: {
            getAmFaqSettings: <?= /** @noEscape */ json_encode(
            $viewModelGraphQl->query(
            'am_get_faq_settings',
            'query getAmFaqSettings {'
            . $viewModelQueries->getAmFaqSettings() .
            '}'
            )
            ) //phpcs:ignore ?>,
            placeAmFaqQuestion: <?= /** @noEscape */ json_encode(
            $viewModelGraphQl->query(
            'am_place_faq_question',
            'mutation placeAmFaqQuestion($title: String!, $name: String, $email: String, $product_id: Int, $category_id: Int) {'
            . $viewModelQueries->getPlaceAmFaqQuestion() .
            '}'
            )
            ) //phpcs:ignore ?>,
        },

        initQuestionsForm() {
            this.formBtnText = this.showFormBtnText;

            this._checkIsAllowCaptcha();
            this._listeners();
        },

        <?php /** Listeners for component actions (submit form, etc.) */ ?>
        _listeners() {
            <?php /* Submit form in case from allowed to submit */ ?>
            this.$watch('isFormReadyToSubmit', (isReady) => {
                if (isReady) {
                    this._placeQuestion();
                }
                this.isFormReadyToSubmit = false;
            })
        },

        toggleFaqForm: function () {
            this.isFormActive = !this.isFormActive;
            this.formBtnText = this.isFormActive ? this.hideFormBtnText : this.showFormBtnText;
        },

        receiveCustomerData(data) {
            this.isLoggedIn = !!(data.customer && data?.customer?.firstname);
            this._getAmFaqSettingsData();

            const faqData = data.faq;

            if (faqData && faqData.name) {
                this.userName = faqData.name;
                this.userEmail = faqData.email;
            }
        },

        <?php /** Form submit */ ?>
        submitQuestionForm() {
            <?php /* Captcha verifiaction and set flags for submit */ ?>
            if (this.getCaptchaEnabled && this.isFaqFormToProtect && this.gcaptchaToken) {
                this._verifyGrecaptcha(this.gcaptchaToken);
            } else {
                this.isFormReadyToSubmit = true;
            }
        },

        getCaptchaToken(form) {
            const tokenField = form.querySelector('.g-recaptcha-response');
            this.gcaptchaToken = tokenField ? tokenField.value : '';
        },

        validateForm(input) {
            const emails = input.value.split(/[\s\n\,]+/g);

            for (let i = 0; i < emails.length; i++) {
                if (!this.validateEmailsRegex.test(emails[i].trim())) {
                    this.isValid = false;
                    input.setCustomValidity('<?= $escaper->escapeJs(__($validationLabel)) ?>');
                    return false;
                }
            }
            this.isValid = true;
            input.setCustomValidity('');
            return true;
        },

        closeAndClearForm() {
            this.userQuestion = '';
            this.isFormActive = false;
            this.isNameFieldEnabled = false;
            this.isEmailFieldEnabled = false;
            this.formBtnText = this.showFormBtnText;
        },

        _checkIsAllowCaptcha() {
            const faqFormSelector = 'form[action*="faq/index/save"]';
            Array.from(this.allowedCaptchaForm.split(',')).forEach(formSelector => {
                if (formSelector === faqFormSelector) {
                    this.isFaqFormToProtect = true;
                }
            })
        },

        <?php /** Send graphQL mutation for place question */ ?>
        _placeQuestion() {
            const data = this._prepareMutationData();
            this.isLoading = true;
            this._useQuery(
                this.queries.placeAmFaqQuestion, data
            ).then(result => {
                /* show errros */
                if (result?.errors) {
                    console.error(result);
                    result.errors.map(error => {
                        this._showMessage(error.message, 'error', 5000);
                    });
                    return result;
                }
                /* get data */
                const message = result?.data?.placeAmFaqQuestion?.message;
                const messageType = result?.data?.placeAmFaqQuestion?.error ? 'error' : 'success';
                this._showMessage(message, messageType, 10000);
                this.closeAndClearForm();
            }).finally(() => {
                this.isLoading = false;
                this.$nextTick(() => {
                    this.$refs.formToggle.focus();
                })
            });
        },

        <?php /** Amasty invisible verfication */ ?>
        _verifyGrecaptcha(token) {
            let url = this.verifyUrl;
            let requestData = '?token=' + token;
            fetch(url + requestData, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-Requested-With': 'XMLHttpRequest'
                },
            })
                .then(response => response.json())
                .then(result => {
                    if (result?.success) {
                        if (result?.verification?.success) {
                            this.isFormReadyToSubmit = true;
                        } else {
                            this._showMessage(result?.verification?.error, 'error', 10000)
                            this.isFormReadyToSubmit = false;
                        }
                    } else {
                        console.error(result.error_message);
                        this._showMessage(result.error_message, 'error', 4000)
                    }
                })
        },

        _showMessage(message, type, delay) {
            dispatchMessages([{
                type: type,
                text: message
            }], delay);
        },

        _prepareMutationData() {
            let data = {
                title: this.userQuestion,
                name: this.userName,
                email: this.isEmailFieldEnabled ? this.userEmail : ''
            }
            switch (this.additionalField.field) {
                case fieldCategory:
                    data['category_id'] = parseInt(this.additionalField.value);
                    break;
                case fieldProduct:
                    data['product_id'] = parseInt(this.additionalField.value);
                    break;
            }
            return data;
        },

        _getAmFaqSettingsData() {
            this._useQuery(
                this.queries.getAmFaqSettings
            ).then(result => {
                if (result?.errors) {
                    console.error(result);
                    result.errors.map(error => {
                        this._showMessage(error.message, 'error', 5000);
                    });
                    return result;
                }
                this.formSettings = result?.data?.getAmFaqSettings;

                this.isShowForm = !(!this.formSettings.isGuestQuestionsAllowed && !this.isLoggedIn);
            });
        },

        _useQuery(query, variables) {
            return fetch(BASE_URL + "graphql", {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Store': '<?= /* @noEscape */ $viewModelStore->getStoreCode() ?>'
                },
                credentials: 'include',
                body: JSON.stringify({ query: query, variables: variables }),
            }).then(response => response.json()).catch(() => {
                this._showMessage('<?= $escaper->escapeHtml(__("Something went wrong. Please try again later.")) ?>', 'error', 5000);
            })
        }
    }
    }
</script>