<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Checkout\Block\Cart;
use Magento\Framework\Escaper;

/** @var Cart $block */
/** @var Escaper $escaper */
?>

<div class="w-full inline-block">
    <h1 class="font-semibold leading-wide text-3xl lg:text-5xl mt-6 lg:mt-10 mb-8 lg:mb-16">
        <?= __('Shopping Cart') ?>
    </h1>
    <div class="w-full lg:w-1/3 float-left lg:float-right lg:order-2 top-0 lg:sticky lg:top-6 lg:pl-8 mb-6">
        <div class="border border-whizzy-body rounded-md p-6 lg:p-8 text-sm lg:text-base">
            <?= $block->getChildHtml('cart.summary') ?>
        </div>
    </div>
    <div class="w-full lg:w-2/3 float-left lg:order-1">
        <?= $block->getChildHtml('form_before') ?>
        <?= $block->getChildHtml('cart-items') ?>
        <?= $block->getChildHtml('checkout_cart_widget') ?>
    </div>
    <div class="w-full lg:w-3/4">
        <?= $block->getChildHtml('cart.discount') ?>
    </div>
</div>