<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
?>
<?php
/**
 * Blog tag claud sidebar template
 *
 * @var $block \Magefan\Blog\Block\Sidebar\TagClaud
 */
?>
<?php $tags = $block->getTags(); ?>

<?php if (count($tags))
{ ?>
    <div class="block-tagclaud mb-2">
        <div class="title text-xs uppercase font-bold tracking-wider my-6 lg:mt-8 lg:mb-6">
            <?= $block->escapeHtml(__('Tags')) ?>
        </div>

        <div class="tagclaud-hld card">
            <?php foreach ($tags as $tag)
            { ?>
                <?php $title = $tag->getTitle() ?>
                <span class="<?= $escaper->escapeHtml($block->getTagClass($tag)) ?>">
                    <a href="<?= $escaper->escapeUrl($tag->getTagUrl()) ?>" class="hover:text-whizzy-primary duration-300"
                        title="<?= $escaper->escapeHtml($title) ?>">
                        <?= $escaper->escapeHtml($title) ?>
                    </a>
                </span>
            <?php } ?>
        </div>
        <div class="mt-4 lg:mt-6 h-px bg-whizzy-separator"></div>
    </div>
<?php } ?>