<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Magento\LayeredNavigation\Block\Navigation;

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var Navigation $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
$themeIcons = $viewModels->require(\MgtWizards\Base\ViewModel\ThemeIcons::class);
?>
<?php if ($block->canShowBlock()): ?>
    <div class="layered-navigation-wrapper" x-data="initLayeredNavigation()" x-init="checkIsMobileResolution()"
        @resize.window.debounce="checkIsMobileResolution()" @visibilitychange.window.debounce="checkIsMobileResolution()"
        role="region" aria-label="<?= $escaper->escapeHtmlAttr(__('Product filters')) ?>">
        <div id="filters-heading" class="block-title">
            <button type="button" @click="blockOpen = !blockOpen"
                class="btn btn-secondary gap-2 px-6 py-3 justify-between w-full text-start text-base font-medium md:p-0 border lg:border-0 border-whizzy-separator md:!bg-transparent md:!text-current shadow-whizzy-header"
                aria-controls="filters-content" :aria-expanded="blockOpen" :aria-disabled="!isMobile"
                :disabled="!isMobile ? '' : null">
                <span class="md:!hidden"><?= $escaper->escapeHtml(__('Shop By')) ?></span>

                <span class="md:hidden" x-ref="LayeredNavigationMobileToggleIcon">
                    <?= $themeIcons->renderHtml('settings', 'transition-transform transform duration-300 ease-in-out', 24, 24, [":class" => "{ 'rotate-180': blockOpen }", "aria-hidden" => "true", "focusable" => "false"]) ?>
                </span>
            </button>
        </div>
        <?php
        $filters = array_filter($block->getFilters(), function ($filter)
        {
            // Exclude Mirasvit SearchFilter
            if ($filter instanceof \Mirasvit\Search\Model\Layer\Filter\SearchFilter)
            {
                return false;
            }

            // Keep only filters that actually have items
            return method_exists($filter, 'getItemsCount') && $filter->getItemsCount();
        });
        ?>
        <?php $contentclasses = count($filters)
        ? 'md:block rounded-md shadow-whizzy-header border-0 text-whizzy-body pt-4 p-6'
        : '' ?>
        <div id="filters-content" class="block-content filter-content hidden <?= $contentclasses ?>"
            :class="{ 'hidden': !blockOpen }">
            <?= $block->getChildHtml('state') ?>
            <a href="#product-list"
                class="sr-only focus:not-sr-only bg-blue-600 text-white px-12 py-4 text-center block rounded-sm">
                <?= $escaper->escapeHtml(__('Skip to product list')) ?>
            </a>
            <?php foreach ($block->getFilters() as $filter): ?>
                <?php if ($filter->getItemsCount()): ?>
                    <div x-data="{
                            open: false,
                            id: $id('filter-option')
                        }" x-defer="intersect"
                        class="filter-option group py-2 border-b border-whizzy-separator last:border-b-0">
                        <div :id="`${id}-title`">
                            <button type="button" @click="open = !open"
                                class="filter-options-title [&::-webkit-details-marker]:hidden py-2 flex justify-between items-center font-semibold text-xl text-left tracking-tight cursor-pointer w-full"
                                :aria-controls="`${id}-content`" :aria-expanded="open">
                                <span class="title">
                                    <?= $escaper->escapeHtml(__($filter->getName())) ?>
                                    <span class="sr-only"> <?= $escaper->escapeHtml(__('filter')) ?></span>
                                </span>
                                <span class="text-whizzy-body">
                                    <?= $heroicons->chevronDownHtml('transition-transform transform duration-300 ease-in-out', 24, 24, [":class" => "{ 'rotate-180': open }", "aria-hidden" => "true", "focusable" => "false"]); ?>
                                </span>
                            </button>
                        </div>
                        <template x-if="open">
                            <div :id="`${id}-content`" class="filter-options-content py-2">
                                <?= /* @noEscape */ $block->getChildBlock('renderer')->setFilterTitle($filter->getName())->render($filter); ?>
                            </div>
                        </template>
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>
    </div>
    <script>
        function initLayeredNavigation() {
            return {
                isMobile: false,
                blockOpen: false,
                checkIsMobileResolution() {
                    const mobileElement = this.$refs.LayeredNavigationMobileToggleIcon;
                    this.isMobile = mobileElement
                        ? getComputedStyle(mobileElement).display !== "none"
                        : window.matchMedia('(max-width: 767px)').matches; // Fallback to `md` breakpoint
                }
            }
        }
    </script>
<?php endif; ?>