<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Magezon\Builder\Block\Element;
/** @var $block Element */

$coreHelper = $this->helper('\Magezon\Core\Helper\Data');
$element = $this->getElement();
$title = $coreHelper->filter($element->getData('title'));
$titleAlign = $element->getData('title_align');
$titleTag = $element->getData('title_tag') ? $element->getData('title_tag') : 'h2';
$headingSize = trim($titleTag, 'h');
if ($headingSize < 5) {
    $size = 6 - $headingSize.'xl';
} elseif ($headingSize == 5) {
    $size = 'xl';
} else {
    $size = 'base';
}
$description = $coreHelper->filter($element->getData('description'));
$showLine = $element->getData('show_line');
$linePosition = $element->getData('line_position');
$items = $this->toObjectArray($element->getItems());
$htmlId = $element->getHtmlId();
$carouselOptions = $this->getOwlCarouselOptions();
$classes = $this->getOwlCarouselClasses();
?>
<?php if (count($items)) { ?>
<div class="mgz-block">
	<?php if ($title || $description) { ?>
	<div class="mgz-block-heading mgz-block-heading-align-<?= $titleAlign ?><?= $showLine ? ' mgz-block-heading-line' : '' ?> mgz-block-heading-line-position-<?= $linePosition ?>">
		<?php if ($title) { ?>
			<<?= $titleTag ?> class="inline-block relative mb-2 mt-0 text-<?= $size ?> font-medium leading-tight text-primary" style="padding: 0 10px; background: #fafafa"><?= $title ?></<?= $titleTag ?>>
		<?php } ?>
		<?php if ($description) { ?>
			<div class="info"><?= $description ?></div>
		<?php } ?>
	</div>
	<?php } ?>
	<div class="mgz-block-content">
		<?php if ($items && count($items)) { ?>
			<div class="mgz-carousel content-slider-<?= $element->getId() ?> owl-carousel <?= implode(' ', $classes) ?>">
				<?php foreach ($items as $item) { ?>
					<div class="mgz-content-carouse-slide">
						<?= $coreHelper->filter($item['content']) ?>						
					</div>
				<?php } ?>
			</div>
		<?php } ?>
	</div>
</div>
<?php } ?>

<script>
    loadScript('<?= $block->getViewFileUrl('Hyva_MagezonBuilder::js/jquery.min.js') ?>', 'jquery')
        .then(() => {
            return loadScript('<?= $block->getViewFileUrl('Magezon_Core::js/owl.carousel.min.js') ?>', 'carousel');
        })
        .then(() => {
            return loadScript('<?= $block->getViewFileUrl('Hyva_MagezonBuilder::js/carousel.min.js') ?>', 'content-slider');
        })
        .then(() => {
            $('.content-slider-<?= $element->getId() ?>').carousel(<?= $coreHelper->serialize($carouselOptions) ?>);
        })
</script>
