<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Magento\Framework\App\Action\Action;
use Hyva\Theme\ViewModel\ProductListItem;
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Hyva\Theme\ViewModel\ProductPage;
use Magento\Catalog\ViewModel\Product\OptionsData as ProductOptionsData;
use Magento\Catalog\Helper\Output as CatalogOutputHelper;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Magezon\Builder\Block\Element;

/** @var $block Element */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */
/** @var ProductPage $productViewModel */
/** @var CatalogOutputHelper $catalogOutputHelper */
/** @var HeroiconsOutline $heroicons */
/** @var HeroiconsSolid $heroiconsSolid */

$eagerLoadImagesCount = (int)($block->getData('eager_load_images_count') ?? 3);
$productListItemViewModel = $viewModels->require(ProductListItem::class);
$productViewModel = $viewModels->require(ProductPage::class);
$productOptionsViewmodel = $viewModels->require(ProductOptionsData::class);
$catalogOutputHelper = $this->helper(CatalogOutputHelper::class);
$heroicons = $viewModels->require(HeroiconsOutline::class);
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);
$viewIsGrid = true;
$uniqueId = '_' . uniqid();

$coreHelper = $this->helper('\Magezon\Core\Helper\Data');
$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
$element = $this->getElement();
$title = $coreHelper->filter($element->getData('title'));
$titleColor = $element->getData('title_color');
$titleAlign = $element->getData('title_align');
$titleTag = $element->getData('title_tag') ? $element->getData('title_tag') : 'h2';
$description = $coreHelper->filter($element->getData('description'));
$showLine = $element->getData('show_line');
$linePosition = $element->getData('line_position');
$items = $this->getItems();
if (!$itemCount = count($items))
{
    return '';
}
$sliderViewModel = $viewModels->require(\Hyva\Theme\ViewModel\Slider::class);

// The number of slides visible on the xl breakpoint
$maxVisibleSlides = $block->getData('max_visible') ?? 4;

// Breakpoints for 1 visible slider items on mobile, 2 visible on md, 3 on lg and 4 on xl (see $sliderPageSize).
$defaultSliderItemClasses = 'mr-2 py-1 md:w-1/2 lg:w-1/3 xl:w-1/4';

$sliderSectionClasses = $block->getData('maybe_purged_tailwind_section_classes') ?? 'my-12 text-gray-700 body-font';
$slideItemClasses = $block->getData('maybe_purged_tailwind_slide_item_classes') ?? $defaultSliderItemClasses;

$imageId = 'category_page_grid';
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
$showImage = $element->getData('product_image');
$showName = $element->getData('product_name');
$showPrice = $element->getData('product_price');
$showShortDescription = $element->getData('product_shortdescription');
$showWishlist = $element->getData('product_wishlist');
$showCompare = $element->getData('product_compare');
$showCart = $element->getData('product_addtocart');
$showReview = $element->getData('product_review');
$swatches = $element->getData('product_swatches');
$displayStyle = $element->getData('display_style');
$carouselOptions = $this->getOwlCarouselOptions();
$carouselOptions['item_xl'] = $carouselOptions['item_lg'] = $carouselOptions['item_md'] = $carouselOptions['item_sm'] = $carouselOptions['item_xs'] = 1;
$carouselOptions['dots'] = $element->getData('owl_dots') ? true : false;
$carouselOptions['lazyLoad'] = true;
$lazyLoad = true;
$xl = $element->getData('item_xl');
$lg = $element->getData('item_lg');
$md = $element->getData('item_md');
$sm = $element->getData('item_sm');
$xs = $element->getData('item_xs');
$htmlId = $element->getHtmlId();
?>

<?php if ($displayStyle == 'pagination'): ?>

    <section>
        <?php
        $itemsTemplate = 'Magento_Catalog::product/list/item.phtml';
        $sliderTemplate = 'Magento_Catalog::product/slider/product-slider-container.phtml';
        $slideritems = [];
        foreach ($items as $item)
        {
            foreach ($item as $product)
            {
                $slideritems[] = $product;
            }
        }
        ?>
        <?= $sliderViewModel->getSliderForItems($itemsTemplate, $slideritems, $sliderTemplate)->setData('max_visible', 5)->toHtml(); ?>
    </section>

<?php else: ?>

    <div class="mgz-block">
        <?php if ($title || $description)
        { ?>
            <div
                class="mgz-block-heading mgz-block-heading-align-<?= $titleAlign ?><?= $showLine ? ' mgz-block-heading-line' : '' ?> mgz-block-heading-line-position-<?= $linePosition ?>">
                <?php if ($title)
                { ?>
                    <<?= $titleTag ?> class="title" style="color: <?= $titleColor ?>" ><?= $title ?></<?= $titleTag ?>>
                <?php } ?>
                <?php if ($description)
                { ?>
                    <div class="info"><?= $description ?></div>
                <?php } ?>
            </div>
        <?php } ?>
        <div class="mgz-block-content">
            <div class="products-list-<?= $element->getId() ?>">
                <div
                    class="mx-auto pt-4 pb-12 grid gap-4 grid-cols-<?= $xs ?> sm:grid-cols-<?= $sm ?> md:grid-cols-<?= $md ?> lg:grid-cols-<?= $lg ?> xl:grid-cols-<?= $xl ?>">
                    <?php
                    /** @var \Magento\Catalog\Model\Product $product */
                    foreach ($items as $i => $item): ?>
                        <div
                            class="item product product-item mx-auto pt-4 pb-12 grid gap-4 grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
                            <?php foreach ($item as $product): ?>
                                <?php if ($product->isSaleable()): ?>
                                    <form method="post"
                                        action="<?= $escaper->escapeUrl($productViewModel->getAddToCartUrl($product, ['useUencPlaceholder' => true])) ?>"
                                        class="item product product-item product_addtocart_form card card-interactive flex flex-col w-full <?= $viewIsGrid ? '' : 'md:flex-row' ?>"
                                        <?php if ($product->getOptions()): ?> enctype="multipart/form-data" <?php endif; ?>>
                                        <?= /** @noEscape */ $block->getBlockHtml('formkey') ?>
                                        <input type="hidden" name="product" value="<?= (int)$product->getId() ?>" />
                                        <?php $options = $productOptionsViewmodel->getOptionsData($product); ?>
                                        <?php foreach ($options as $optionItem): ?>
                                            <input type="hidden" name="<?= $escaper->escapeHtml($optionItem['name']) ?>"
                                                value="<?= $escaper->escapeHtml($optionItem['value']) ?>">
                                        <?php endforeach; ?>
                                    <?php else: ?>
                                        <div
                                            class="item product product-item card card-interactive flex flex-col w-full <?= $viewIsGrid ? '' : 'md:flex-row' ?>">
                                        <?php endif; ?>
                                        <?php /* Product Image */ ?>
                                        <a href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>"
                                            class="product photo product-item-photo block mx-auto mb-3 <?= $viewIsGrid ? '' : 'md:w-2/6 md:mb-0 md:mr-5' ?>"
                                            tabindex="-1">
                                            <?= $block->getImage($product, $imageId)->setTemplate('Magento_Catalog::product/list/image.phtml')->setData('custom_attributes', ['loading' => 'eager', 'fetchpriority' => 'high'])->setProductId($product->getId())->toHtml(); ?>
                                        </a>
                                        <div class="product-info flex flex-col grow p-2">
                                            <div
                                                class="mt-2 mb-1 items-center justify-center text-primary font-semibold text-lg text-center <?= $viewIsGrid ? '' : 'md:text-left' ?>">
                                                <?php if ($showName): ?>
                                                    <a class="product-item-link"
                                                        href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>">
                                                        <?= /* @noEscape */ $catalogOutputHelper->productAttribute($product, $product->getName(), 'name') ?>
                                                    </a>
                                                <?php endif; ?>
                                            </div>

                                            <?php if ($showReview): ?>
                                                <div class="py-1 mx-auto <?= $viewIsGrid ? '' : 'md:mx-0 md:w-auto' ?>">
                                                    <?= $block->getReviewsSummaryHtml($product, 'short') ?>
                                                </div>
                                            <?php endif; ?>

                                            <?php if ($product->isAvailable()): ?>
                                                <?= $block->getProductDetailsHtml($product) ?>
                                            <?php endif; ?>

                                            <?php if ($showShortDescription): ?>
                                                <div
                                                    class="mt-2 mb-1 items-center justify-center text-primary text-center <?= $viewIsGrid ? '' : 'md:text-left' ?>">
                                                    <?= /* @noEscape */ $productViewModel->getShortDescriptionForProduct($product) ?>
                                                </div>
                                            <?php endif; ?>

                                            <script>
                                                function initPriceBox_<?= /** @noEscape */ $uniqueId ?>() {
                                                return {
                                                    updatePrice(priceData) {
                                                        const regularPriceLabel = this.$root.querySelector('.normal-price .price-label');
                                                        const regularPriceElement = this.$root.querySelector('.normal-price [data-price-type=finalPrice].price-wrapper .price');
                                                        const basePriceElement = this.$root.querySelector('.normal-price [data-price-type=basePrice].price-wrapper .price');
                                                        if (priceData.finalPrice.amount < priceData.oldPrice.amount) {
                                                            regularPriceLabel.classList.add('hidden');
                                                        } else {
                                                            regularPriceLabel.classList.remove('hidden');
                                                        }
                                                        regularPriceElement && (regularPriceElement.innerText = hyva.formatPrice(priceData.finalPrice.amount));
                                                        basePriceElement && (basePriceElement.innerText = hyva.formatPrice(priceData.basePrice.amount));
                                                    }
                                                }
                                                                                                                                                                                                                                                                                                                                                        }
                                            </script>
                                            <div class="pt-1 text-gray-900" x-data="initPriceBox_<?= /** @noEscape */
                                            $uniqueId ?>()" @update-prices-<?= (int)$product->getId() ?>.window="updatePrice($event.detail);">
                                                <?= /* @noEscape */ $productListItemViewModel->getProductPriceHtml($product) ?>
                                            </div>

                                            <div class="mt-auto pt-3 flex flex-wrap justify-center items-center">
                                                <?php if ($product->isSaleable()): ?>
                                                    <?php if ($showCart): ?>
                                                        <button class="w-auto btn btn-primary justify-center text-sm
                                            <?= $viewIsGrid ? 'mr-auto' : 'mr-auto md:mr-0' ?>"
                                                            aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                            <?= $heroicons->shoppingCartHtml("h-6 w-6 border-current inline", 25, 25) ?>
                                                            <span
                                                                class="ml-2 inline <?= $viewIsGrid ? 'md:ml-0 md:hidden lg:ml-2 lg:inline' : '' ?>">
                                                                <?= $escaper->escapeHtml(__('Add to Cart')) ?>
                                                            </span>
                                                        </button>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                                <?php if ($showWishlist): ?>
                                                    <button x-data="initWishlist()"
                                                        @click.prevent="addToWishlist(<?= (int)$product->getId() ?>)"
                                                        aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Wish List')) ?>"
                                                        type="button"
                                                        class="rounded-full w-9 h-9 bg-gray-200 p-0 border-0 inline-flex shrink-0 items-center justify-center text-gray-500 hover:text-red-600 ml-2">
                                                        <?= $heroiconsSolid->heartHtml("w-5 h-5", 25, 25) ?>
                                                    </button>
                                                <?php endif; ?>
                                                <?php if ($showCompare): ?>
                                                    <button x-data="initCompareOnProductList()"
                                                        @click.prevent="addToCompare(<?= (int)$product->getId() ?>)"
                                                        aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Compare')) ?>" type="button"
                                                        class="rounded-full w-9 h-9 bg-gray-200 p-0 border-0 inline-flex shrink-0 items-center justify-center text-gray-500 hover:text-yellow-500 ml-2">
                                                        <?= $heroicons->scaleHtml("w-5 h-5", 25, 25) ?>
                                                    </button>
                                                <?php endif; ?>
                                                <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                                    <?= $addToBlock->setProduct($product)->getChildHtml() ?>
                                                <?php endif; ?>
                                            </div>
                                        </div>
                                        <?php if ($product->isSaleable()): ?>
                                    </form>
                                <?php else: ?>
                                </div>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
<?php endif; ?>