<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Magezon\Builder\Block\Element;
/** @var $block Element */

$coreHelper = $this->helper('\Magezon\Core\Helper\Data');
$element = $this->getElement();
$toggleTitle = $element->getData('toggle_title');
$toggleContent = $element->getData('toggle_content');
$icon = $element->getData('icon');
$activeIcon = $element->getData('active_icon');
$iconStyle = $element->getData('icon_style');
$iconSize = $element->getData('icon_size');
$open = $element->getData('open');
if ($iconStyle =='text_only') $icon = $activeIcon = '';
?>
<div class="mgz-toggle <?= $open ? 'active-default' : '' ?> mgz-toggle-<?= $element->getId() ?> <?= $icon ?
    'mgz-toggle-icon' : '' ?> mgz-toggle-icon-<?= $iconStyle ?> mgz-toggle-<?= $element->getId() ?> mgz-toggle-icon-size-<?= $iconSize ?>">
    <?php if ($toggleTitle) { ?>
        <div class="mgz-toggle-title" data-role="title">
            <span data-icon="<?= $icon ?>" data-icon-active="<?= $activeIcon ?>" class="icon" data-role="icons"></span>
            <h4 data-role="trigger" class="mb-2 mt-0 font-bold leading-tight text-primary">
                <span><?= $toggleTitle ?></span>
            </h4>
        </div>
    <?php } ?>
    <?php if ($toggleContent) { ?>
        <div class="mgz-toggle-content" data-role="content" <?php if (!$open) { ?>style="display: none;"<?php } ?>>
            <?= $coreHelper->filter($toggleContent) ?>
        </div>
    <?php } ?>
</div>

<script>
    loadScript('<?= $block->getViewFileUrl('Hyva_MagezonBuilder::js/jquery.min.js') ?>', 'jquery')
        .then(() => {
            let activeIcon = $('.mgz-toggle-<?= $element->getId() ?>').find('.icon').data('iconActive'),
                icon = $('.mgz-toggle-<?= $element->getId() ?>').find('.icon').data('icon'),
                element = $('.mgz-toggle-<?= $element->getId() ?>');
            if(element.hasClass('active-default')) {
                element.find('.mgz-toggle-title').addClass('active');
            }
            if(element.find('.mgz-toggle-title').hasClass('active')) {
                element.find('.icon').addClass(activeIcon);
            }else{
                element.find('.icon').addClass(icon);
            }
            $('.mgz-toggle-<?= $element->getId() ?> .mgz-toggle-title').click(function(e) {
                if($(this).hasClass('active')) {
                    $(this).find('.icon').removeClass(activeIcon);
                    $(this).find('.icon').addClass(icon);
                    $(this).removeClass('active');
                }else{
                    $(this).find('.icon').removeClass(icon);
                    $(this).find('.icon').addClass(activeIcon);
                    $(this).addClass('active');
                }
                $(this).next().stop().slideToggle(400, 'swing');
            });
        })
</script>