<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Shop By Brand Compatibility with Hyva for Magento 2
 */
/** @var HeroiconsOutline $heroicons */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Hyva\Theme\ViewModel\ProductCompare;
use Hyva\Theme\ViewModel\Wishlist;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

$heroicons = $viewModels->require(HeroiconsOutline::class);
/** @var HeroiconsSolid $heroiconsSolid */
$themeIcons = $viewModels->require(\MgtWizards\Base\ViewModel\ThemeIcons::class);
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);
/** @var Wishlist $wishlistViewModel */
$wishlistViewModel = $viewModels->require(Wishlist::class);
/** @var ProductCompare $compareViewModel */
$compareViewModel = $viewModels->require(ProductCompare::class);
// phpcs:disable Generic.Files.LineLength.TooLong

$themeIcons = $viewModels->require(\MgtWizards\Base\ViewModel\ThemeIcons::class);

?>
<div class="flex-none w-1/2 me-2 py-1 js_slide md:w-1/3 lg:w-1/4 xl:w-1/4" x-init="$nextTick(() => slideRendered())">
    <div
        class="item product product-item card card-interactive border-4 hover:border-whizzy-beige flex flex-col justify-between w-full h-full">
        <a :href="getProductUrl(product)" class="relative flex items-center bg-white product photo product-item-photo"
            tabindex="-1">
            <span class="h-40 lg:h-[250px] mb-4 lg:mb-6 rounded-lg mx-auto">
                <img class="h-full w-full object-cover product-image-photo" :src="product.small_image.url"
                    :alt="product.small_image.label" loading="lazy" width="400" height="400" />
            </span>
        </a>
        <?php if ($wishlistViewModel->isEnabled()): ?>
            <button aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Wish List')) ?>"
                @click.prevent="addToWishlist(product.id)"
                class="!absolute bottom-0 right-6 md:top-auto md:bottom-2 md:right-2 rounded-full w-12 h-12 p-0 border-0 inline-flex shrink-0 items-center justify-center text-gray-500 hover:text-red-600 ml-2">
                <?= $themeIcons->renderHtml('wishlist', 'w-5 h-5', 25, 25, ['aria-hidden' => 'true']) ?>
            </button>
        <?php endif; ?>
        <div class="product-info flex flex-wrap items-center justify-center">
            <div
                class="md:mt-2 mb-2 items-center justify-center text-primary text-sm lg:text-base text-center flex-auto w-full">
                <a class="product-item-link text-sans-serif font-medium min-h-[72px] block"
                    :href="getProductUrl(product)">
                    <span
                        class="mb-1 md:mb-2 items-center text-primary text-sm lg:text-base flex-auto w-full text-ellipsis overflow-hidden line-clamp-2 h-12"
                        x-html="product.name"></span>
                </a>
            </div>

            <template x-if="product.price_range.minimum_price?.final_price?.value">
                <div class="md:pt-1 text-black text-start w-1/2 md:w-full"
                    x-text="hyva.formatPrice(product.price_range.minimum_price.final_price.value)">
                </div>
            </template>

            <a class="justify-center w-full mr-auto btn btn-primary mt-3 text-base" :href="getProductUrl(product)">
                <span class="inline"><?= $escaper->escapeHtml(__('View Product')) ?></span>
            </a>
        </div>
    </div>
</div>