<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Magento\Framework\Escaper;
use Magento\Sales\Block\Order\Creditmemo;

/** @var Creditmemo $block  */
/** @var Escaper $escaper */

$order = $block->getOrder();
?>
<div class="lg:pl-10">
    <div class="flex flex-col lg:flex-row justify-between gap-3 lg:gap-4 mb-4 lg:mb-6">
        <div class="flex flex-col gap-y-2 lg:gap-y-4">
            <div class="text-2xl text-heading mb-2 lg:mb-0">
                <?= $escaper->escapeHtml(__('Order # %1', $order->getRealOrderId())) ?>
            </div>
            <div class="inline-flex justify-between gap-x-3 lg:gap-x-6 items-center text-whizzy-body">
                <div class="text-base">
                    <?= $block->getChildHtml('order.date') ?>
                </div>
                <?= $block->getChildHtml('order.status') ?>
            </div>
        </div>
        <?= $block->getChildHtml('sales.creditmemo.buttons') ?>
    </div>
    <div class="order-details-items creditmemo">

        <div class="mb-6">
            <?= $block->getChildHtml('order_top_items') ?>
        </div>

        <?= $block->getChildHtml('order.comments') ?>

        <div class="mb-4">
            <?= $block->getChildHtml('sales.order.info') ?>
        </div>

        <?= $block->getChildHtml('creditmemo_items') ?>

        <div class="w-full pt-8 lg:pt-0">
            <div class="flex justify-center lg:justify-start">
                <a class="action back text-base py-2 lg:py-4 text-whizzy-body underline font-medium"
                    href="<?= $escaper->escapeUrl($block->getBackUrl()) ?>">
                    <span><?= $escaper->escapeHtml($block->getBackTitle()) ?></span>
                </a>
            </div>
        </div>

    </div>
</div>