<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Magento\Framework\Escaper;
use Magento\Sales\Block\Order\Info;

/** @var Info $block */
/** @var Escaper $escaper */
?>

<span class="order-status px-4 py-1 text-white bg-whizzy-body rounded-full">
    <span class="sr-only">
        <?= $escaper->escapeHtml(__('Status')) ?>:&nbsp;
    </span>
    <div class="text-sm lg:text-base">
        <?= $escaper->escapeHtml($block->getOrder()->getStatusLabel()) ?>
    </div>
</span>