<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Magento\Framework\Escaper;
use Magento\GiftMessage\Helper\Message;
use Magento\Sales\Block\Order\View;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper

/** @var View $block */
/** @var Escaper $escaper */

$giftMessageHelper = $this->helper(Message::class);

$order = $block->getOrder();

$themeIcons = $viewModels->require(\MgtWizards\Base\ViewModel\ThemeIcons::class);

?>
<div>
    <div
        class="flex flex-col lg:flex-row justify-between gap-3 lg:gap-4 mb-4 lg:mb-6 bg-white shadow-whizzy-base p-6 rounded-lg">
        <div class="flex flex-col gap-y-2 lg:gap-y-4">
            <div class="text-2xl text-heading mb-2 lg:mb-0">
                <?= $escaper->escapeHtml(__('Order # %1', $order->getRealOrderId())) ?>
            </div>
            <div class="inline-flex justify-between gap-x-3 lg:gap-x-6 items-center text-whizzy-brown">
                <div class="text-base">
                    <?= $block->getChildHtml('order.date') ?>
                </div>
                <?= $block->getChildHtml('order.status') ?>
            </div>
        </div>
        <?php if (!$block->getData('is_context_shipment')): ?>
            <?= $block->getChildHtml('sales.order.buttons') ?>
        <?php else: ?>
            <?= $block->getChildHtml('sales.shipment.buttons') ?>
        <?php endif; ?>
    </div>
    <div class="order-details-items ordered">

        <div class="mb-6">
            <?= $block->getChildHtml('order_top_items') ?>
        </div>

        <div class="mb-6">
            <?= $block->getChildHtml('sales.order.info') ?>
        </div>

        <?php if (!$block->getData('is_context_shipment')): ?>
            <div class="order-title">
                <div class="flex lg:flex-row p-6 bg-white shadow-whizzy-header rounded-lg h-full w-full mb-8">
                    <span class="text-2xl text-heading"><?= __('My Order') ?></span>
                </div>
                <?php if (!empty($order->getTracksCollection()->getItems())): ?>
                    <?= $block->getChildHtml('tracking-info-link') ?>
                <?php endif; ?>
            </div>
        <?php endif; ?>
        <?= $block->getChildHtml('order_items') ?>

        <div>

            <?php if ($giftMessageHelper->isMessagesAllowed('order', $order) && $order->getGiftMessageId()): ?>
                <div class="block block-order-details-gift-message">
                    <div class="block-title"><strong><?= $escaper->escapeHtml(__('Gift Message for This Order')) ?></strong>
                    </div>
                    <?php
                    $giftMessage =
                        $giftMessageHelper->getGiftMessageForEntity($order);
                    ?>
                    <div class="block-content">
                        <dl class="item-options">
                            <dt class="item-sender">
                                <strong class="label">
                                    <?= $escaper->escapeHtml(__('From')) ?>
                                </strong>
                                <?= $escaper->escapeHtml($giftMessage->getSender()) ?>
                            </dt>
                            <dt class="item-recipient">
                                <strong class="label">
                                    <?= $escaper->escapeHtml(__('To')) ?>
                                </strong>
                                <?= $escaper->escapeHtml($giftMessage->getRecipient()) ?>
                            </dt>
                            <dd class="item-message">
                                <?= /* @noEscape */ $giftMessageHelper->getEscapedGiftMessage($order) ?>
                            </dd>
                        </dl>
                    </div>
                </div>
            <?php endif; ?>

        </div>

        <div class="w-full pt-8 lg:pt-0">
            <div class="flex justify-center lg:justify-start">
                <a class="action back text-base py-2 lg:py-4 text-whizzy-brown underline font-medium"
                    href="<?= $escaper->escapeUrl($block->getBackUrl()) ?>">
                    <span><?= $escaper->escapeHtml($block->getBackTitle()) ?></span>
                </a>
            </div>
        </div>
    </div>
</div>