<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\ProductAttributes;
use Hyva\Theme\ViewModel\ProductCompare;
use Hyva\Theme\ViewModel\ProductPage;
use Hyva\Theme\ViewModel\Wishlist;
use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Amasty\ShopbyBrand\ViewModel\OptionProcessor;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var ProductPage $productViewModel */
$productViewModel = $viewModels->require(ProductPage::class);
/** @var ProductAttributes $attributesViewModel */
$attributesViewModel = $viewModels->require(ProductAttributes::class);
/** @var Product $product */
$product = $productViewModel->getProduct();
$productType = $product->getTypeId();
$productName = $product->getName();
$productId = $product->getId();
$productShortDescription = $product->getShortDescription();
$hideRatingSummary = $block->getData('hide_rating_summary') ?: false;
$optionProcessor = $viewModels->require(OptionProcessor::class);
?>
<div class="flex flex-col w-full">

    <div class="flex flex-col gap-2 mb-4">
        <div class="flex justify-between items-center">
            <?php if (!$hideRatingSummary): ?>
                <?= $block->getChildHtml('product.info.review') ?>
            <?php endif; ?>
            <?php if ($additionalActions = $block->getChildHtml('product.info.additional.actions')): ?>
                <?= /** @noEscape */ $additionalActions; ?>
            <?php endif; ?>
        </div>
        <h1 class="font-bold text-3xl lg:text-4xl">
            <?= $escaper->escapeHtmlAttr($productName) ?>
        </h1>
    </div>

    <div x-data="" id="gallery-mobile"></div>

    <div class="relative mb-4" x-data="{ showTooltip: false }" @mouseover="showTooltip = true"
        @mouseleave="showTooltip = false">
        <div class="cvb-bol">
            <span class="prefix"><?= __('Veilig en snel') ?></span>
            <img src="/media/wysiwyg/button_checkout_via_bol.svg" alt="bol Payment Gateway"
                class="h-12 w-auto cursor-pointer">
        </div>
        <div x-show="showTooltip"
            class="absolute z-10 w-64 p-3 bg-white text-sm rounded-lg shadow-lg border-2 border-whizzy-primary-lighter top-full left-0 ml-2 z-20"
            x-cloak x-transition>
            <p class="mb-1 text-base"><strong><?= __('Checkout via bol') ?></strong></p>
            <p><?= __('Gebruik je bol account om snel en makkelijk de bestelling af te ronden') ?></p>
            <p><?= __('De bestelling wordt afgehandeld en geleverd door onze webshop.') ?></p>
        </div>
    </div>

    <style>
        .cvb-bol {
            position: relative;
            display: inline-flex;
            align-items: center;
            cursor: help;
            width: fit-content;
            justify-content: space-between;
            padding: 8px 0px 8px 14px;
            border-radius: 24px;
            background-image: radial-gradient(circle at 75% 200%, rgb(0, 0, 164) 47%, rgb(237, 243, 255) 47.7%);
        }

        .cvb-bol .prefix {
            color: #0000A4;
            font-size: 0.9rem;
            line-height: 16px;
        }

        .cvb-bol img {
            margin-left: 12px;
            margin-top: -2px;
            height: 16px;
            object-fit: contain;
            display: block;
            cursor: help;
        }
    </style>

    <?= $this->getLayout()->createBlock("Amasty\ShopbyBase\Block\Product\AttributeIcon")
    ->setData(['attribute_codes' => ['merk'], 'option_processor' => $optionProcessor, 'product' => $product, 'page_type' => 'listing'])
    ->setTemplate("Amasty_ShopByBrandHyvaCompatibility::attribute/icon.phtml")
    ->toHtml(); ?>

    <?php if ($productShortDescription): ?>
        <div class="product-short-description">
            <?= __($productShortDescription) ?>
        </div>
    <?php endif; ?>

    <div class="flex flex-col lg:flex-row justify-between items-start lg:items-end text-base lg:text-xl lg:mt-2 mb-4">
        <div role="group" aria-label="<?= $escaper->escapeHtmlAttr('Price') ?>">
            <?php if ($productType === 'grouped'): ?>
                <?= $this->getProductPrice($product); ?>
            <?php else: ?>
                <?= $block->getChildHtml("product.info.price") ?>
            <?php endif; ?>
        </div>
        <div class="flex flex-row gap-4">
            <div class="flex flex-col gap-2 text-sm font-regular">
                <?= $block->getChildHtml("product.info.stockstatus") ?>
                <?= $block->getChildHtml("alert.urls") ?>
                <div class="w-full">
                    <dl id="product-details">
                        <?php foreach ($block->getAttributes() as $attributeConfig):
                            $attribute = $attributesViewModel->getAttributeFromLayoutConfig($attributeConfig); ?>
                            <?php if ($value = $attribute['value'] ?? null): ?>
                                <?php if ($attribute['label'] === 'Color'): ?>
                                <?php else: ?>
                                    <div class="flex attribute-<?=/* @noEscape */ $attribute['code'] ?: "" ?>">
                                        <div class="w-full inline-flex items-center lg:justify-end">
                                            <dt class="text-left product-detail-label">
                                                <?= $escaper->escapeHtml($attribute['label']) ?>
                                            </dt>
                                            <dd class="hyphens-none break-normal ml-2 text-left product-detail-value">
                                                <?= $escaper->escapeHtml($value) ?>
                                            </dd>
                                        </div>
                                    </div>
                                <?php endif; ?>
                            <?php endif ?>
                        <?php endforeach; ?>
                    </dl>
                </div>
            </div>
        </div>
    </div>

    <?= $block->getChildHtml('product.info.form') ?>

    <?php if ($productType === 'grouped'): ?>
    <?php elseif ($productType === 'simple'): ?>
        <?php if ($tierPriceBlock = $block->getChildHtml("product.price.tier")): ?>
            <div class="tier-price-container">
                <?= /** @noEscape */ $tierPriceBlock ?>
            </div>
        <?php endif; ?>
    <?php endif; ?>

    <div class="flex flex-col gap-y-3">
        <?php if ($product->isSaleable()): ?>
            <div class="flex flex-row gap-3">
                <?= $block->getChildHtml("product.info.quantity") ?>
                <?= $block->getChildHtml("product.info.addtocart") ?>
            </div>
        <?php endif; ?>

        <a href="https://www.webwinkelkeur.nl/webshop/OnlineCameraShop-NL_1218762" target="_blank"
            rel="noopener noreferrer nofollow"
            class="relative z-10 rounded-lg bg-whizzy-primary-lighter p-2 lg:p-3 flex flex-col justify-center items-center border-2 border-whizzy-primary text-whizzy-primary">
            <div class="text-xl font-semibold">
                OnlineCameraShop.NL
            </div>
            <div class="flex items-center justify-between gap-3">
                <div class="flex items-end leading-none">
                    <span class="text-2xl font-bold text-gray-900">9.5</span>
                    <span class="text-sm text-gray-500 ml-0.5 mb-0.5">/10</span>
                </div>
                <div class="flex items-center text-yellow-400">
                    <svg class="w-6 h-6 fill-current" viewBox="0 0 20 20">
                        <path
                            d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.286 3.966a1 1 0 00.95.69h4.173c.969 0 1.371 1.24.588 1.81l-3.376 2.455a1 1 0 00-.364 1.118l1.287 3.966c.3.921-.755 1.688-1.54 1.118l-3.376-2.455a1 1 0 00-1.176 0l-3.376 2.455c-.784.57-1.838-.197-1.539-1.118l1.286-3.966a1 1 0 00-.364-1.118L2.098 9.393c-.783-.57-.38-1.81.588-1.81h4.173a1 1 0 00.951-.69l1.239-3.966z">
                        </path>
                    </svg>
                    <svg class="w-6 h-6 fill-current" viewBox="0 0 20 20">
                        <path
                            d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.286 3.966a1 1 0 00.95.69h4.173c.969 0 1.371 1.24.588 1.81l-3.376 2.455a1 1 0 00-.364 1.118l1.287 3.966c.3.921-.755 1.688-1.54 1.118l-3.376-2.455a1 1 0 00-1.176 0l-3.376 2.455c-.784.57-1.838-.197-1.539-1.118l1.286-3.966a1 1 0 00-.364-1.118L2.098 9.393c-.783-.57-.38-1.81.588-1.81h4.173a1 1 0 00.951-.69l1.239-3.966z">
                        </path>
                    </svg>
                    <svg class="w-6 h-6 fill-current" viewBox="0 0 20 20">
                        <path
                            d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.286 3.966a1 1 0 00.95.69h4.173c.969 0 1.371 1.24.588 1.81l-3.376 2.455a1 1 0 00-.364 1.118l1.287 3.966c.3.921-.755 1.688-1.54 1.118l-3.376-2.455a1 1 0 00-1.176 0l-3.376 2.455c-.784.57-1.838-.197-1.539-1.118l1.286-3.966a1 1 0 00-.364-1.118L2.098 9.393c-.783-.57-.38-1.81.588-1.81h4.173a1 1 0 00.951-.69l1.239-3.966z">
                        </path>
                    </svg>
                    <svg class="w-6 h-6 fill-current" viewBox="0 0 20 20">
                        <path
                            d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.286 3.966a1 1 0 00.95.69h4.173c.969 0 1.371 1.24.588 1.81l-3.376 2.455a1 1 0 00-.364 1.118l1.287 3.966c.3.921-.755 1.688-1.54 1.118l-3.376-2.455a1 1 0 00-1.176 0l-3.376 2.455c-.784.57-1.838-.197-1.539-1.118l1.286-3.966a1 1 0 00-.364-1.118L2.098 9.393c-.783-.57-.38-1.81.588-1.81h4.173a1 1 0 00.951-.69l1.239-3.966z">
                        </path>
                    </svg>
                    <svg class="w-6 h-6" viewBox="0 0 20 20">
                        <defs>
                            <linearGradient id="half">
                                <stop offset="50%" stop-color="currentColor"></stop>
                                <stop offset="50%" stop-color="#e5e7eb"></stop>
                            </linearGradient>
                        </defs>
                        <path fill="url(#half)"
                            d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.286 3.966a1 1 0 00.95.69h4.173c.969 0 1.371 1.24.588 1.81l-3.376 2.455a1 1 0 00-.364 1.118l1.287 3.966c.3.921-.755 1.688-1.54 1.118l-3.376-2.455a1 1 0 00-1.176 0l-3.376 2.455c-.784.57-1.838-.197-1.539-1.118l1.286-3.966a1 1 0 00-.364-1.118L2.098 9.393c-.783-.57-.38-1.81.588-1.81h4.173a1 1 0 00.951-.69l1.239-3.966z">
                        </path>
                    </svg>
                </div>
            </div>
        </a>

    </div>

    <?= $block->getChildHtml("product.info.additional") ?>
</div>

<script>
    /* https://github.com/nabeghe/alpine-portal */
    !function (e) { "function" == typeof define && define.amd ? define(e) : e() }((function () { "use strict"; function e(e) { this.target = null, this.screen = 0; const t = e.parentElement; let n = null; this.update = () => { n && (n.removeEventListener("change", this.onResize), n = null), 0 !== this.screen && (n = window.matchMedia(`(${this.screen > 0 ? "min" : "max"}-width: ${Math.abs(this.screen)}px)`), n.addEventListener("change", this.onResize)) }, this.onResize = n => { n.matches ? document.querySelector(this.target).appendChild(e) : t.appendChild(e) }, window.Alpine.nextTick((() => this.onResize(n))) } const t = []; document.addEventListener("alpine:init", (() => { window.Alpine.directive("portal", ((n, { value: i, expression: s }, { evaluate: a }) => { i || void 0 !== n._x_portal || (n._x_portal = new e(n), t.push(n._x_portal)), !1 !== s && (i ? s = a(s) : i = "target", n._x_portal[i] = s, i && "screen" === i && n._x_portal.update()) })) })) }));
</script>