<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\StoreConfig;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

$storeConfig = $viewModels->require(StoreConfig::class);
$maxItemsToDisplay = $storeConfig->getStoreConfig('checkout/sidebar/max_items_display_count');

/** @var HeroiconsOutline $heroIcons */
$heroIcons = $viewModels->require(HeroiconsOutline::class);

/** @var HeroiconsSolid $heroIconsSolid */
$heroIconsSolid = $viewModels->require(HeroiconsSolid::class);

$themeIcons = $viewModels->require(\MgtWizards\Base\ViewModel\ThemeIcons::class);

$miniCartOptionQtyStyle = (string)$block->getQtyStyle() ?: 'default';
$miniCartOptionShowSku = $block->getShowSku() !== null ? (bool)$block->getShowSku() : false;
$miniCartOptionQtySaveAuto = $miniCartOptionQtyStyle === "incrementor" || $miniCartOptionQtyStyle === "select";

// Whizzy Helper
$whizzyHelper = $this->helper('ShopWhizzy\DigitalTheme\Helper\Data');
$product_image_background = (($whizzyHelper->getConfigValue('general/product_image_background')) ? 'bg-whizzy-artic' : '');
$product_image_background_custom = (($product_image_background_custom_value = $whizzyHelper->getConfigValue('general/product_image_background_custom')) ? "style=\"background-color:{$product_image_background_custom_value}\";" : '');
$product_image_background_mixblend = ($whizzyHelper->getConfigValue('general/product_image_background_mixblend') ? 'mix-blend-multiply' : '');
$product_image_padding = ($whizzyHelper->getConfigValue('general/product_image_padding') ? 'p-1.5 lg:p-3' : '');
$product_image_square = ($whizzyHelper->getConfigValue('general/product_image_square') ? 'aspect-square object-center object-contain' : 'object-cover');

$header_layout = $whizzyHelper->getConfigValue('header/header_layout');
$cart_margins = 'mx-6';
if ($header_layout === 'header_3')
{
    $cart_margins = 'mt-3 mx-6 lg:mx-0';
}
?>
<script>
    function initCartDrawer() {
        return {
            open: false,
            isLoading: false,
            cart: {},
            maxItemsToDisplay: <?= (int)$maxItemsToDisplay ?>,
            itemsCount: 0,
            showSku: <?= $miniCartOptionShowSku ? 'true' : 'false' ?>,
            getData(data) {
                if (data.cart) {
                    this.cart = data.cart;
                    this.itemsCount = data.cart.items && data.cart.items.length || 0;
                    this.setCartItems();
                }
                this.isLoading = false;
            },
            cartItems: [],
            getItemCountTitle() {
                return hyva.strf('<?= $escaper->escapeJs(__('%0 of %1 products in cart displayed')) ?>', this.maxItemsToDisplay, this.itemsCount)
            },
            setCartItems() {
                this.cartItems = this.cart.items && this.cart.items.sort((a, b) => b.item_id - a.item_id) || [];

                if (this.maxItemsToDisplay > 0) {
                    this.cartItems = this.cartItems.slice(0, parseInt(this.maxItemsToDisplay, 10));
                }
            },
            updateItemQty(form) {
                if (!form.action) return;
                this.isLoading = true;
                const action = form.action;
                const formData = new FormData(form);
                formData.append('form_key', hyva.getFormKey());

                if (!formData.uenc) {
                    formData.append('uenc', hyva.getUenc());
                }

                fetch(action, {
                    body: formData,
                    method: 'POST',
                    mode: "cors",
                    credentials: "include"
                }).then((result) => {
                    return result.text()
                }).then((content) => {
                    window.dispatchEvent(new CustomEvent("reload-customer-section-data"));
                }).catch((error) => {
                    window.dispatchMessages && window.dispatchMessages([{
                        type: 'error',
                        text: '<?= $escaper->escapeJs(__("Something went wrong. Please try again.")) ?>'
                    }]);
                }).finally(() => {
                    this.isLoading = false;
                })
            },
            deleteItemFromCart(itemId) {
                this.isLoading = true;

                const formKey = hyva.getFormKey();
                const postUrl = BASE_URL + 'checkout/sidebar/removeItem/';

                fetch(postUrl, {
                    headers: {
                        "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    },
                    body: "form_key=" + formKey + "&item_id=" + itemId,
                    method: "POST",
                    mode: "cors",
                    credentials: "include"
                }).then(response => {
                    if (response.redirected) {
                        window.location.href = response.url;
                    } else if (response.ok) {
                        return response.json();
                    } else {
                        window.dispatchMessages && window.dispatchMessages([{
                            type: 'warning',
                            text: '<?= $escaper->escapeJs(__('Could not remove item from quote.')) ?>'
                        }]);
                        this.isLoading = false;
                    }
                }).then(result => {
                    window.dispatchMessages && window.dispatchMessages([{
                        type: result.success ? 'success' : 'error',
                        text: result.success
                            ? '<?= $escaper->escapeJs(__('You removed the item.')) ?>'
                            : result.error_message
                    }], result.success ? 5000 : 0)
                    window.dispatchEvent(new CustomEvent('reload-customer-section-data'));
                });
            },
            toggleCartDrawer(event) {
                if (event.detail && event.detail.isOpen) {
                    this.open = event.detail.isOpen;
                } else {
                    this.open = !this.open;
                }
                this.calcCartDrawerAnchor();
            },
            openCartDrawer() {
                this.open = true;
                this.calcCartDrawerAnchor();
            },
            closeCartDrawer() {
                this.open = false;
            },
            getSectionDataExtraActions() {
                if (!this.cart.extra_actions || typeof hyva.activateScripts === "undefined") {
                    return '';
                }

                const contentNode = document.createElement('div');
                contentNode.innerHTML = this.cart.extra_actions;
                hyva.activateScripts(contentNode);

                return contentNode.innerHTML;
            },
            calcCartDrawerAnchor() {
                const btn = this.$refs.cartButton ? this.$refs.cartButton.getBoundingClientRect() : {};
                const scrollOffset = window.pageYOffset || document.documentElement.scrollTop;
                const btnOffset = btn.top && (btn.top + btn.height);
                const offsetTop = btnOffset
                    ? `${btnOffset < 0 ? btnOffset + scrollOffset : btnOffset}px`
                    : "1rem";
                const offsetRight = btn.right ? `${Math.floor((window.innerWidth - btn.right) + (btn.width / 4))}px` : "1rem";

                const drawer = this.$refs.cartDialogContent;
                drawer.style.setProperty('--cart-drawer-offset-top', offsetTop);
                drawer.style.setProperty('--cart-drawer-offset-right', offsetRight);
            },
            cartListeners: {
                ['@private-content-loaded.window'](event) {
                    this.getData(event.detail.data);
                },
                ['@toggle-cart.window'](event) {
                    this.toggleCartDrawer(event);
                },
                ['@keydown.window.escape']() {
                    this.$dispatch('toggle-cart', { isOpen: false })
                },
                ['@click.outside'](event) {
                    this.$dispatch('toggle-cart', { isOpen: false })
                },
                ['@resize.window.debounce']() {
                    if (!this.open) return;
                    this.calcCartDrawerAnchor();
                }
            }
        }
    }
</script>
<section id="cart-drawer" aria-labelledby="cart-drawer-title"
    class="absolute top-full right-0 <?= $cart_margins ?> w-[calc(100%-48px)] flex flex-col z-40 lg:max-w-[520px] lg:w-full bg-white shadow-whizzy-header rounded-lg text-whizzy-body"
    x-show="open" x-transition.origin.top.right x-ref="cartDialogContent" x-data="initCartDrawer()"
    x-bind="cartListeners" x-cloak :aria-hidden="!open">

    <div>
        <?= $block->getChildHtml('cart-drawer.top'); ?>

        <div class="inline-flex justify-between items-center rounded-t-lg w-full p-4 pb-2 lg:p-8 lg:pb-4">
            <p id="cart-drawer-title" class="inline-flex gap-2 items-center">
                <span class="font-semibold text-xl lg:text-3xl"><?= $escaper->escapeHtml(__('Cart')) ?></span>
                <span
                    class="items-total w-8 h-8 bg-whizzy-artic leading-5 flex items-center justify-center text-xs rounded-full"
                    x-text="cart.summary_count"></span>
            </p>
            <button type="button" @click="closeCartDrawer"
                class="flex justify-center items-center bg-white text-whizzy-body hover:text-whizzy-graylighter shadow-whizzy-header border-0 transition-all duration-300 p-3 rounded-lg focus:ring-0 shrink-0">
                <?= $themeIcons->renderHtml('close', '', 18, 18) ?>
            </button>
        </div>

        <?= $block->getChildHtml('cart-drawer.items.before'); ?>

        <template x-if="!itemsCount">
            <div class="grow grid place-items-center md:min-h-auto mx-4">
                <div class="text-center flex flex-col gap-2 mb-4 lg:mb-6">
                    <div class="w-full flex justify-center">
                        <div
                            class="flex justify-center items-center bg-white shadow-whizzy-header border-0 transition-all duration-300 p-4 rounded-lg focus:ring-0 w-fit">
                            <?= $themeIcons->renderHtml('cart', 'text-whizzy-body', 32, 32) ?>
                        </div>
                    </div>
                    <p class="mt-10 text-xl text-whizzy-body">
                        <strong><?= $escaper->escapeHtml(__('Your cart is empty')) ?></strong>
                    </p>
                    <p class="text-whizzy-graylighter">
                        <?= $escaper->escapeHtml(__("Looks like you haven't made your choice yet.")) ?>
                    </p>
                </div>
            </div>
        </template>

        <div class="flex overflow-y-auto max-h-[324px] bg-white">
            <template x-if="itemsCount">
                <ul id="cart-form-scroll"
                    class="grow flex flex-col gap-2 overflow-y-auto overscroll-y-contain mask-overflow mask-dir-y pl-4 lg:pl-8 pr-2 mr-2 lg:pr-4 lg:mr-4">
                    <template x-for="item in cartItems">
                        <li class="grid grid-cols-3 gap-x-4 border-b border-whizzy-separator last:border-0 pt-2 pb-4">
                            <div class="h-fit">
                                <a class="block shrink-0 w-full rounded-lg bg-whizzy-artic <?= $product_image_padding ?>"
                                    <?= $product_image_background_custom ?> :href="item.product_url"
                                    :title="hyva.str('<?= $escaper->escapeJs(__('Product "%1"')) ?>', item.product_name)">
                                    <img :src="item.product_image.src" :width="item.product_image.width"
                                        :height="item.product_image.height" loading="lazy"
                                        class="mx-auto <?= $product_image_background_mixblend ?> <?= $product_image_square ?>"
                                        :alt="hyva.str('<?= $escaper->escapeJs(__('Product "%1"')) ?>', item.product_name)">
                                </a>
                            </div>

                            <div class="grow flex justify-between flex-col gap-2 col-span-2">
                                <div class="flex gap-3 lg:gap-4 justify-between items-start">
                                    <p class="text-sm font-medium">
                                        <?php if ($miniCartOptionQtyStyle === "text"): ?>
                                            <span x-text="item.qty + ' x '"></span>
                                        <?php endif; ?>
                                        <a class="hover:text-whizzy-graylighter transition-all duration-200"
                                            :href="item.product_url" x-html="item.product_name"></a>
                                    </p>
                                    <span class="[&_.price]:font-medium text-sm" x-html="item.product_price"></span>
                                </div>

                                <template x-if="item.options && item.options.length || showSku">
                                    <dl class="table text-xs lg:text-sm w-full">
                                        <template x-if="showSku">
                                            <div class="inline-flex gap-1 text-whizzy-graylighter text-sm">
                                                <span><?= $escaper->escapeHtml(__('Sku:')) ?></span>
                                                <span x-html="item.product_sku"></span>
                                            </div>
                                        </template>
                                    </dl>
                                </template>
                                <div
                                    class="flex flex-wrap gap-2 <?= $miniCartOptionQtyStyle === "text" ? 'justify-end' : 'justify-between' ?> items-center">
                                    <?php if ($miniCartOptionQtyStyle !== "text"): ?>
                                        <form
                                            action="<?= $escaper->escapeUrl($block->getUrl('checkout/cart/updatePost')) ?>"
                                            x-data="{
                            initQty: item.qty,
                            itemQty: item.qty,
                            prevQty: item.qty,
                            updateQty() {
                                const submitEvent = new Event('submit', { cancelable: true });
                                this.$root.dispatchEvent(submitEvent);
                            },
                            setQtyDefaults() {
                                this.initQty = item.qty;
                                this.itemQty = item.qty;
                                this.prevQty = item.qty;
                            }
                        }" @submit.prevent="updateItemQty($event.target);"
                                            x-init="$watch('item.qty', () => setQtyDefaults());" method="post"
                                            class="form form-cart flex flex-row items-center gap-2 h-full">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <div id="cart-form" class="px-2.5 bg-whizzy-artic rounded mt-2 lg:mt-0">
                                                <?php if ($miniCartOptionQtyStyle === "incrementor"): ?>
                                                    <button type="button" @click="itemQty <= 0 ? itemQty = 0 : itemQty--"
                                                        @click.debounce.1000ms="updateQty($event);"
                                                        class="h-full text-whizzy-body hover:text-whizzy-graylighter transition-all duration-200">
                                                        <?= $heroIcons->minusHtml('', 14, 14, ['aria-hidden' => 'true']); ?>
                                                    </button>
                                                <?php endif; ?>
                                                <span class="sr-only"><?= $escaper->escapeHtml(__('Qty')) ?></span>
                                                <input type="number" <?php if ($miniCartOptionQtyStyle === "select"): ?>
                                                        :placeholder="initQty" list="minicart-autocomplete"
                                                        @focus="prevQty = itemQty; itemQty = null"
                                                        @blur="itemQty === null ? itemQty = prevQty : () => {}" <?php endif; ?>
                                                    <?php if ($miniCartOptionQtySaveAuto): ?>
                                                        @change.debounce.1000ms="updateQty($event)" <?php endif; ?>
                                                    class="qty p-0 border-0 shadow-none [-moz-appearance:textfield]
                                                        <?= $miniCartOptionQtyStyle === "select"
                                                            ? 'form-select focus:bg-none [&::-webkit-list-button]:w-0 [&::-webkit-calendar-picker-indicator]:!hidden'
                                                            : 'form-input' ?>
                                                        <?= $miniCartOptionQtyStyle === "incrementor" ? 'h-2 w-8 text-center' : 'h-2 w-12' ?>
                                                        <?= $miniCartOptionQtyStyle === "select" || $miniCartOptionQtyStyle === "incrementor"
                                                            ? '[&::-webkit-inner-spin-button]:hidden'
                                                            : 'hover:[-moz-appearance:auto] [&::-webkit-inner-spin-button]:invisible hover:[&::-webkit-inner-spin-button]:visible' ?>"
                                                    required min="0" step="any" x-model.number="itemQty"
                                                    :id="`minicart-${item.item_id}-qty`"
                                                    :name="`cart[${item.item_id}][qty]`">
                                                <?php if ($miniCartOptionQtyStyle === "incrementor"): ?>
                                                    <button type="button" @click="itemQty++"
                                                        @click.debounce.1000ms="updateQty($event);"
                                                        class="h-full text-whizzy-body hover:text-whizzy-graylighter transition-all duration-200">
                                                        <?= $heroIcons->plusHtml('', 14, 14, ['aria-hidden' => 'true']); ?>
                                                    </button>
                                                <?php endif; ?>
                                            </div>
                                            <?php if (!$miniCartOptionQtySaveAuto): ?>
                                                <button type="submit"
                                                    class="btn btn-secondary inline-flex items-center gap-2 focus:border focus:border-whizzy-separator focus:ring-0 focus:offset-0 focus:outline-none cursor-pointer w-fit mx-2"
                                                    :disabled="itemQty === initQty || itemQty === null" :aria-label="hyva.str(
                                    '<?= $escaper->escapeJs(__('Update qty for "%1"')) ?>',
                                    item.product_name
                                )">
                                                    <?= __('Save') ?>
                                                    <?= $heroIconsSolid->checkHtml('', 16, 16, ['aria-hidden' => 'true']); ?>
                                                </button>
                                            <?php endif; ?>
                                        </form>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <div class="col-span-3 flex w-full justify-start">
                                <button type="button"
                                    class="inline-flex w-full items-center gap-1 text-whizzy-graylighter hover:text-whizzy-body transition-all duration-200 mt-3 lg:mt-2 font-medium text-sm"
                                    @click="deleteItemFromCart(item.item_id)" :aria-label="hyva.str(
                            '<?= $escaper->escapeJs(__('Remove product "%1" from cart')) ?>',
                            item.product_name)">
                                    <?= $themeIcons->renderHtml('close', '', 15, 15) ?>
                                    <?= __('Remove') ?>
                                </button>
                            </div>
                        </li>
                    </template>
                </ul>
            </template>
        </div>

        <?= $block->getChildHtml('cart-drawer.bottom'); ?>

        <template x-if="itemsCount">
            <div
                class="flex flex-col gap-4 lg:gap-6 bg-white shadow-whizzy-menu-negative w-full rounded-lg px-4 py-6 lg:p-8">
                <?= $block->getChildHtml('cart-drawer.totals.before'); ?>

                <div class="flex flex-col gap-2">
                    <div class="inline-flex justify-between items-center text-sm font-semibold text-whizzy-body">
                        <span class="text-lg"><?= $escaper->escapeHtml(__('Subtotal')) ?></span>
                        <span x-html="cart.subtotal" class="text-lg"></span>
                    </div>
                    <span class="text-whizzy-graylighter text-xs font-medium">
                        <?= __('Tax and shipping calculated at checkout') ?>
                    </span>
                </div>

                <div class="flex flex-col">
                    <a @click.prevent.stop="closeCartDrawer; $dispatch('toggle-authentication', { url: '<?= $escaper->escapeUrl($block->getUrl('checkout')) ?>' });"
                        href="<?= $escaper->escapeUrl($block->getUrl('checkout')) ?>"
                        class="btn btn-primary py-3 font-medium uppercase">
                        <?= $escaper->escapeHtml(__('Secure Checkout')) ?>
                        <?= $themeIcons->renderHtml('cart-secure', 'ml-2', 24, 24, ['aria-hidden' => 'true']) ?>
                    </a>
                    <a href="<?= $escaper->escapeUrl($block->getUrl('checkout/cart')) ?>"
                        class="group inline-flex gap-2 justify-center items-center w-full text-whizzy-body hover:text-whizzy-body transition-all duration-300 mt-2">
                        <?= $escaper->escapeHtml(__('View Cart')) ?>
                        <?= $themeIcons->renderHtml('arrow-up-right', 'group-hover:rotate-45 transition-all duration-200', 18, 18, ['aria-hidden' => 'true']) ?>
                    </a>
                    <div x-html="getSectionDataExtraActions()"></div>
                    <?= $block->getChildHtml('extra_actions'); ?>
                </div>
            </div>
        </template>

        <template x-if="!itemsCount">
            <div class="flex justify-center w-full pb-12">
                <button type="button" @click="closeCartDrawer"
                    class="btn btn-primary py-4 mx-auto w-fit"><?= $escaper->escapeHtml(__('Continue shopping')) ?></button>
            </div>
        </template>

        <?php if ($miniCartOptionQtyStyle === "select"): ?>
            <datalist id="minicart-autocomplete">
                <template x-for="i in 100">
                    <option :value="i"></option>
                </template>
            </datalist>
        <?php endif; ?>

        <?= $block->getChildHtml('loading') ?>
    </div>

</section>